import type { LabPracticeContent } from "./_schema";

/**
 * AIF — Laboratorio, Módulo II (Prof. Nicolás Mateo González), subgrupo J5
 * (Karen Pachón + César Díaz). Parte A: Prácticas 1 y 2 (métodos físicos).
 * Fuente: «Guías Practicas de laboratorio - Módulo II» + cronograma del grupo.
 * Material de referencia: no pasa por `db:seed`. Estándar de contenido AIF:
 * interpretación → factor de conversión explícito → resultado → conclusión.
 * Los números de los ejemplos son ILUSTRATIVOS (para mostrar el método); los
 * datos reales salen de tu medición.
 */
export const aifModulo2PracticasA: LabPracticeContent[] = [
  // ───────────────────────────── PRÁCTICA 1 ─────────────────────────────
  {
    number: 1,
    labModule: "Módulo II",
    title: "Refractometría: índice de refracción, °Brix y °Baumé (etanol + agua)",
    moduleSlug: "metodos-fisicos",
    fundamento:
      "El **índice de refracción (n)** mide cuánto se desvía la luz al pasar de un medio a otro; es una **constante física** de cada sustancia a una longitud de onda y temperatura dadas (n_D²⁰: línea D del sodio, 20 °C). Con el **refractómetro de Abbe** se mide n de mezclas **etanol + agua** de concentración conocida, se construye una **curva de calibración** (n vs. % p/p, con °Brix y °Baumé como escalas derivadas) y se interpola en ella la concentración de **dos muestras problema**.",
    desarrollo: [
      "#### En una frase",
      "",
      "Vas a medir cuánto se «dobla» la luz al atravesar mezclas de **etanol y agua** de concentración conocida (eso arma la curva de calibración) y vas a usar esa curva para descubrir la concentración de **dos muestras problema**. Nada más. Todo lo demás de esta práctica es el *cómo* de esa frase.",
      "",
      "> **Analogía — la pajilla «quebrada».** Mete una pajilla en un vaso con agua: se ve doblada justo en la superficie. La luz viaja más lento en el agua que en el aire, y por eso se desvía al cruzar la superficie. Si en vez de agua pones agua con etanol, el «quiebre» cambia un poquito. El refractómetro mide ese quiebre con precisión de cuatro decimales, y ese quiebre depende de **cuánto etanol hay**.",
      "",
      "#### Qué es el índice de refracción (n), sin dar nada por sabido",
      "",
      "**Interpretación.** La luz va a su máxima velocidad (*c* ≈ 3,00 × 10⁸ m/s) en el vacío. En cualquier material va más lenta (*v*). El índice de refracción es **cuántas veces más lenta** va la luz en ese material:",
      "",
      "```formula",
      "n = #{c|v}",
      "```",
      "",
      "- *n* **no tiene unidades** (es una razón entre dos velocidades) y siempre es ≥ 1.",
      "- Para el agua, n = 1,3330 (a 20 °C, línea D del sodio). **Factor de conversión:** v = c ÷ n = (3,00 × 10⁸ m/s) ÷ 1,3330 = 2,25 × 10⁸ m/s. **Conclusión:** en el agua la luz va al 75 % de su velocidad en el vacío (1 ÷ 1,3330 = 0,75).",
      "",
      "**Ley de Snell** (la que explica la pajilla quebrada): cuando la luz pasa de un medio 1 a un medio 2,",
      "",
      "```formula",
      "n_{1} sen θ_{1} = n_{2} sen θ_{2}",
      "```",
      "",
      "θ₁ y θ₂ son los ángulos que el rayo hace con la **normal** (la perpendicular a la superficie). Si n₂ > n₁, el rayo se acerca a la normal.",
      "",
      "**Dos cosas que mueven el valor de n** (por eso hay que controlarlas):",
      "",
      "- **La longitud de onda (λ):** por eso se reporta a la línea D del sodio (589,3 nm) → n_D.",
      "- **La temperatura:** al calentar, el líquido se expande, se vuelve menos denso y n **baja** (del orden de 10⁻⁴ por °C). Por eso se reporta a 20 °C → n_D²⁰. Si tu equipo no está a 20 °C, tu curva y tus muestras deben medirse **a la misma temperatura** (anótala).",
      "",
      "#### Cómo funciona el refractómetro de Abbe",
      "",
      "1. Una gota de muestra se extiende en una película delgada **entre dos prismas** (el de iluminación y el de medida).",
      "2. La luz atraviesa la muestra y llega al prisma de medida con muchos ángulos. Hay un **ángulo crítico**: los rayos que llegan con un ángulo mayor sufren **reflexión total** (no pasan). Eso divide el campo visual en una zona **clara** y una **oscura**.",
      "3. La posición de esa línea de separación depende solo de n de la muestra. Con el tornillo de ajuste llevas la línea **al cruce de la retícula** y lees n (y °Brix) en la escala.",
      "4. **Compensador de Amici:** la luz blanca se descompone en colores y la línea sale con un borde de color. Los prismas de Amici lo corrigen para que la lectura equivalga a luz monocromática D. Sin ajustarlo, la línea se ve difusa y coloreada y la lectura es imprecisa.",
      "5. **Termostato:** el agua circulante mantiene los prismas a 20 °C.",
      "6. **Verificación previa:** con agua destilada el equipo debe leer **n = 1,3330** (y 0 °Brix) a 20 °C. Si lee otro valor, ajusta según indique el docente o **anota la corrección** y aplícala a todas las lecturas.",
      "",
      "**Cuidado con los prismas:** se rayan con facilidad. Límpialos solo con papel de lente humedecido (agua destilada o etanol) y sin presionar; nunca toques el prisma con la punta del gotero.",
      "",
      "#### ¿Qué son los °Brix y los °Baumé?",
      "",
      "- **°Brix:** **1 °Brix = 1 g de sacarosa en 100 g de solución** (1 % p/p de sacarosa). El aparato convierte el n medido a °Brix usando la tabla de **la sacarosa**. **Ojo:** con etanol, el valor °Brix **no es el % de etanol**; es «la concentración de sacarosa que daría el mismo n». Por eso no se usa directo: se hace una **curva de calibración propia** con tus mezclas.",
      "- **°Baumé (°Bé):** escala de **densidad** (d, relativa al agua). Líquidos más densos que el agua: °Bé = 145 − 145/d. Líquidos más livianos que el agua (como las mezclas con etanol, d < 1): °Bé = 140/d − 130. El refractómetro suele darlo ya convertido; la guía te pide graficarlo contra n y contra la concentración.",
      "",
      "#### Etanol + agua: qué esperar",
      "",
      "- n **sube** al aumentar el % de etanol (el etanol puro tiene n ≈ 1,361 frente a 1,333 del agua). En el rango bajo (0–20 % p/p) la curva es **casi una recta**; a concentraciones altas se aplana y deja de ser lineal, porque la mezcla etanol-agua **no es ideal**.",
      "- **Contracción de volumen:** al mezclar etanol y agua el volumen total es **menor** que la suma de los volúmenes. Por eso, para llegar a un volumen final **no sumes volúmenes**: pasa el etanol al balón y **completa con agua hasta el aforo**.",
      "",
      "#### Paso 1 — Preparar los 5 niveles con C₁V₁ = C₂V₂ (factores a la vista)",
      "",
      "La guía te da una **solución madre al 20 % p/p** y te pide 5 niveles (por duplicado). Todos los niveles se hacen **diluyendo la madre**.",
      "",
      "**Interpretación.** C₁V₁ = C₂V₂ dice: «la cantidad de etanol que saco de la madre (C₁·V₁) es **la misma** que quedará en el balón final (C₂·V₂)». Diluir solo agrega agua; no cambia la cantidad de etanol. Se despeja el volumen de madre que debes tomar:",
      "",
      "```formula",
      "V_{1} = #{C_{2} × V_{2}|C_{1}}",
      "```",
      "",
      "C₁ = 20 % (madre) · C₂ = concentración del nivel · V₂ = volumen del balón (aquí 10,0 mL) · V₁ = volumen de madre a tomar.",
      "",
      "**Ejemplo con el nivel 8 % (balón de 10,0 mL).**",
      "",
      "- **Factor de conversión:** V₁ = (8 % × 10,0 mL) ÷ (20 %). El «%» está arriba y abajo → **se cancela**, y queda **mL** (justo la unidad que buscas).",
      "- **Cálculo:** 8 × 10,0 = 80,0 → 80,0 ÷ 20 = **4,0 mL**.",
      "- **Conclusión:** toma 4,0 mL de madre al 20 % y completa con agua destilada hasta el aforo de 10,0 mL; queda al 8 % p/p.",
      "",
      "Tabla ilustrativa (tus niveles los defines con el docente; el nivel de 20 % es la madre sin diluir):",
      "",
      "| Nivel | C₂ (% p/p) | V₂ (mL) | V₁ = C₂·V₂ ÷ 20 % (mL de madre) | Agua hasta aforo |",
      "| --- | --- | --- | --- | --- |",
      "| 1 | 4 | 10,0 | 4 × 10,0 ÷ 20 = **2,0** | completar a 10,0 mL |",
      "| 2 | 8 | 10,0 | 8 × 10,0 ÷ 20 = **4,0** | completar a 10,0 mL |",
      "| 3 | 12 | 10,0 | 12 × 10,0 ÷ 20 = **6,0** | completar a 10,0 mL |",
      "| 4 | 16 | 10,0 | 16 × 10,0 ÷ 20 = **8,0** | completar a 10,0 mL |",
      "| 5 | 20 | 10,0 | la madre misma (sin diluir) | — |",
      "",
      "**Aviso de rigor:** tomar volúmenes de una solución «% p/p» y diluir en volumen es una **aproximación** (la densidad de la mezcla cambia con la composición). Si el docente pide rigor máximo, prepara los niveles **por masa** (pesando madre y agua en la balanza).",
      "",
      "#### Paso 2 — Medir por duplicado y calcular el %RSD de cada nivel",
      "",
      "Cada nivel se prepara **dos veces** (dos réplicas independientes) y cada una se lee en el refractómetro. Anota n, °Brix y °Bé de cada lectura, y la temperatura.",
      "",
      "**Interpretación del %RSD.** Mide qué tan parecidas salen las réplicas **en relación con su tamaño**: %RSD = (s ÷ promedio) × 100. Un %RSD pequeño significa que tu técnica es repetible.",
      "",
      "**Ejemplo (nivel 8 %, réplicas n = 1,3412 y 1,3414).**",
      "",
      "- Promedio = (1,3412 + 1,3414) ÷ 2 = **1,3413**.",
      "- Con solo 2 datos, s = |diferencia| ÷ √2 = 0,0002 ÷ 1,4142 = **0,000141**.",
      "- **Factor de conversión:** s ÷ promedio = 0,000141 ÷ 1,3413 = 1,05 × 10⁻⁴ (adimensional) → × 100 para pasarlo a porcentaje = **%RSD = 0,0105 %**.",
      "- **Conclusión:** réplicas casi idénticas; la lectura del refractómetro es muy repetible (por eso n se informa con 4 decimales).",
      "",
      "#### Paso 3 — Regresión lineal por mínimos cuadrados, paso a paso",
      "",
      "Se grafica **x = concentración (% p/p)** contra **y = n** (con los 10 puntos: 5 niveles × 2 réplicas) y se ajusta la recta y = m·x + b.",
      "",
      "```formula",
      "m = #{Σ(x_{i} − x̄)(y_{i} − ȳ)|Σ(x_{i} − x̄)^{2}}",
      "b = ȳ − m·x̄",
      "R^{2} = 1 − #{Σ(y_{i} − ŷ_{i})^{2}|Σ(y_{i} − ȳ)^{2}}",
      "```",
      "",
      "- **m (pendiente):** cuánto sube n por cada 1 % p/p de etanol (unidades: n por % p/p). Es la **sensibilidad** del método: más pendiente = el refractómetro distingue mejor concentraciones parecidas.",
      "- **b (intercepto):** n cuando la concentración es 0. Debe quedar muy cerca de **1,3330** (el agua pura). Si no, hay un error sistemático (equipo sin verificar o temperatura distinta).",
      "- **R² (coeficiente de determinación):** qué fracción de la variación de n explica la concentración. Cercano a 1 = recta excelente (el criterio habitual es R² ≥ 0,99; confirma el de tu profesor).",
      "- **ANOVA de la regresión:** compara la variación *explicada* por la recta (MS_reg) con la *no explicada* (MS_res): F = MS_reg ÷ MS_res. Una F grande (con p < 0,05) dice que la pendiente **no es cero**: sí hay relación real entre n y concentración.",
      "- **Incertidumbre de la pendiente y del intercepto:** s_m = s_{y/x} ÷ √Σ(xᵢ − x̄)² y s_b = s_{y/x}·√(1/N + x̄²/Σ(xᵢ − x̄)²), con s_{y/x} = √[Σ(yᵢ − ŷᵢ)² ÷ (N − 2)]. Con ellas se arman los intervalos de confianza (m ± t·s_m).",
      "- **Residuos** (yᵢ − ŷᵢ, lo que la recta no explica): grafícalos contra x. Si se reparten **al azar** alrededor de cero con altura pareja → modelo **homocedástico** (varianza constante). Si forman un **embudo** (más dispersión a mayor concentración) → **heterocedástico**. Si dibujan una **curva** (U o ∩), la relación no es lineal.",
      "",
      "#### Paso 4 — Hallar la concentración de las muestras problema (interpolación inversa)",
      "",
      "**Interpretación.** La recta dice n = m·x + b. Tú midiste n de la muestra y quieres x: se despeja.",
      "",
      "```formula",
      "x_{MP} = #{n_{MP} − b|m}",
      "```",
      "",
      "**Ejemplo ilustrativo** (m = 0,0010 por % p/p; b = 1,3330; n de MP1 = 1,3410):",
      "",
      "- **Factor de conversión:** (n_MP − b) ÷ m = (1,3410 − 1,3330) ÷ (0,0010 por % p/p). El numerador es adimensional (n no tiene unidades); la pendiente trae «por % p/p» → al dividir queda **% p/p**.",
      "- **Cálculo:** 0,0080 ÷ 0,0010 = **8,0 % p/p**.",
      "- **Conclusión:** la muestra problema 1 contiene ≈ 8,0 % p/p de etanol. Verifica que caiga **dentro** del rango de la curva (4–20 %): fuera de él estarías extrapolando y el resultado no es confiable.",
      "",
      "#### Las 5 gráficas que pide la guía y qué te dice cada una",
      "",
      "| Gráfica | Para qué sirve |",
      "| --- | --- |",
      "| Concentración vs. índice de refracción | **La curva principal**: de ella sale la concentración de las muestras problema. |",
      "| Concentración vs. °Brix | Muestra que °Brix también crece con el etanol, pero **no vale 1:1** (°Brix ≠ % etanol). |",
      "| °Brix vs. índice de refracción | Convierte n a °Brix: debería parecerse a la **tabla de la sacarosa**; si no, el equipo está descalibrado. |",
      "| °Baumé vs. índice de refracción | Relaciona la escala de densidad con n. |",
      "| Concentración vs. °Baumé | Alternativa para estimar la concentración desde °Bé. |",
      "",
      "#### Resultado esperado",
      "",
      "- n_D²⁰ del agua = 1,3330 (y 0 °Brix); n **creciente** con el % de etanol.",
      "- Recta con R² cercano a 1 en el rango 4–20 % p/p y residuos sin patrón.",
      "- MP1 y MP2 dentro del rango de la curva, con %RSD bajo entre réplicas.",
      "- En la discusión: comenta la importancia de la **temperatura**, la **limpieza de prismas**, la **contracción de volumen**, y que °Brix (referido a sacarosa) no es una concentración real de etanol.",
    ].join("\n"),
    keyPoints: [
      "**Objetivo operativo:** curva de calibración de **5 niveles × 2 réplicas** (n vs. % p/p) con solución madre al **20 % p/p** y 2 muestras problema (MP1, MP2).",
      "**Verifica el equipo con agua destilada:** debe leer **n = 1,3330** y **0 °Brix** a 20 °C; si no, anota la corrección.",
      "**Temperatura constante (20 °C)** y la **misma** para curva y muestras: n baja al calentar (≈ 10⁻⁴ por °C).",
      "**Diluye con C₁V₁ = C₂V₂** y completa con agua **hasta el aforo** (no sumes volúmenes: el etanol y el agua se contraen al mezclarse).",
      "**Prismas:** límpialos con papel de lente humedecido, sin presionar ni rayar; limpia **entre muestras** para no arrastrar la anterior.",
      "**°Brix ≠ % de etanol:** es «equivalente en sacarosa». La concentración real sale de tu curva, no de la escala °Brix.",
      "**Estadística obligatoria:** pendiente, intercepto, R², ANOVA, incertidumbre de m y b, análisis de residuos (homo/heterocedástico) y %RSD por nivel.",
      "**Chequeo de hidratación/pureza:** el etanol se declara con su pureza (p. ej. 96 % v/v); usa el dato del frasco al preparar la madre y anótalo en el informe.",
    ],
    procedure: [
      "#### Actividad A — Preparar y verificar el equipo",
      "1. Encender el refractómetro de Abbe y el baño termostático; esperar a que los prismas lleguen a **20 °C**.",
      "2. Abrir los prismas, limpiarlos con papel de lente humedecido en agua destilada y secar sin presionar.",
      "3. Colocar 1–2 gotas de **agua destilada**, cerrar los prismas, ajustar el compensador de Amici hasta que la línea quede nítida y sin color, y llevarla al cruce de la retícula.",
      "4. Leer n (esperado 1,3330) y °Brix (esperado 0). Registrar y anotar la corrección si la hay.",
      "",
      "#### Actividad B — Preparar la curva (5 niveles × 2 réplicas)",
      "1. Calcular con C₁V₁ = C₂V₂ el volumen de madre (20 % p/p) para cada nivel (ver tabla del desarrollo).",
      "2. En balones aforados, medir el volumen de madre calculado y **completar con agua hasta el aforo**; homogenizar.",
      "3. Preparar cada nivel **dos veces** (réplica 1 y réplica 2, independientes).",
      "4. Medir de menor a mayor concentración, limpiando los prismas entre muestras.",
      "",
      "#### Actividad C — Muestras problema",
      "1. Medir MP1 y MP2 (por duplicado) en las mismas condiciones.",
      "2. Registrar n, °Brix y °Bé de cada lectura y la temperatura.",
      "",
      "#### Actividad D — Tratamiento de datos",
      "1. Graficar las 5 relaciones pedidas (ver el desarrollo) y aplicar regresión lineal por mínimos cuadrados.",
      "2. Calcular m, b, R², ANOVA, incertidumbre de m y b, residuos y %RSD de cada nivel.",
      "3. Interpolar MP1 y MP2 en la curva (x = (n − b) ÷ m) y reportar con su %RSD.",
      "4. Discutir: cercanía con valores tabulados, importancia de la técnica en farmacia, factores que afectan la medición y conclusiones.",
    ].join("\n"),
    equations: [
      {
        name: "Índice de refracción",
        expression: "n = #{c|v}",
        variables: "c = velocidad de la luz en el vacío (≈ 3,00 × 10^{8} m/s) · v = velocidad en el medio · n = adimensional (≥ 1)",
        description: "Cuántas veces más lenta viaja la luz en el medio que en el vacío.",
      },
      {
        name: "Ley de Snell",
        expression: "n_{1} sen θ_{1} = n_{2} sen θ_{2}",
        variables: "θ_{1}, θ_{2} = ángulos de incidencia y refracción medidos desde la normal",
      },
      {
        name: "Dilución (volumen de madre)",
        expression: "C_{1}V_{1} = C_{2}V_{2}  →  V_{1} = #{C_{2} × V_{2}|C_{1}}",
        variables: "C_{1} = % p/p de la madre (20 %) · V_{1} = mL de madre a tomar · C_{2} = % p/p del nivel · V_{2} = mL del balón",
        description: "El % se cancela arriba y abajo: el resultado queda en mL.",
      },
      {
        name: "Regresión lineal (curva de calibración)",
        expression: "n = m·C + b\nm = #{Σ(x_{i} − x̄)(y_{i} − ȳ)|Σ(x_{i} − x̄)^{2}}\nb = ȳ − m·x̄",
        variables: "x = % p/p · y = n · m = sensibilidad (n por % p/p) · b ≈ n del agua (1,3330)",
      },
      {
        name: "Interpolación de la muestra problema",
        expression: "C_{MP} = #{n_{MP} − b|m}",
        variables: "n_{MP} = índice de refracción medido de la muestra · resultado en % p/p",
      },
      {
        name: "% RSD",
        expression: "%RSD = #{s|x̄} × 100",
        variables: "s = desviación estándar de las réplicas · x̄ = promedio",
      },
      {
        name: "°Baumé (a partir de la densidad relativa d)",
        expression: "°Bé = 145 − #{145|d}   (líquidos más densos que el agua)\n°Bé = #{140|d} − 130   (líquidos más livianos que el agua)",
        variables: "d = densidad relativa al agua",
      },
    ],
    dataRequested: [
      "Temperatura del ensayo y n del agua destilada (verificación del equipo).",
      "Cálculos de los volúmenes de madre (C₁V₁ = C₂V₂) y datos de preparación de la madre al 20 % p/p, los 5 niveles y las 2 muestras problema.",
      "Tabla: solución (1–5, MP1, MP2) × réplica → **% p/p**, **n**, **°Brix**, **°Baumé**.",
      "Las 5 gráficas (C–n, C–°Brix, °Brix–n, °Bé–n, C–°Bé) con su recta de regresión.",
      "m, b, R², tabla ANOVA, incertidumbre de m y b, gráfico de residuos (¿homo o heterocedástico?) y %RSD de cada nivel.",
      "Concentración de MP1 y MP2 interpoladas, con %RSD, y discusión final.",
    ],
    studyTopics: [
      "Índice de refracción, ley de Snell, ángulo crítico y reflexión total.",
      "Refractómetro de Abbe: prismas, compensador de Amici y calibración con agua.",
      "Escalas °Brix y °Baumé: definición y límites de uso.",
      "Regresión lineal por mínimos cuadrados, ANOVA de la regresión, residuos, homocedasticidad.",
      "No idealidad de mezclas etanol-agua (contracción de volumen).",
    ],
    quizQuestions: [
      {
        question:
          "Necesitas 10,0 mL de una solución de etanol al **12 % p/p** a partir de la madre al **20 % p/p**. ¿Cuántos mL de madre tomas? Muestra el factor de conversión.",
        solution: [
          "**Interpretación.** La cantidad de etanol se conserva al diluir: C₁V₁ = C₂V₂. Se despeja V₁.",
          "",
          "**Factor de conversión:** V₁ = (C₂ × V₂) ÷ C₁ = (12 % × 10,0 mL) ÷ (20 %). El «%» aparece arriba y abajo → se cancela y queda **mL**.",
          "",
          "**Cálculo:** 12 × 10,0 = 120 → 120 ÷ 20 = **6,0 mL**.",
          "",
          "**Conclusión:** 6,0 mL de madre + agua destilada hasta el aforo de 10,0 mL (completa con agua, no sumes volúmenes).",
        ].join("\n"),
      },
      {
        question:
          "Tu agua destilada lee **n = 1,3326** a 20 °C y el valor tabulado es 1,3330. ¿Qué haces y por qué importa? Si MP1 lee 1,3410, ¿qué n corregido usas?",
        solution: [
          "**Interpretación.** El equipo tiene un error sistemático de −0,0004 (lee de menos). Si no se corrige, **todas** las lecturas quedan desplazadas igual.",
          "",
          "**Corrección:** 1,3330 − 1,3326 = **+0,0004**. Se suma a cada lectura.",
          "",
          "**Aplicado a MP1:** 1,3410 + 0,0004 = **1,3414**.",
          "",
          "**Conclusión:** anota la corrección, aplícala a curva y muestras por igual (o recalibra el equipo si el docente lo permite). Un desplazamiento constante cambia el **intercepto** de la recta, no su pendiente.",
        ].join("\n"),
      },
    ],
  },

  // ───────────────────────────── PRÁCTICA 2 ─────────────────────────────
  {
    number: 2,
    labModule: "Módulo II",
    title: "Polarimetría: rotación óptica y rotación específica (sacarosa + ácido ascórbico)",
    moduleSlug: "metodos-fisicos",
    fundamento:
      "Las sustancias **quirales** (ópticamente activas) giran el plano de la luz polarizada. El **polarímetro** mide ese ángulo (**α**, rotación observada); con la concentración y la longitud del tubo se calcula la **rotación específica [α]**, una constante propia de la sustancia (a 20 °C y línea D del sodio, 589,3 nm) que sirve para **identificarla y evaluar su pureza**. Se mide α **20 veces** (una por estudiante, resultados compartidos) para cada analito y se trata estadísticamente (promedio, %RSD, CV, prueba t de Student).",
    desarrollo: [
      "#### En una frase",
      "",
      "Vas a medir **cuántos grados gira la luz** al atravesar una solución de **sacarosa** y otra de **ácido ascórbico**, y con ese ángulo vas a calcular una constante de cada sustancia (la **rotación específica**) para compararla con el valor de los libros.",
      "",
      "> **Analogía — la rejilla y el peine.** Imagina que la luz normal es una lluvia de rayos que vibran en todas direcciones, y que el *polarizador* es una rejilla de una sola ranura: solo deja pasar los rayos que vibran en **un plano**. Una molécula quiral actúa como un «peine torcido» que **gira** ese plano un poco. El polarímetro mide cuánto lo giró; entre más sustancia (o más tubo), más gira.",
      "",
      "#### Conceptos que no puedes saltar",
      "",
      "- **Quiral:** molécula que **no se superpone con su imagen en el espejo** (como tus manos). Casi siempre tiene un carbono con 4 sustituyentes distintos.",
      "- **Dextrógira (+):** gira el plano **a la derecha** (horario). **Levógira (−):** a la izquierda. El signo se mide, **no se deduce de la estructura**.",
      "- **α (rotación observada):** el ángulo que lees en el equipo (grados, °). Depende de cuánta muestra hay en el camino.",
      "- **[α] (rotación específica):** α **normalizada** por concentración y longitud del tubo: la «huella digital» de la sustancia, independiente de cuánta muestra uses (a λ y T fijas).",
      "",
      "#### Cómo funciona el polarímetro",
      "",
      "1. **Fuente de luz** de sodio (línea D, 589,3 nm): luz casi monocromática.",
      "2. **Polarizador:** deja pasar luz que vibra en un solo plano.",
      "3. **Tubo con la muestra** (longitud **l**, en decímetros): aquí la sustancia gira el plano.",
      "4. **Analizador:** se gira hasta recuperar la posición de máxima o mínima luz; el ángulo girado es α.",
      "5. **Cero del equipo:** con el tubo lleno del **solvente solo** (agua), α debe ser 0,000°. Si no, se anota/corrige ese cero.",
      "",
      "**Buenas prácticas:** tubo **sin burbujas** (dispersan la luz y dan lecturas erráticas), temperatura de **20 °C**, solución **transparente** (filtrada), y leer el mismo número de veces con la misma técnica.",
      "",
      "#### La fórmula de la guía — y el ×100",
      "",
      "```formula",
      "[α]_{D}^{20°C} = #{α × 100|l × C}",
      "```",
      "",
      "- **α** = rotación observada (°) · **l** = longitud del tubo en **dm** (1 dm = 10 cm) · **C** = concentración en **g por 100 mL** de solución.",
      "- El **×100** aparece porque C está en g/100 mL. (Si C estuviera en g/mL, la fórmula sería [α] = α ÷ (l·c) sin el 100.)",
      "",
      "**Paso previo — pasar tus pesadas a g/100 mL (factor de conversión).** Pesas *m* gramos y aforas a *V* mL:",
      "",
      "```formula",
      "C (g/100 mL) = #{m (g)|V (mL)} × 100",
      "```",
      "",
      "**Ejemplo (sacarosa):** 2,500 g en un balón de 25,00 mL → C = (2,500 g ÷ 25,00 mL) × 100 = **10,00 g/100 mL**. **Interpretación del factor:** g ÷ mL da g/mL; multiplicar por 100 lo reexpresa «por cada 100 mL».",
      "",
      "#### Ejemplo completo — sacarosa (ilustrativo)",
      "",
      "Datos: C = 10,00 g/100 mL · l = 2 dm · valor tabulado [α] = +66,5°.",
      "",
      "**Paso 1 — ¿qué α debería leer?** Despejando de la fórmula: α_esperada = [α] × l × C ÷ 100.",
      "",
      "- **Factor de conversión:** 66,5 (°·mL·g⁻¹·dm⁻¹) × 2 (dm) × 10,00 (g/100 mL) ÷ 100 → los dm se cancelan con dm⁻¹, los g/100 mL con g⁻¹ y el ×100 convierte «100 mL» en «mL». Queda grados (°).",
      "- **Cálculo:** 66,5 × 2 × 10,00 ÷ 100 = **13,3°**.",
      "- **Conclusión:** con ese tubo y esa solución debes leer ≈ +13,3° (dextrógira).",
      "",
      "**Paso 2 — de α medida a [α] experimental.** Si el promedio de 20 lecturas fue α = 13,28°:",
      "",
      "- [α] = 13,28 × 100 ÷ (2 × 10,00) = 1328 ÷ 20,00 = **+66,4°**.",
      "- **Conclusión:** muy cerca del tabulado (+66,5°). Diferencia = 0,1° → **0,2 %** del valor.",
      "",
      "#### Tratamiento estadístico de las 20 mediciones",
      "",
      "Cada estudiante del curso mide una vez y se comparten los 20 datos. Para cada analito:",
      "",
      "| Estadístico | Fórmula | Qué te dice |",
      "| --- | --- | --- |",
      "| Promedio (x̄) | Σxᵢ ÷ N | El valor central de α. |",
      "| Desviación estándar (s) | √[Σ(xᵢ − x̄)² ÷ (N − 1)] | La dispersión de los 20 datos, en °. |",
      "| %RSD | (s ÷ x̄) × 100 | La dispersión **relativa**: permite comparar la repetibilidad de dos analitos. |",
      "| CV | s ÷ x̄ | Es **lo mismo** que el %RSD, pero como fracción (CV × 100 = %RSD). |",
      "| t de Student | (x̄ − μ) ÷ (s ÷ √N) | Si tu promedio difiere **significativamente** del valor esperado μ. |",
      "",
      "**Prueba t, paso a paso.** Hipótesis nula: «tu promedio es igual al esperado» (μ = α_esperada, calculada con el [α] tabulado). Se calcula t y se compara con el valor crítico: con N = 20 → **gl = N − 1 = 19** y α = 0,05 a dos colas, **t_crítico = 2,093**.",
      "",
      "**Ejemplo (ilustrativo):** x̄ = 13,28° · μ = 13,30° · s = 0,12° · N = 20.",
      "",
      "- **Error estándar** = s ÷ √N = 0,12 ÷ 4,472 = **0,0268°** (los grados quedan; N es adimensional).",
      "- **t** = (13,28 − 13,30) ÷ 0,0268 = **−0,75**.",
      "- |t| = 0,75 < 2,093 → **no se rechaza** la hipótesis nula.",
      "- **Conclusión:** no hay diferencia significativa entre tu medición y el valor teórico: la sustancia es consistente con la tabulada (identidad y pureza óptica compatibles).",
      "",
      "#### Particularidades de cada analito",
      "",
      "- **Sacarosa:** [α] ≈ **+66,5°** (agua, 20 °C). Es un disacárido **no reductor**: no muta (la α no deriva en el tiempo). **Ojo:** en medio ácido se **hidroliza** (inversión) a glucosa + fructosa y el signo de la rotación cambia; usa agua neutra y no la dejes mucho tiempo.",
      "- **Ácido L-ascórbico:** [α] ≈ **+21°** (agua; el valor exacto depende de la concentración y del disolvente de la tabla que cites, así que anótalos). Es **inestable en solución** (se oxida con aire, luz y calor): prepárala **fresca**, protégela de la luz y mide pronto. Su señal es unas 3 veces menor que la de la sacarosa a igual C y l: con C = 10 g/100 mL y l = 2 dm, α_esperada = 21 × 2 × 10 ÷ 100 = **4,2°**, frente a 13,3° de la sacarosa. Más señal pequeña = **mayor error relativo**.",
      "",
      "#### Resultado esperado",
      "",
      "- Cero del equipo ≈ 0,000° con agua.",
      "- α positivas (dextrógiras) para ambos analitos; [α] experimental cercana a la tabulada (≈ +66,5° sacarosa; ≈ +21° ascórbico).",
      "- %RSD bajo para la sacarosa; algo mayor para el ascórbico (señal menor e inestabilidad).",
      "- En la discusión: importancia de la técnica en farmacia (identidad y pureza óptica de fármacos quirales, control de azúcares), y factores que afectan la medición: temperatura, λ, concentración, burbujas, pureza del solvente, estabilidad de la muestra.",
    ].join("\n"),
    keyPoints: [
      "**Dos analitos:** sacarosa (≈ +66,5°) y ácido ascórbico (≈ +21°). Cada uno se mide **20 veces** (una por estudiante) y los resultados se comparten.",
      "**Fórmula de la guía:** [α] = α·100 ÷ (l·C) con **l en dm** y **C en g/100 mL**. Si pesas m (g) y aforas a V (mL): C = m ÷ V × 100.",
      "**Cero con solvente** (agua): sin burbujas y a 20 °C antes de medir la muestra.",
      "**Sacarosa:** usar agua neutra (el ácido la hidroliza → inversión). **Ascórbico:** prepararlo fresco, proteger de la luz, medir pronto.",
      "**Estadística:** promedio, s, **%RSD**, **CV** (= %RSD ÷ 100) y **prueba t de Student** contra el valor esperado (gl = N − 1 = 19; t_crítico ≈ 2,093 a 95 %).",
      "**Hidratación:** sacarosa y ácido ascórbico se pesan **anhidros**; si tu frasco fuera otra forma (sal o hidrato), usa el peso de la **especie que rota** y anótalo.",
      "Compara siempre con el valor **tabulado** y cita **disolvente, concentración y temperatura** de esa tabla (la [α] depende de ellos).",
    ],
    procedure: [
      "#### Actividad A — Preparar las soluciones",
      "1. Calcular la masa para la concentración definida con el docente (C en g/100 mL): m = C × V ÷ 100.",
      "2. Pesar con exactitud, disolver en agua destilada y **aforar** en balón; filtrar si hay turbidez.",
      "3. Preparar el ácido ascórbico **justo antes** de medir y protegerlo de la luz.",
      "",
      "#### Actividad B — Medir con el polarímetro",
      "1. Encender la lámpara de sodio y esperar a que se estabilice.",
      "2. Llenar el tubo con **agua** (sin burbujas), medir y registrar el **cero** del equipo.",
      "3. Llenar el tubo con la solución del analito 1, medir α y registrar (una medición por estudiante).",
      "4. Repetir con el analito 2. Compartir los 20 resultados de cada analito con el grupo.",
      "",
      "#### Actividad C — Cálculos",
      "1. Calcular promedio, s, %RSD y CV de las 20 mediciones de cada analito.",
      "2. Calcular [α] experimental con la fórmula de la guía y compararla con la tabulada.",
      "3. Aplicar la prueba t de Student (gl = 19) contra la α esperada.",
      "4. Discutir: cercanía con lo tabulado, importancia en el ámbito farmacéutico, factores que afectan la medición y conclusión.",
    ].join("\n"),
    equations: [
      {
        name: "Rotación específica",
        expression: "[α]_{D}^{20°C} = #{α × 100|l × C}",
        variables: "α = rotación observada (°) · l = longitud del tubo (dm) · C = concentración (g/100 mL) · medido a 20 °C con luz de sodio (589,3 nm)",
        description: "Constante característica de cada sustancia ópticamente activa.",
      },
      {
        name: "Concentración en g/100 mL",
        expression: "C = #{m (g)|V (mL)} × 100",
        variables: "m = masa pesada (g) · V = volumen del balón (mL)",
      },
      {
        name: "α esperada",
        expression: "α_{esp} = #{[α]_{tab} × l × C|100}",
        variables: "[α]_{tab} = valor tabulado · l (dm) · C (g/100 mL)",
        description: "Lo que deberías leer si la sustancia es la tabulada.",
      },
      {
        name: "Prueba t de Student (una muestra)",
        expression: "t = #{x̄ − μ|s / √N}",
        variables: "x̄ = promedio de las N mediciones · μ = α esperada · s = desviación estándar · gl = N − 1 (= 19)",
        description: "Si |t| < t_crítico (≈ 2,093 a 95 %, gl = 19), no hay diferencia significativa.",
      },
      {
        name: "%RSD y CV",
        expression: "%RSD = #{s|x̄} × 100        CV = #{s|x̄}",
        variables: "El CV es el %RSD expresado como fracción.",
      },
    ],
    dataRequested: [
      "Nombre y PM de los dos principios activos (sacarosa y ácido ascórbico) y datos de preparación (masa, volumen del balón, C en g/100 mL).",
      "Longitud del tubo (dm), temperatura y cero del equipo con agua.",
      "Tabla de las **20 mediciones** de α de cada analito (una por estudiante).",
      "Promedio, %RSD, CV, resultado de la prueba t de Student y [α] experimental de cada analito, junto al valor tabulado.",
      "Discusión: cercanía con lo tabulado, importancia de la técnica, factores que afectan la medición y conclusión.",
    ],
    studyTopics: [
      "Luz polarizada, actividad óptica, quiralidad y signos (+)/(−).",
      "Partes del polarímetro y por qué se usa la línea D del sodio.",
      "Rotación específica vs. rotación observada; unidades y condiciones de reporte.",
      "Hidrólisis (inversión) de la sacarosa y estabilidad del ácido ascórbico.",
      "Estadística: %RSD, CV, prueba t de Student de una muestra.",
    ],
    quizQuestions: [
      {
        question:
          "Pesaste **1,250 g** de sacarosa y aforaste a **25,00 mL**; el tubo mide **2 dm** y el promedio de α fue **6,64°**. Calcula C (g/100 mL) y [α], mostrando los factores de conversión.",
        solution: [
          "**Paso 1 — C en g/100 mL.** *Interpretación:* la fórmula pide la concentración por cada 100 mL.",
          "",
          "- **Factor de conversión:** C = (1,250 g ÷ 25,00 mL) × 100 = 0,0500 g/mL × 100 = **5,00 g/100 mL** (g ÷ mL da g/mL; el ×100 lo pasa a «por 100 mL»).",
          "",
          "**Paso 2 — [α].** *Interpretación:* normalizar α por la longitud del tubo y por la concentración.",
          "",
          "- [α] = α × 100 ÷ (l × C) = 6,64 × 100 ÷ (2 × 5,00) = 664 ÷ 10,0 = **+66,4°**.",
          "",
          "**Conclusión:** [α] = +66,4°, prácticamente el valor tabulado de la sacarosa (+66,5°): la muestra es consistente con sacarosa.",
        ].join("\n"),
      },
      {
        question:
          "¿Por qué el ácido ascórbico da un **%RSD mayor** que la sacarosa en esta práctica, aunque se mida igual de cuidadosamente?",
        solution: [
          "**Razón 1 — señal más pequeña.** A igual C y l, su [α] (≈ +21°) es ~3 veces menor que la de la sacarosa (≈ +66,5°); un mismo error absoluto de lectura pesa más en términos relativos.",
          "",
          "**Razón 2 — inestabilidad.** El ácido ascórbico se oxida en solución (aire, luz, calor), así que su α puede derivar durante las 20 mediciones.",
          "",
          "**Conclusión:** el %RSD mayor es esperable; se reduce preparando la solución fresca, protegiéndola de la luz y midiendo rápido.",
        ].join("\n"),
      },
    ],
  },
];
