import type { LabPracticeContent } from "./_schema";

/**
 * AIF — Laboratorio, Módulo II, subgrupo J5. Parte B: Prácticas 3 y 4
 * (cuantificación por espectrofotometría UV y Visible). Los números de los
 * ejemplos son ILUSTRATIVOS; los datos reales salen de tu medición.
 */
export const aifModulo2PracticasB: LabPracticeContent[] = [
  // ───────────────────────────── PRÁCTICA 3 ─────────────────────────────
  {
    number: 3,
    labModule: "Módulo II",
    title: "Cuantificación UV: ibuprofeno (extracción del activo, curva de calibración y verificación)",
    moduleSlug: "uv-visible",
    fundamento:
      "La **espectrofotometría UV** cuantifica un analito que absorbe radiación ultravioleta (200–400 nm) usando la **ley de Lambert-Beer** (A = ε·b·c): a una longitud de onda fija, la absorbancia es proporcional a la concentración. Se halla el **λmáx** del **ibuprofeno** (IBU), se construye una **curva de calibración de 5 niveles × 2 réplicas** en el rango óptimo de absorbancia (**0,17–0,85 UA**), se extrae el activo de las **tabletas** y se verifica la curva con **3 soluciones problema** (baja, media, alta) calculando % recuperación, error relativo y %RSD.",
    desarrollo: [
      "#### En una frase",
      "",
      "Vas a disolver el **ibuprofeno** de una tableta, medir cuánta luz UV absorbe y, con una curva hecha con concentraciones conocidas, **calcular cuántos mg de ibuprofeno hay por tableta** y compararlo con lo que dice el empaque.",
      "",
      "> **Analogía — el vaso de té.** Un té más cargado deja pasar menos luz. Si preparas 5 tés con cantidades conocidas de hojas y mides cuánta luz bloquea cada uno, puedes dibujar «luz bloqueada vs. cantidad de hojas». Después, con un té de concentración desconocida, ves cuánta luz bloquea y **lees en tu dibujo** cuántas hojas tiene. La curva de calibración es ese dibujo. El espectrofotómetro es el medidor de «luz bloqueada».",
      "",
      "#### Fichas de las moléculas y reactivos de esta práctica",
      "",
      "Estructuras tomadas de PubChem (NCBI); datos de PubChem/HSDB y literatura. Las constantes dependen de la fuente, la temperatura y el disolvente: úsalas como referencia, no como verdad absoluta.",
      "",
      "| Estructura | Ficha |",
      "| --- | --- |",
      "| ![Estructura del ibuprofeno](/molecules/ibuprofeno.png) | **Ibuprofeno (IBU)** · C₁₃H₁₈O₂ · **PM 206,28 g/mol** · CAS 15687-27-1 · IUPAC: ácido 2-[4-(2-metilpropil)fenil]propanoico <br> **Qué es:** AINE del grupo de los ácidos arilpropiónicos; un anillo bencénico 1,4-disustituido (cromóforo) y un grupo –COOH. Tiene **un carbono quiral**; el fármaco suele ser racémico. <br> **Datos clave:** pKa ≈ **4,4–5,3** (≈ 4,9 es lo más citado); punto de fusión 75–77 °C; solubilidad en agua **muy baja (≈ 21 mg/L a 25 °C)**, muy soluble en etanol; se disuelve bien en medio **básico** como carboxilato. <br> **En esta práctica:** es el activo que se cuantifica por UV; explica por qué se prueba la solubilidad en agua / HCl 0,1 N / NaOH 0,1 N. |",
      "| ![Estructura del hidróxido de sodio](/molecules/naoh.png) | **Hidróxido de sodio (NaOH)** · **PM 40,00 g/mol** · CAS 1310-73-2 <br> **Qué es:** base fuerte; las lentejas absorben agua y CO₂ del aire (la pureza real baja de 100 %). <br> **En esta práctica:** se prepara 250 mL 0,1 N (1,000 g puro ÷ pureza) como **disolvente** del ibuprofeno. |",
      "",
      "",
      "#### Absorbancia, transmitancia y la ley de Lambert-Beer",
      "",
      "- **Transmitancia (T):** fracción de la luz que **sale** de la celda (I ÷ I₀). **Absorbancia (A):** A = −log T. Es adimensional (se escribe «UA»).",
      "- **Lambert-Beer:** **A = ε · b · c**. ε (absortividad molar, L·mol⁻¹·cm⁻¹) es propia de cada sustancia a cada λ; **b** = paso óptico de la celda (1 cm); **c** = concentración. A mayor c, mayor A: **relación lineal**.",
      "- **Por qué el rango 0,17–0,85 UA:** convertir con T = 10^(−A): A = 0,17 → T = 0,676 (67,6 % de la luz pasa); A = 0,85 → T = 0,141 (14,1 %). Es la zona donde el error relativo del instrumento es mínimo: con muy poca absorbancia la señal se confunde con el ruido; con demasiada (T < 10 %) llega muy poca luz al detector y se pierde la linealidad.",
      "",
      "#### Por qué el ibuprofeno absorbe UV",
      "",
      "El ibuprofeno (C₁₃H₁₈O₂, **PM 206,28 g/mol**) tiene un **anillo bencénico** 1,4-disustituido (el **cromóforo**: la parte de la molécula que absorbe). Los electrones π del anillo saltan de nivel al absorber UV (transiciones π→π*): una banda **intensa cerca de 220 nm** y bandas **débiles hacia 264–273 nm**. *(Valores de literatura aproximados; tu barrido de 200 a 400 nm manda.)* Con la solución de trabajo de **10 µg/mL** de la guía, la banda intensa es la que cae en el rango 0,17–0,85 UA.",
      "",
      "**Por qué el ibuprofeno se solubiliza en NaOH.** Es un **ácido carboxílico débil** (pKa ≈ 4,4–5,2): en agua o HCl está **protonado (neutro)** y casi no se disuelve; en NaOH 0,1 N pasa a **carboxilato (ibuprofenato de sodio)**, que sí es soluble. Por eso la prueba de solubilidad de la guía (agua / HCl 0,1 N / NaOH 0,1 N) lo deja en evidencia: lo esperado es **poco soluble en agua, insoluble en HCl, soluble en NaOH** (confírmalo con tus observaciones). Ojo: el disolvente también absorbe cerca del corte UV; **ajusta el blanco con el mismo disolvente** y, si el blanco da absorbancia alta hacia 220 nm, trabaja la banda de 264–273 nm con concentraciones mayores.",
      "",
      "#### Preparar 250 mL de NaOH 0,1 N (cronograma, semana 1–2)",
      "",
      "**Interpretación.** Necesitas gramos de NaOH sólido para que, en 250 mL, haya 0,1 eq por litro.",
      "",
      "- **Paso 1 — equivalentes necesarios:** 0,1 eq/L × 0,250 L = **0,025 eq** (el «L» se cancela).",
      "- **Paso 2 — pasar eq a gramos:** el NaOH tiene PM 40,00 g/mol y θ = 1 (un OH⁻ por unidad), así que 1 eq = 40,00 g. **Factor de conversión:** 0,025 eq × (40,00 g ÷ 1 eq) = **1,000 g** (el «eq» se cancela).",
      "- **Paso 3 — pureza:** las lentejas comerciales tienen ≈ 97–99 % de pureza y absorben agua del aire; para 97 %: 1,000 g ÷ 0,97 = **1,03 g**.",
      "- **Conclusión:** pesa ≈ 1,03 g de NaOH, disuélvelos en agua destilada y afora a 250 mL. Como aquí el NaOH es **medio/disolvente** (no valorante), la guía no pide estandarizarlo; si el docente lo pide, se estandariza contra KHP (ver Módulo I, Práctica 3).",
      "",
      "#### Paso 1 — Barrido espectral para hallar el λmáx",
      "",
      "1. Escoger el disolvente (el que mejor disuelve el IBU; lo esperado: NaOH 0,1 N).",
      "2. Preparar la **solución madre**, luego la **solución de trabajo de 10 µg/mL** (guía) y medirla de **200 a 400 nm** contra un **blanco** del mismo disolvente, en **celda de cuarzo** de 1 cm (el vidrio común y el plástico absorben por debajo de ≈ 340 nm y taparían el UV).",
      "3. El **λmáx** es la longitud de onda del pico más alto; registra su absorbancia y verifica que esté entre **0,17 y 0,85 UA**. Compara con el valor teórico (tabla del informe: teórico vs. práctico).",
      "",
      "#### Paso 2 — Diseñar la curva de calibración con C₁V₁ = C₂V₂",
      "",
      "Debes elegir: el λmáx de trabajo, el rango de concentración (el que dé 0,17–0,85 UA), la concentración de la **solución madre** y los 5 niveles (cada uno por duplicado).",
      "",
      "**Interpretación.** C₁V₁ = C₂V₂: la cantidad de analito tomada de la madre (C₁·V₁) es la que queda en el balón (C₂·V₂). Se despeja V₁ = C₂·V₂ ÷ C₁.",
      "",
      "**Ejemplo ilustrativo:** madre de **100 µg/mL**, balones de **25,0 mL**, niveles de 4, 6, 8, 10 y 12 µg/mL.",
      "",
      "- **Factor de conversión (nivel 6 µg/mL):** V₁ = (6 µg/mL × 25,0 mL) ÷ (100 µg/mL). El «µg/mL» está arriba y abajo → se cancela y queda **mL**.",
      "- **Cálculo:** 6 × 25,0 = 150 → 150 ÷ 100 = **1,5 mL**.",
      "",
      "| Nivel | C₂ (µg/mL) | V₂ (mL) | V₁ = C₂·V₂ ÷ 100 (mL de madre) |",
      "| --- | --- | --- | --- |",
      "| 1 | 4 | 25,0 | 4 × 25,0 ÷ 100 = **1,0** |",
      "| 2 | 6 | 25,0 | 6 × 25,0 ÷ 100 = **1,5** |",
      "| 3 | 8 | 25,0 | 8 × 25,0 ÷ 100 = **2,0** |",
      "| 4 | 10 | 25,0 | 10 × 25,0 ÷ 100 = **2,5** |",
      "| 5 | 12 | 25,0 | 12 × 25,0 ÷ 100 = **3,0** |",
      "",
      "**Conclusión:** cada balón se completa a 25,0 mL con el disolvente elegido (el mismo del blanco). Si con tus datos reales alguna absorbancia sale fuera de 0,17–0,85 UA, **cambia el rango** (más diluido o más concentrado) y repite.",
      "",
      "#### Paso 3 — Regresión lineal y estadística de la curva",
      "",
      "Se grafica **absorbancia promedio (y) vs. concentración (x, µg/mL)** y se ajusta **A = m·c + b**:",
      "",
      "- **m (pendiente, UA por µg/mL):** sensibilidad del método. Equivale a ε·b expresada por µg/mL.",
      "- **b (intercepto):** absorbancia con c = 0; debería ser ≈ 0 (si es grande, el blanco no está bien ajustado o hay contaminación).",
      "- **R²:** qué tan recta es la relación (criterio habitual ≥ 0,99; confirma el de tu docente).",
      "- **ANOVA de la regresión**, **incertidumbre de m y b**, **residuos** (¿homo o heterocedástico? al azar = homo; embudo = hetero) y **%RSD de cada nivel**: mismo procedimiento descrito en Módulo II · Práctica 1 (Paso 3).",
      "",
      "#### Paso 4 — Extraer el activo de las tabletas",
      "",
      "**Interpretación.** Una tableta no es ibuprofeno puro: trae excipientes (almidón, celulosa, etc.). Hay que sacar el activo a solución y dejar atrás lo insoluble.",
      "",
      "1. **Pesar las tabletas (hasta 10) una por una** y calcular el **peso promedio** (P̄). También anota la **información del producto** (mg de IBU declarados por tableta).",
      "2. Triturar a polvo fino y homogéneo.",
      "3. Pesar una porción de polvo **equivalente a una cantidad conocida de IBU**.",
      "4. Disolver/extraer en el disolvente elegido (agitar o sonicar ≈ 15 min), **filtrar** (los excipientes insolubles se quedan en el filtro) y aforar.",
      "5. Diluir hasta quedar en el rango de la curva.",
      "",
      "**Ejemplo ilustrativo — cuánto polvo pesar.** Tableta declarada de **400 mg** de IBU; peso promedio de la tableta **620 mg**. Quieres una porción que contenga 100 mg de IBU.",
      "",
      "- **Interpretación:** cada 620 mg de tableta contienen 400 mg de IBU; necesitas la masa de polvo que contenga 100 mg.",
      "- **Factor de conversión:** 100 mg IBU × (620 mg polvo ÷ 400 mg IBU) → los «mg IBU» se cancelan y quedan **mg de polvo**.",
      "- **Cálculo:** 100 × 620 ÷ 400 = **155 mg de polvo**.",
      "- **Conclusión:** pesa ≈ 155 mg de polvo (anota la masa real exacta que pesaste) y aforalos a 100 mL → ≈ 1,00 mg/mL de IBU = **1000 µg/mL** (1 mg = 1000 µg).",
      "",
      "#### Paso 5 — Verificar la curva con 3 soluciones problema (baja, media, alta)",
      "",
      "Prepara 3 soluciones dentro del rango lineal, **cada integrante** las prepara por el mismo procedimiento (así obtienes **duplicado independiente** de cada medida). Mide A al λmáx y calcula:",
      "",
      "```formula",
      "C_{exp} = #{A − b|m}",
      "%Rec = #{C_{exp}|C_{teo}} × 100",
      "ER (%) = #{C_{exp} − C_{teo}|C_{teo}} × 100",
      "```",
      "",
      "- **C_exp:** concentración que dice tu curva (interpolación inversa).",
      "- **% Recuperación (exactitud):** qué porcentaje de lo que *debía* haber recuperaste. 100 % es perfecto; el criterio habitual para un ensayo es ≈ 98–102 % (confirma el de tu docente).",
      "- **Error relativo (ER):** cuánto te desvías, con signo. + = sobreestimas; − = subestimas.",
      "- **%RSD:** repetibilidad entre las réplicas.",
      "",
      "**Ejemplo ilustrativo** (m = 0,0432 UA por µg/mL; b = 0,003; solución teórica 10,0 µg/mL; A medida = 0,437):",
      "",
      "- **C_exp** = (0,437 − 0,003) ÷ 0,0432 = 0,434 ÷ 0,0432 = **10,05 µg/mL** (UA ÷ (UA por µg/mL) = µg/mL: la UA se cancela).",
      "- **% Rec** = 10,05 ÷ 10,0 × 100 = **100,5 %**.",
      "- **ER** = (10,05 − 10,0) ÷ 10,0 × 100 = **+0,5 %**.",
      "- **Conclusión:** la curva recupera el analito con muy buena exactitud.",
      "",
      "#### Paso 6 — De la absorbancia al mg de IBU por tableta (cierre del problema)",
      "",
      "**Ejemplo ilustrativo** (continuando): la solución de la tableta se diluyó 1,00 mL → 100 mL (factor 100) y su C medida fue 10,05 µg/mL.",
      "",
      "- **Concentración en el balón de extracción:** 10,05 µg/mL × 100 = 1005 µg/mL (los mL de la dilución se cancelan: 100 mL ÷ 1,00 mL = 100).",
      "- **Masa de IBU extraída:** 1005 µg/mL × 100 mL = 100 500 µg → **÷ 1000 µg/mg = 100,5 mg** (el «µg» se cancela con µg/mg).",
      "- **Pasar de la porción de polvo a la tableta entera:** 100,5 mg × (620 mg tableta ÷ 155 mg polvo) = **402 mg por tableta** (los mg de polvo se cancelan).",
      "- **% del declarado:** 402 ÷ 400 × 100 = **100,5 %**.",
      "- **Conclusión:** la tableta cumple con lo declarado en el empaque.",
      "",
      "> **Chequeo de hidratación:** el ibuprofeno de la tableta es el **ácido libre, anhidro (PM 206,28)**. Si algún día trabajas con **ibuprofenato de sodio dihidrato** (PM ≈ 264,3), la masa que pesas no es la del ácido: debes multiplicar por 206,28 ÷ 264,3 = 0,780 para expresar el resultado «como ibuprofeno ácido».",
      "",
      "#### Resultado esperado",
      "",
      "- λmáx del IBU consistente con la literatura (banda intensa ≈ 220 nm y/o 264–273 nm) y absorbancia en 0,17–0,85 UA.",
      "- Curva con R² ≈ 1, intercepto cercano a 0 y residuos sin patrón.",
      "- % recuperación cercano a 100 % en las 3 soluciones y %RSD bajo.",
      "- Contenido por tableta cercano al declarado.",
    ].join("\n"),
    keyPoints: [
      "**Equipo:** barrido **200–400 nm** (modo espectral), **celda de cuarzo de 1 cm** (el vidrio común/plástico absorben UV bajo ≈ 340 nm), **blanco = el mismo disolvente**; sin burbujas y caras ópticas limpias.",
      "**Disolvente:** haz la prueba de solubilidad (agua, HCl 0,1 N, NaOH 0,1 N); el IBU, ácido débil, es lo más soluble como **carboxilato en NaOH**. Elige el de mejor solubilidad como base del experimento.",
      "**Rango de trabajo: 0,17–0,85 UA** (T de 67,6 % a 14,1 %); la solución de trabajo del barrido es de **10 µg/mL**.",
      "**Curva:** 5 niveles × 2 réplicas; volúmenes de madre con **C₁V₁ = C₂V₂**; absorbancia promedio vs. concentración.",
      "**Estadística:** pendiente, intercepto, R², ANOVA, incertidumbre de m y b, residuos (homo/heterocedástico) y %RSD de cada nivel.",
      "**Tabletas:** pesar hasta 10, calcular el peso promedio, triturar, extraer, **filtrar** y aforar; calcular la porción de polvo con el mg declarado.",
      "**Verificación:** 3 niveles (bajo, medio, alto), duplicado por integrante; reportar C_exp, **% recuperación**, **error relativo** y **%RSD**.",
      "**NaOH 0,1 N (250 mL):** 1,000 g de NaOH puro (÷ pureza ≈ 1,03 g); es disolvente, no valorante.",
      "**Chequeo de hidratación:** el activo de la tableta es el ácido libre anhidro (PM 206,28); la sal sódica dihidratada tiene otro PM.",
    ],
    procedure: [
      "#### Actividad A — Prueba de solubilidad y elección del disolvente",
      "1. En tres vidrios de reloj, colocar pequeñas porciones del IBU sólido y añadir agua destilada, HCl 0,1 N y NaOH 0,1 N respectivamente.",
      "2. Observar solubilidad y comportamiento; anotar en la tabla (Solubilidad / Observaciones) y escoger el disolvente de mejor solubilidad.",
      "",
      "#### Actividad B — Barrido y λmáx",
      "1. Verificar que el espectrofotómetro esté calibrado y operativo; encender y elegir modo de escaneo espectral **200–400 nm**.",
      "2. Ajustar el **blanco** con el disolvente escogido en una celda limpia y seca.",
      "3. Preparar la solución madre y la solución de trabajo de **10 µg/mL**; transferir una alícuota a la celda de 1 cm (sin burbujas, caras limpias con papel sin pelusa).",
      "4. Realizar el barrido completo, registrar absorbancia vs. λ, identificar **λmáx** y verificar que su absorbancia esté en 0,17–0,85 UA. Tomar los datos para graficar en Excel (o foto de la pantalla del equipo).",
      "",
      "#### Actividad C — Curva de calibración",
      "1. Fijar λ de trabajo, rango de concentración y concentración de la madre; calcular volúmenes con C₁V₁ = C₂V₂.",
      "2. Preparar 5 niveles por duplicado, medir la absorbancia a λmáx de cada uno (de menor a mayor concentración).",
      "3. Graficar A promedio vs. concentración; regresión, ANOVA, incertidumbres, residuos y %RSD.",
      "",
      "#### Actividad D — Extracción del activo y verificación",
      "1. Pesar hasta 10 tabletas individualmente; peso promedio e información del producto.",
      "2. Triturar, pesar la porción de polvo calculada, extraer, filtrar y aforar; diluir al rango de la curva.",
      "3. Preparar al menos **3 soluciones problema** (baja, media, alta) **por cada integrante**; medir A a λmáx.",
      "4. Calcular C_exp (interpolando en la recta), % recuperación, error relativo y %RSD; llevar el resultado a mg por tableta.",
    ].join("\n"),
    equations: [
      {
        name: "Absorbancia y transmitancia",
        expression: "A = −log T = log #{I_{0}|I}        T = 10^{−A}",
        variables: "I_{0} = intensidad incidente · I = intensidad transmitida · A adimensional (UA)",
      },
      {
        name: "Ley de Lambert-Beer",
        expression: "A = ε · b · c",
        variables: "ε = absortividad molar (L·mol^{−1}·cm^{−1}) · b = paso óptico (cm) · c = concentración (mol/L)",
        description: "En la curva de calibración, la pendiente m equivale a ε·b (por µg/mL).",
      },
      {
        name: "Dilución (volumen de madre)",
        expression: "C_{1}V_{1} = C_{2}V_{2}  →  V_{1} = #{C_{2} × V_{2}|C_{1}}",
        variables: "C en µg/mL · V en mL (la unidad de C se cancela y V_{1} queda en mL)",
      },
      {
        name: "Curva de calibración",
        expression: "A = m·c + b        C_{exp} = #{A − b|m}",
        variables: "m = pendiente (UA por µg/mL) · b = intercepto (UA) · C_{exp} en µg/mL",
      },
      {
        name: "Exactitud: % recuperación y error relativo",
        expression: "%Rec = #{C_{exp}|C_{teo}} × 100\nER (%) = #{C_{exp} − C_{teo}|C_{teo}} × 100",
        variables: "C_{teo} = concentración teórica de la solución problema",
      },
      {
        name: "Contenido por tableta",
        expression: "mg/tableta = m_{IBU,extraída} × #{P̄|m_{polvo}}",
        variables: "m_{IBU,extraída} (mg) = C·V·factor de dilución ÷ 1000 · P̄ = peso promedio de la tableta · m_{polvo} = masa de polvo pesada (mismas unidades)",
      },
      {
        name: "%RSD",
        expression: "%RSD = #{s|x̄} × 100",
        variables: "s = desviación estándar de las réplicas · x̄ = promedio",
      },
    ],
    dataRequested: [
      "Nombre y PM del principio activo (ibuprofeno, 206,28 g/mol).",
      "Tabla de solubilidad: agua destilada / HCl 0,1 N / NaOH 0,1 N (solubilidad y observaciones) y el disolvente seleccionado.",
      "λmáx teórico vs. práctico y su absorbancia (UA); espectro del barrido (Excel o foto).",
      "Construcción de la curva: λmáx seleccionado y su absorbancia, rango de concentración (0,17–0,85 UA), concentración de la madre y C₁…C₅ (µg/mL) con los cálculos de C₁V₁ = C₂V₂.",
      "Absorbancias de los 5 niveles × 2 réplicas; recta, m, b, R², ANOVA, incertidumbres, residuos y %RSD por nivel.",
      "Masas de las 10 tabletas, peso promedio e información reportada en el producto.",
      "Soluciones problema (baja, media, alta): A, C_exp, % recuperación, error relativo, %RSD; mg por tableta.",
    ],
    studyTopics: [
      "Ley de Lambert-Beer, desviaciones y rango óptimo de absorbancia.",
      "Cromóforos y transiciones electrónicas π→π* del anillo bencénico.",
      "Solubilidad del ibuprofeno y su pKa; ionización en NaOH.",
      "Instrumentación UV-Vis: lámparas, monocromador, celdas de cuarzo, blanco.",
      "Validación básica: linealidad, exactitud (% recuperación), precisión (%RSD).",
    ],
    quizQuestions: [
      {
        question:
          "Tu madre es de **100 µg/mL**. ¿Cuántos mL tomas para preparar **25,0 mL** de una solución de **8 µg/mL**? Muestra el factor de conversión.",
        solution: [
          "**Interpretación.** Al diluir se conserva la cantidad de analito: C₁V₁ = C₂V₂ → V₁ = C₂V₂ ÷ C₁.",
          "",
          "**Factor de conversión:** V₁ = (8 µg/mL × 25,0 mL) ÷ (100 µg/mL). El «µg/mL» está arriba y abajo → se cancela; queda **mL**.",
          "",
          "**Cálculo:** 8 × 25,0 = 200 → 200 ÷ 100 = **2,0 mL**.",
          "",
          "**Conclusión:** 2,0 mL de madre, completar a 25,0 mL con el mismo disolvente del blanco.",
        ].join("\n"),
      },
      {
        question:
          "Con la recta **A = 0,0432·c + 0,003**, una solución teórica de **10,0 µg/mL** dio **A = 0,425**. Calcula C_exp, % recuperación y error relativo, y concluye.",
        solution: [
          "**Paso 1 — C_exp.** *Interpretación:* se despeja c de la recta. C_exp = (A − b) ÷ m = (0,425 − 0,003) ÷ 0,0432 = 0,422 ÷ 0,0432 = **9,77 µg/mL** (UA ÷ (UA/(µg/mL)) = µg/mL).",
          "",
          "**Paso 2 — % recuperación.** 9,77 ÷ 10,0 × 100 = **97,7 %**.",
          "",
          "**Paso 3 — error relativo.** (9,77 − 10,0) ÷ 10,0 × 100 = **−2,3 %** (se subestima).",
          "",
          "**Conclusión:** 97,7 % queda **ligeramente fuera** de un criterio típico de 98–102 %. Revisa: pesada/aforo de la solución, burbujas en la celda, blanco, o si ese nivel está en el borde del rango de la curva.",
        ].join("\n"),
      },
    ],
  },

  // ───────────────────────────── PRÁCTICA 4 ─────────────────────────────
  {
    number: 4,
    labModule: "Módulo II",
    title: "Cuantificación Visible: verde de bromocresol, constante de equilibrio y punto isosbéstico",
    moduleSlug: "uv-visible",
    fundamento:
      "El **verde de bromocresol (BCG)** es un **indicador ácido-base** coloreado: su forma ácida (HIn, amarilla) y su forma básica (In⁻, azul) absorben luz **visible** a longitudes de onda distintas. Se hace el barrido **400–700 nm**, se cuantifica el colorante con una **curva de calibración (5 niveles × 2 réplicas)** y se aprovecha el equilibrio **HIn ⇌ H⁺ + In⁻** para determinar su **constante de equilibrio (Ka, pKa)** midiendo la absorbancia en 10 soluciones de pH distinto, por el **método gráfico** y el **método de las pendientes**, e identificando el **punto isosbéstico**.",
    desarrollo: [
      "#### En una frase",
      "",
      "Vas a medir el color de un indicador (el verde de bromocresol) a distintos pH y, viendo **cómo cambia su absorbancia**, vas a calcular **a qué pH está mitad ácido y mitad básico** (eso es el pKa) y en qué longitud de onda todos los espectros se cruzan (**punto isosbéstico**).",
      "",
      "> **Analogía — el semáforo.** El indicador es un semáforo de dos luces: en medio ácido está **amarillo**; en medio básico, **azul**; en el pH intermedio es **verde** (mezcla de los dos). El pKa es el pH donde ambas luces brillan igual: 50 % amarillo, 50 % azul.",
      "",
      "#### Fichas de las moléculas y reactivos de esta práctica",
      "",
      "Estructuras tomadas de PubChem (NCBI); datos de PubChem/HSDB y literatura. Las constantes dependen de la fuente, la temperatura y el disolvente: úsalas como referencia, no como verdad absoluta.",
      "",
      "| Estructura | Ficha |",
      "| --- | --- |",
      "| ![Estructura del verde de bromocresol](/molecules/verde-bromocresol.png) | **Verde de bromocresol (BCG)** · C₂₁H₁₄Br₄O₅S · **PM 698,01 g/mol** · CAS 76-60-8 · una sulfonftaleína tetrabromada <br> **Qué es:** indicador ácido-base. La estructura dibujada es la forma **cerrada (sultona)**, sin color; en solución se abre a **sulfonato** y se vuelve la especie coloreada. Se vende como ácido libre (PM 698) o como **sal sódica** (PM ≈ 720; más soluble en agua). <br> **Datos clave:** viraje **pH ≈ 3,8 (amarillo) → 5,4 (azul)**; pKa ≈ **4,8–4,9** según la fuente; λmáx forma ácida ≈ 420–445 nm y forma básica ≈ 615–620 nm; punto isosbéstico ≈ 515 nm; muy soluble en etanol, poco en agua; punto de fusión ≈ 218 °C (descompone). <br> **En esta práctica:** es el analito cuantificado en el visible y el sistema para medir el **pKa** y el punto isosbéstico. |",
      "| ![Estructura del ácido acético](/molecules/acido-acetico.png) | **Ácido acético (AcOH)** · C₂H₄O₂ · **PM 60,05 g/mol** · CAS 64-19-7 <br> **Datos clave:** pKa **4,76**; glacial: d ≈ 1,049 g/mL. <br> **En esta práctica:** con el NaOH forma el **buffer AcOH/AcO⁻** de las soluciones 5–8 (pH 4,5–5,1). |",
      "",
      "",
      "#### La química: un equilibrio ácido-base",
      "",
      "El BCG es un ácido débil, que representamos como HIn (In = «indicador»):",
      "",
      "```formula",
      "HIn ⇌ H⁺ + In⁻",
      "K_{a} = #{[H⁺][In⁻]|[HIn]}        pK_{a} = −log K_{a}",
      "```",
      "",
      "- **HIn (amarillo):** predomina a pH bajo (HCl 0,1 N, pH ≈ 1).",
      "- **In⁻ (azul):** predomina a pH alto (NaOH 0,1 N, pH ≈ 13).",
      "- **Zona de viraje:** pH ≈ 3,8–5,4; **pKa ≈ 4,8–4,9** (varía según la fuente; tu medición lo determina).",
      "- **λmáx de cada forma (literatura, aproximado):** HIn ≈ **420–445 nm** (absorbe azul-violeta → se ve amarillo); In⁻ ≈ **615–620 nm** (absorbe naranja-rojo → se ve azul). Con tu barrido (400–700 nm) confirmas ambos picos.",
      "",
      "**Hidratación / forma química del reactivo (¡importa!).** El BCG puede venir como **ácido libre** (PM ≈ 698,0 g/mol) o como **sal sódica** (PM ≈ 720,0 g/mol; la más soluble en agua). Pesar una u otra para «X µg/mL de colorante» da masas distintas: si te piden el colorante como ácido y pesaste la sal, multiplica por 698,0 ÷ 720,0 = 0,969. Anota qué forma tiene tu frasco.",
      "",
      "#### Solubilidad y soluciones A2 / B2",
      "",
      "La guía pide la prueba de solubilidad (**EtOH**, agua destilada, HCl 0,1 N, NaOH 0,1 N) y barridos de dos soluciones de referencia llamadas **A2 y B2**. La guía **no las define**; lo más probable es que sean las **formas ácida y básica** del colorante (confírmalo con el docente). Con ellas verificas dónde absorbe cada forma y qué absorbancia máxima da (debe estar en 0,17–0,85 UA para la curva de calibración).",
      "",
      "#### Curva de calibración del colorante",
      "",
      "Mismo procedimiento que en la Práctica 3 (UV): λ de trabajo en el **máximo de absorción** elegido, rango de concentración que dé 0,17–0,85 UA, madre, 5 niveles × 2 réplicas, C₁V₁ = C₂V₂, regresión, ANOVA, incertidumbres, residuos y %RSD. Como el BCG tiene una absortividad molar **muy grande** (del orden de 10⁴ L·mol⁻¹·cm⁻¹), basta con **pocos µg/mL**. En el visible puedes usar celdas de vidrio o plástico (la de cuarzo no es obligatoria).",
      "",
      "**Ejemplo de dilución (factores):** madre 50 µg/mL, nivel de 6 µg/mL en balón de 10,0 mL → V₁ = (6 µg/mL × 10,0 mL) ÷ (50 µg/mL) = **1,2 mL** (el «µg/mL» se cancela).",
      "",
      "#### El experimento de los 10 pHs — qué hay realmente en cada tubo",
      "",
      "A partir de las soluciones A2/B2 y sus barridos, prepara soluciones de 10 mL de colorante tales que el máximo de absorción dé ≈ **1 UA**. Con cada una se preparan las 10 soluciones de la guía (todas por duplicado en blanco):",
      "",
      "| Sol. | Colorante (mL) | KCl 0,1 N (mL) | AcOH 0,1 N (mL) | NaOH 0,1 N (mL) | Completar a 10 mL con | Qué hay realmente | pH teórico (estimado) |",
      "| --- | --- | --- | --- | --- | --- | --- | --- |",
      "| 1 | 1,0 | 1,0 | 0,2 | 1,0 | H₂O | NaOH en exceso | ≈ 11,9 |",
      "| 2 | 1,0 | 1,0 | 0,5 | 1,0 | H₂O | NaOH en exceso | ≈ 11,7 |",
      "| 3 | 1,0 | 1,0 | 0,8 | 1,0 | H₂O | NaOH en exceso | ≈ 11,3 |",
      "| 4 | 1,0 | 1,0 | 1,0 | 1,0 | H₂O | solo acetato (punto de equivalencia) | ≈ 8,4 |",
      "| 5 | 1,0 | 1,0 | 1,5 | 1,0 | H₂O | **buffer** AcOH/AcO⁻ (1 : 2) | ≈ 5,06 |",
      "| 6 | 1,0 | 1,0 | 2,0 | 1,0 | H₂O | **buffer** AcOH/AcO⁻ (1 : 1) | ≈ 4,76 |",
      "| 7 | 1,0 | 1,0 | 2,5 | 1,0 | H₂O | **buffer** AcOH/AcO⁻ (3 : 2) | ≈ 4,58 |",
      "| 8 | 1,0 | 1,0 | 3,0 | 1,0 | H₂O | **buffer** AcOH/AcO⁻ (2 : 1) | ≈ 4,46 |",
      "| 9 | 1,0 | 1,0 | 0 | 1,0 | NaOH 0,1 N | **forma básica pura (In⁻)** | ≈ 13 |",
      "| 10 | 1,0 | 1,0 | 0 | 0 | HCl 0,1 N | **forma ácida pura (HIn)** | ≈ 1 |",
      "",
      "**Cómo se obtienen esos pH (paso a paso, con unidades).** 0,1 N de NaOH o AcOH monovalentes = **0,1 mmol/mL**.",
      "",
      "- **NaOH añadido:** 1,0 mL × 0,1 mmol/mL = **0,100 mmol** (el «mL» se cancela).",
      "- **AcOH añadido:** x mL × 0,1 mmol/mL = **0,1·x mmol**. El NaOH y el AcOH reaccionan 1 : 1 (CH₃COOH + NaOH → CH₃COONa + H₂O).",
      "- **x < 1,0 mL (soluciones 1–3):** sobra NaOH. Para x = 0,2: sobran 0,100 − 0,020 = 0,080 mmol en 10 mL = 0,0080 M → pOH = 2,10 → **pH ≈ 11,9**.",
      "- **x = 1,0 mL (solución 4):** se neutraliza todo; queda acetato 0,100 mmol/10 mL = 0,010 M → pH = 7 + ½(4,76 + log 0,010) = 7 + ½(2,76) = **≈ 8,4**.",
      "- **x > 1,0 mL (soluciones 5–8):** queda AcOH sobrante y acetato formado = **buffer**. Henderson-Hasselbalch: pH = pKa(AcOH) + log([AcO⁻]/[AcOH]) con pKa(AcOH) = 4,76. Para x = 1,5: AcOH = 0,150 − 0,100 = 0,050 mmol; AcO⁻ = 0,100 mmol → pH = 4,76 + log(0,100/0,050) = 4,76 + 0,30 = **5,06**. Para x = 2,0: 0,100/0,100 → **4,76**. Para x = 2,5: 0,100/0,150 → 4,76 − 0,18 = **4,58**. Para x = 3,0: 0,100/0,200 → 4,76 − 0,30 = **4,46**.",
      "- **Conclusión:** solo las soluciones **5 a 8** caen cerca del pKa del BCG (≈ 4,8): son las que muestran la **transición** amarillo ↔ azul. Las 9 y 10 son las **referencias** de «100 % base» y «100 % ácido». Los valores son **estimados** (ignoran el colorante y la fuerza iónica; el KCl aporta una fuerza iónica constante): **mide el pH real** de cada tubo con el potenciómetro y usa ese valor.",
      "",
      "Las soluciones **blanco (1b–10b)** llevan exactamente lo mismo pero **sin colorante**: sirven para poner en cero el espectrofotómetro con la matriz idéntica de cada tubo.",
      "",
      "#### De absorbancias a pKa: método gráfico y método de las pendientes",
      "",
      "Se mide cada solución en **dos longitudes de onda**: λ₁ (donde absorbe la forma ácida, ≈ 420–445 nm) y λ₂ (donde absorbe la forma básica, ≈ 617 nm), y se anota su **pH real**.",
      "",
      "**Fundamento (Lambert-Beer aditiva).** A cualquier pH, el colorante total C_T se reparte entre HIn e In⁻. La absorbancia es la suma de ambas contribuciones:",
      "",
      "```formula",
      "A = ε_{HIn}·b·[HIn] + ε_{In}·b·[In⁻]        C_{T} = [HIn] + [In⁻]",
      "A_{HIn} = ε_{HIn}·b·C_{T}   (solución 10, todo ácido)",
      "A_{In} = ε_{In}·b·C_{T}   (solución 9, todo básico)",
      "```",
      "",
      "Restando y ordenando se obtiene la relación entre absorbancias y fracciones de cada especie:",
      "",
      "```formula",
      "#{[In⁻]|[HIn]} = #{A − A_{HIn}|A_{In} − A}",
      "pH = pK_{a} + log #{A − A_{HIn}|A_{In} − A}",
      "```",
      "",
      "- **Método gráfico:** se grafica **A vs. pH**. La curva tiene forma de **S (sigmoide)**; el **pKa es el pH donde A está a la mitad** entre A_HIn y A_In: A = (A_HIn + A_In) ÷ 2.",
      "- **Método de las pendientes (linealización):** se grafica **pH (eje y) vs. log[(A − A_HIn) ÷ (A_In − A)] (eje x)**. Debe salir una **recta de pendiente ≈ 1** cuyo **intercepto es el pKa** (cuando el log vale 0, pH = pKa). La guía llama a esto «método de las pendientes»; confirma con el docente que sea esta la forma que espera (otra variante es ajustar rectas a las zonas lineales de la sigmoide).",
      "",
      "**Ejemplo ilustrativo (λ₂ = 617 nm).** A_HIn (sol. 10) = 0,020 · A_In (sol. 9) = 1,000 · en un tubo con pH real = 4,72 se midió A = 0,520.",
      "",
      "- **Razón [In⁻]/[HIn]** = (0,520 − 0,020) ÷ (1,000 − 0,520) = 0,500 ÷ 0,480 = **1,04** (adimensional; la UA se cancela).",
      "- **log(1,04)** = 0,018.",
      "- **pKa** = pH − log(razón) = 4,72 − 0,018 = **4,70**.",
      "- **Conclusión:** es del orden del valor de literatura (≈ 4,7–4,9). Promedia los pKa de los tubos de la zona de transición (5–8) y compáralos con el del método gráfico.",
      "",
      "#### Punto isosbéstico",
      "",
      "Es la longitud de onda donde **todos los espectros** de las 10 soluciones **se cruzan** en un mismo punto. Ocurre cuando ε_HIn = ε_In a esa λ: la absorbancia ahí no depende de cuánto hay de cada forma (solo de C_T). Su existencia prueba que solo hay **dos especies en equilibrio** (HIn e In⁻) sin otras reacciones. Para el BCG está hacia **≈ 515–520 nm** (confírmalo con tus espectros superpuestos).",
      "",
      "#### Resultado esperado",
      "",
      "- Dos picos: ≈ 420–445 nm (ácida) y ≈ 617 nm (básica); la absorbancia en cada uno cambia con el pH en sentido contrario.",
      "- Curva A vs. pH tipo sigmoide (más nítida en el rango 4–5,5).",
      "- pKa ≈ 4,7–4,9 por ambos métodos, con diferencia pequeña entre ellos.",
      "- Punto isosbéstico en el cruce de los espectros (≈ 515–520 nm).",
      "- En la discusión: relaciona el pKa con la zona de viraje, la importancia del pH en compuestos ionizables de interés farmacéutico y las fuentes de error (pH real vs. teórico, fuerza iónica, temperatura).",
    ].join("\n"),
    keyPoints: [
      "**Barrido 400–700 nm**, blanco = disolvente; celdas de vidrio o plástico sirven en el visible. Verifica que la absorbancia máxima esté en **0,17–0,85 UA** (curva) y ≈ **1 UA** para el experimento de pH.",
      "**Solubilidad:** prueba EtOH, agua, HCl 0,1 N y NaOH 0,1 N; elige el medio de mejor solubilidad. **A2 y B2** no están definidas en la guía: probablemente formas ácida y básica (confirmar).",
      "**10 soluciones + 10 blancos (1b–10b):** colorante 1,0 mL + KCl 1,0 mL + AcOH x mL + NaOH 1,0 mL, aforo a 10 mL; la **9** es forma básica pura (aforo con NaOH 0,1 N) y la **10** forma ácida pura (aforo con HCl 0,1 N).",
      "**Solo las soluciones 5–8 son buffer AcOH/AcO⁻** (pH ≈ 5,06; 4,76; 4,58; 4,46): ahí ocurre la transición del BCG. **Mide el pH real** de cada tubo con el potenciómetro.",
      "**pKa por 2 métodos:** gráfico (A vs. pH, punto medio de la sigmoide) y de las pendientes (pH vs. log[(A − A_HIn)/(A_In − A)], intercepto = pKa).",
      "**Punto isosbéstico:** λ donde se cruzan los espectros; evidencia de dos especies en equilibrio.",
      "**Cada integrante prepara la muestra** por el mismo procedimiento para obtener duplicado de la medida.",
      "**Chequeo de hidratación/forma:** BCG ácido (PM ≈ 698) vs. sal sódica (PM ≈ 720): pesa y reporta la forma que realmente tienes.",
    ],
    procedure: [
      "#### Actividad A — Solubilidad y barrido",
      "1. Probar la solubilidad del BCG en EtOH, agua destilada, HCl 0,1 N y NaOH 0,1 N (tabla de solubilidad/observaciones).",
      "2. Preparar madre, soluciones de trabajo y soluciones A2 y B2; barrido **400–700 nm** (blanco con el disolvente), registrar λmáx y absorbancia de cada una.",
      "",
      "#### Actividad B — Curva de calibración",
      "1. Elegir el λ de trabajo (máximo de absorción), el rango de concentración (0,17–0,85 UA) y la concentración de la madre.",
      "2. Calcular con C₁V₁ = C₂V₂, preparar 5 niveles por duplicado y medir; graficar y tratar estadísticamente.",
      "3. Verificar la curva con ≥ 3 soluciones problema (baja, media, alta): C_exp, % recuperación, error relativo y %RSD.",
      "",
      "#### Actividad C — Constante de equilibrio y punto isosbéstico",
      "1. Preparar soluciones de colorante de 10 mL que den ≈ 1 UA en el máximo.",
      "2. Con cada una, armar las 10 soluciones (y sus blancos 1b–10b) según la tabla del desarrollo.",
      "3. Medir **pH real** de cada tubo y su absorbancia en λ₁ (ácida) y λ₂ (básica) contra su blanco; superponer los espectros para ubicar el punto isosbéstico.",
      "4. Calcular el pKa por el método gráfico y por el método de las pendientes; discutir con base en el fundamento.",
    ].join("\n"),
    equations: [
      {
        name: "Constante de equilibrio del indicador",
        expression: "HIn ⇌ H⁺ + In⁻        K_{a} = #{[H⁺][In⁻]|[HIn]}        pK_{a} = −log K_{a}",
        variables: "HIn = forma ácida · In⁻ = forma básica",
      },
      {
        name: "Relación entre absorbancias y especies",
        expression: "#{[In⁻]|[HIn]} = #{A − A_{HIn}|A_{In} − A}",
        variables: "A_{HIn} = absorbancia de la forma ácida pura (solución 10) · A_{In} = absorbancia de la forma básica pura (solución 9) · A = absorbancia del tubo",
      },
      {
        name: "Ecuación de Henderson-Hasselbalch (espectrofotométrica)",
        expression: "pH = pK_{a} + log #{A − A_{HIn}|A_{In} − A}",
        variables: "Graficando pH vs. el logaritmo: pendiente ≈ 1, intercepto = pK_{a}",
      },
      {
        name: "Buffer acético (para estimar el pH teórico)",
        expression: "pH = pK_{a}(AcOH) + log #{n_{AcO⁻}|n_{AcOH}}",
        variables: "pK_{a}(AcOH) = 4,76 · n = mmol (mL × N) de cada especie tras la reacción 1 : 1 con el NaOH",
      },
      {
        name: "Dilución",
        expression: "C_{1}V_{1} = C_{2}V_{2}",
        variables: "Para la curva de calibración del colorante; V_{1} = C_{2}V_{2} ÷ C_{1}",
      },
      {
        name: "Curva de calibración y verificación",
        expression: "A = m·c + b        C_{exp} = #{A − b|m}        %Rec = #{C_{exp}|C_{teo}} × 100",
        variables: "ER (%) = (C_{exp} − C_{teo}) ÷ C_{teo} × 100 · %RSD = s ÷ x̄ × 100",
      },
    ],
    dataRequested: [
      "Nombre y PM del principio activo (verde de bromocresol; indica si es ácido libre o sal sódica).",
      "Tabla de solubilidad: EtOH / agua destilada / HCl 0,1 N / NaOH 0,1 N.",
      "Barridos 400–700 nm: λmáx y absorbancia de las soluciones **A2** y **B2**.",
      "Curva de calibración: λmáx seleccionado, rango (0,17–0,85 UA), concentración de la madre, C₁…C₅ (µg/mL), absorbancias 5 × 2, recta, R², ANOVA, residuos, %RSD.",
      "Verificación (≥ 3 soluciones): C_exp, % recuperación, error relativo y %RSD.",
      "Tabla de las 10 soluciones: absorbancia y **pH real** en λ₁ y λ₂.",
      "pKa por el método gráfico y por el de las pendientes, y punto isosbéstico, con discusión.",
    ],
    studyTopics: [
      "Equilibrios ácido-base de indicadores y rango de viraje.",
      "Ecuación de Henderson-Hasselbalch y soluciones amortiguadoras (AcOH/AcO⁻).",
      "Absorbancias aditivas de dos especies y punto isosbéstico.",
      "Efecto del pH y de la fuerza iónica sobre el espectro de un indicador.",
    ],
    quizQuestions: [
      {
        question:
          "En la solución 6 mezclas **1,0 mL de NaOH 0,1 N** con **2,0 mL de AcOH 0,1 N** (volumen final 10 mL). ¿Cuál es el pH teórico? Muestra la estequiometría.",
        solution: [
          "**Reacción (1 : 1):** CH₃COOH + NaOH → CH₃COONa + H₂O.",
          "",
          "**Paso 1 — milimoles de cada reactivo.** NaOH: 1,0 mL × 0,1 mmol/mL = **0,100 mmol**. AcOH: 2,0 mL × 0,1 mmol/mL = **0,200 mmol** (el «mL» se cancela).",
          "",
          "**Paso 2 — qué queda.** Reaccionan 0,100 mmol de cada uno (1 : 1). Sobran 0,200 − 0,100 = **0,100 mmol de AcOH** y se forman **0,100 mmol de AcO⁻**.",
          "",
          "**Paso 3 — Henderson-Hasselbalch.** pH = 4,76 + log(0,100 ÷ 0,100) = 4,76 + 0 = **4,76**.",
          "",
          "**Conclusión:** es un buffer 1 : 1, justo en el pKa del acético (4,76) y muy cerca del pKa del BCG (≈ 4,8): ahí el colorante está ≈ mitad ácido, mitad básico (color verde).",
        ].join("\n"),
      },
      {
        question:
          "Datos a 617 nm: A (forma ácida, sol. 10) = 0,030 · A (forma básica, sol. 9) = 0,980 · tubo con pH real 4,60 y A = 0,410. Calcula el pKa.",
        solution: [
          "**Interpretación.** Con las dos absorbancias de referencia se calcula la razón entre formas en ese tubo y de ahí el pKa.",
          "",
          "**Paso 1 — razón [In⁻]/[HIn]** = (A − A_HIn) ÷ (A_In − A) = (0,410 − 0,030) ÷ (0,980 − 0,410) = 0,380 ÷ 0,570 = **0,667** (la UA se cancela).",
          "",
          "**Paso 2 — logaritmo:** log(0,667) = **−0,176**.",
          "",
          "**Paso 3 — pKa** = pH − log(razón) = 4,60 − (−0,176) = **4,78**.",
          "",
          "**Conclusión:** pKa ≈ 4,78, razonablemente cerca del valor de literatura (≈ 4,8–4,9). Promedia varios tubos de la zona de transición (5–8) para un valor más robusto.",
        ].join("\n"),
      },
    ],
  },
];
