import type { LabPracticeContent } from "./_schema";

/**
 * AIF — Laboratorio, Módulo II, subgrupo J5. Parte C: Prácticas 5 y 6
 * (determinación de pKa por UV-Vis y aditividad de absorbancias). Los números
 * de los ejemplos son ILUSTRATIVOS; los datos reales salen de tu medición.
 */
export const aifModulo2PracticasC: LabPracticeContent[] = [
  // ───────────────────────────── PRÁCTICA 5 ─────────────────────────────
  {
    number: 5,
    labModule: "Módulo II",
    title: "Determinación del pKa: efecto del pH en el espectro UV (ácido gálico)",
    moduleSlug: "uv-visible",
    fundamento:
      "Cuando un analito se **ioniza**, su espectro UV cambia (las formas HA y A⁻ absorben distinto). Midiendo la absorbancia del **ácido gálico** en **soluciones amortiguadoras de pH 2–12** (preparadas desde la solución **Britton-Robinson**, BR) a las λmáx de ambas especies, se grafica A vs. pH y se obtiene el **pKa** por el **método gráfico** y el **método de las pendientes**. Sirve para entender cómo el pH gobierna el equilibrio ácido-base de compuestos de interés farmacéutico.",
    desarrollo: [
      "#### En una frase",
      "",
      "Vas a preparar una serie de buffers de pH conocido (del 2 al 12), poner **la misma cantidad de ácido gálico** en cada uno y ver **cómo cambia su espectro con el pH**. Del punto donde la mitad está ionizada sale el **pKa**.",
      "",
      "> **Analogía — el interruptor con regulador (dimmer).** A pH muy bajo el ácido gálico está «apagado» (sin ionizar, HA); a pH muy alto está «encendido» (ionizado, A⁻). El pKa es el pH donde el regulador está justo a la mitad: 50 % HA y 50 % A⁻. Medir la absorbancia a distintos pH es ir moviendo el regulador y anotando cuánta luz absorbe en cada posición.",
      "",
      "#### Qué es el ácido gálico y por qué tiene más de un pKa",
      "",
      "El **ácido gálico** (ácido 3,4,5-trihidroxibenzoico, C₇H₆O₅) es un anillo bencénico con **un grupo –COOH** y **tres –OH fenólicos**. Cada grupo ionizable puede tener su propio pKa:",
      "",
      "- **–COOH:** pKa₁ ≈ **4,4** (valor de literatura aproximado).",
      "- **–OH fenólico (el de la posición 4):** pKa₂ ≈ **8,7–8,9**.",
      "- Otros –OH: pKa mucho más altos (> 11).",
      "",
      "Por eso la curva A vs. pH puede mostrar **más de una transición** (la guía habla de «el/los valores de pKa»). Y por eso hay que **seguir el espectro en pH 2–12**: cada ionización cambia el espectro en un rango de pH distinto.",
      "",
      "**Estabilidad:** a pH básico el ácido gálico se **oxida con el aire** (la solución se pone amarilla/marrón y el espectro cambia con el tiempo). Mide **pronto y a un tiempo fijo** tras preparar cada solución y anota cualquier cambio de color.",
      "",
      "**Hidratación (¡importante!).** El ácido gálico comercial suele ser **monohidratado**: C₇H₆O₅·H₂O, **PM ≈ 188,13 g/mol**, frente al anhidro (**170,12 g/mol**). Si la concentración que te piden es de *ácido gálico* (anhidro) y tu frasco es monohidrato, debes pesar de más:",
      "",
      "- **Factor de conversión:** m_monohidrato = m_anhidro × (188,13 ÷ 170,12) = m_anhidro × **1,106** (los g de ácido gálico anhidro se cancelan: el factor solo cambia «de qué forma» se pesa).",
      "- **Ejemplo:** para 25,00 mg de ácido gálico (anhidro) → 25,00 × 1,106 = **27,65 mg de monohidrato**.",
      "- **Conclusión:** anota en tu informe la forma del reactivo (lee la etiqueta) y con cuál PM calculaste.",
      "",
      "#### Parte 1 — Preparar la solución buffer de Britton-Robinson (500 mL)",
      "",
      "El **buffer BR** mezcla tres ácidos (**H₃PO₄, CH₃COOH y H₃BO₃**, todos a **0,04 M**): como sus pKa están repartidos (≈ 2,1 – 7,2 – 12,3 para el fosfórico; 4,76 el acético; 9,2 el bórico), el sistema **amortigua en todo el rango de pH 2–12** si se titula con NaOH. Es un buffer «universal».",
      "",
      "**Interpretación.** Quieres 500 mL en los que cada ácido esté a 0,04 M. Para cada uno: moles necesarios → masa o volumen del reactivo comercial.",
      "",
      "**Paso 1 — moles de cada ácido.** 0,04 mol/L × 0,500 L = **0,0200 mol** (el «L» se cancela).",
      "",
      "**Paso 2 — H₃PO₄** (reactivo comercial típico: 85 % p/p, densidad 1,685 g/mL, PM 97,99 g/mol; **verifica los datos de tu frasco**):",
      "",
      "- **Factor de conversión:** 0,0200 mol × (97,99 g ÷ 1 mol) = **1,960 g** de H₃PO₄ puro (el «mol» se cancela).",
      "- **Corrección por pureza:** 1,960 g ÷ 0,85 = **2,306 g** de reactivo comercial (la solución trae 85 % de ácido).",
      "- **Pasar masa a volumen:** 2,306 g ÷ 1,685 g/mL = **1,368 mL = 1368 µL** (el «g» se cancela; 1 mL = 1000 µL).",
      "",
      "**Paso 3 — CH₃COOH glacial** (≈ 99,8–100 %, densidad 1,049 g/mL, PM 60,05 g/mol):",
      "",
      "- 0,0200 mol × (60,05 g ÷ 1 mol) = **1,201 g** → ÷ 1,049 g/mL = **1,145 mL = 1145 µL** (si tu frasco es 99,8 %: 1,201 ÷ 0,998 ÷ 1,049 = 1147 µL).",
      "",
      "**Paso 4 — H₃BO₃** (sólido, PM 61,83 g/mol):",
      "",
      "- 0,0200 mol × (61,83 g ÷ 1 mol) = **1,237 g = 1237 mg** (1 g = 1000 mg).",
      "",
      "**Paso 5 — armar.** Disuelve en ≈ 400 mL de agua, mezcla, **afora a 500 mL** y mide el **pH** con el potenciómetro (debe ser ≈ 2).",
      "",
      "| Reactivo | Cantidad calculada | Concentración final |",
      "| --- | --- | --- |",
      "| H₃PO₄ (µL) | ≈ 1368 | 0,04 M |",
      "| CH₃COOH (µL) | ≈ 1145 | 0,04 M |",
      "| H₃BO₃ (mg) | ≈ 1237 | 0,04 M |",
      "",
      "**Chequeo (comprobación de la concentración).** 1,368 mL × 1,685 g/mL × 0,85 ÷ 97,99 g/mol = 0,01999 mol → ÷ 0,500 L = **0,0400 M** ✔.",
      "",
      "#### Parte 2 — Ajustar el pH de cada buffer con NaOH 0,1 N",
      "",
      "Rotula 10 vasos con los pH de la tabla, mide **50 mL de BR** en cada uno (probeta) y **agrega NaOH 0,1 N** hasta llegar a un pH muy cercano al rotulado, siguiendo el pH con el potenciómetro. **Registra el volumen de NaOH** gastado y el **pH real** (el que marca el equipo, no el deseado).",
      "",
      "> **Ojo, dos observaciones de la guía:** (1) el texto habla de «pH 2–12» y los objetivos de «2–10»; la tabla de ajuste lista 2, 4, 5, 6, 7, 8, 9, 10, 11, 12 y la de lecturas va de 3 a 12. Confirma con el docente el juego exacto de pH. (2) Donde dice «solución amortiguadora BT» es BR (Britton-Robinson).",
      "",
      "#### Parte 3 — Preparar las soluciones del analito (8 µg/mL)",
      "",
      "**Interpretación.** Todas las soluciones deben tener **la misma concentración de ácido gálico (8 µg/mL)** para que lo único que cambie entre ellas sea el pH. Se hace con una solución intermedia («C»).",
      "",
      "**Paso 1 — Solución C (160 µg/mL, 20 mL)** a partir de la madre (en agua destilada o EtOH 96 %). **Ejemplo:** madre de 1000 µg/mL.",
      "",
      "- **Factor de conversión:** V₁ = (160 µg/mL × 20,0 mL) ÷ (1000 µg/mL) = **3,2 mL** (el «µg/mL» se cancela). Afora a 20 mL.",
      "",
      "**Paso 2 — cada buffer.** En 10 balones de 20 mL, **1,0 mL de solución C** y se afora con cada buffer.",
      "",
      "- **Factor de conversión:** C_final = (160 µg/mL × 1,0 mL) ÷ 20 mL = **8 µg/mL** (los mL se cancelan).",
      "- **En moles:** 8 µg/mL = 8 mg/L → 8 × 10⁻³ g/L ÷ 170,12 g/mol = **4,7 × 10⁻⁵ mol/L (47 µM)** (con PM del anhidro).",
      "- **Conclusión:** las 10 soluciones tienen idéntico contenido de analito y solo difieren en el pH.",
      "",
      "#### Parte 4 — Medir, graficar y obtener el pKa",
      "",
      "Mide cada solución a las **λmáx de ambas especies** (HA y A⁻), que ya habrás determinado con las soluciones en **HCl 0,1 N** (forma ácida) y **NaOH 0,1 N** (forma básica), tal como en la Práctica 3. Cada integrante hace su preparación para tener **duplicado**. Registra absorbancia y pH real en la tabla (réplica 1 y réplica 2).",
      "",
      "**Fundamento del cálculo** (idéntico al de la Práctica 4, con HA/A⁻ en vez de HIn/In⁻):",
      "",
      "```formula",
      "pH = pK_{a} + log #{A − A_{HA}|A_{A} − A}",
      "```",
      "",
      "- **Método gráfico:** A (a la λ de la especie que cambia) vs. pH → sigmoide; **pKa = pH en el punto medio** entre A_HA (meseta ácida) y A_A⁻ (meseta básica). Si hay dos ionizaciones, verás **dos mesetas y dos puntos medios** (pKa₁, pKa₂).",
      "- **Método de las pendientes (linealización):** pH vs. log[(A − A_HA) ÷ (A_A − A)] en la zona de transición → recta de **pendiente ≈ 1**; el **intercepto es el pKa**. Si la pendiente se aleja mucho de 1 puede haber más de un equilibrio superpuesto o oxidación del analito.",
      "- **Punto(s) isosbéstico(s):** si superpones los espectros por regiones de pH, los cruces señalan un equilibrio entre dos especies.",
      "",
      "**Ejemplo ilustrativo** (λ de la forma ácida; A_HA = 0,850 a pH 2; A_A = 0,150 a pH 6,5; un tubo con pH real 4,40 y A = 0,500):",
      "",
      "- **Razón [A⁻]/[HA]** = (0,500 − 0,850) ÷ (0,150 − 0,500) = (−0,350) ÷ (−0,350) = **1,00** (los signos y la UA se cancelan).",
      "- **log(1,00)** = 0.",
      "- **pKa** = pH − log(razón) = 4,40 − 0 = **4,40**.",
      "- **Conclusión:** a pH 4,40 el analito está 50 % ionizado → pKa₁ ≈ 4,40, coherente con el –COOH del ácido gálico.",
      "",
      "**Diagrama de distribución de especies** (opcional, ayuda a la discusión). Para un ácido monoprótico: fracción sin ionizar α_HA = 1 ÷ (1 + 10^(pH − pKa)); fracción ionizada α_A = 1 − α_HA. **Ejemplo** con pKa = 4,40 a pH 6,40: α_HA = 1 ÷ (1 + 10²) = 0,0099 (≈ 1 %) → **99 % ionizado**. Regla práctica: a pH = pKa ± 2, ya hay ≈ 99 % de una forma.",
      "",
      "#### Resultado esperado",
      "",
      "- Espectros que cambian con el pH (desplazamiento de λmáx y/o de la absorbancia) y curva A vs. pH sigmoide con 1–2 transiciones.",
      "- pKa₁ ≈ 4,4 (–COOH) y, si el rango de pH lo permite, pKa₂ ≈ 8,7–8,9 (–OH fenólico), por ambos métodos.",
      "- A pH alto, cuidado con la **oxidación** (derivas de absorbancia, color marrón).",
      "- En la discusión: relaciona el pKa con la **solubilidad y absorción** del fármaco (forma ionizada vs. neutra) y comenta fuentes de error: pH real, fuerza iónica variable, tiempo de medición, oxidación.",
    ].join("\n"),
    keyPoints: [
      "**Buffer BR 500 mL:** H₃PO₄ ≈ 1368 µL (85 %, d 1,685), CH₃COOH ≈ 1145 µL (glacial, d 1,049), H₃BO₃ ≈ 1237 mg, todos **0,04 M**; pH final ≈ 2. **Verifica pureza y densidad de TUS frascos**.",
      "**Ajuste de pH:** 50 mL de BR + NaOH 0,1 N hasta el pH deseado; registra **mL de NaOH** y **pH real**.",
      "**Solución C = 160 µg/mL (20 mL)** → 1 mL en balones de 20 mL con cada buffer → **8 µg/mL** en todas.",
      "**Medir a las λmáx de HA y A⁻** (tomadas en HCl 0,1 N y NaOH 0,1 N). Solución madre en agua destilada o EtOH 96 %.",
      "**pKa por dos métodos:** gráfico (punto medio de la sigmoide) y de las pendientes (pendiente ≈ 1; intercepto = pKa).",
      "**Ácido gálico:** –COOH (pKa₁ ≈ 4,4) y –OH fenólico (pKa₂ ≈ 8,7–8,9); a pH alto se **oxida**: medir pronto y a tiempo fijo.",
      "**Chequeo de hidratación:** el ácido gálico suele ser **monohidrato (PM ≈ 188,13)**; para X mg de ácido gálico anhidro (170,12) pesa X × 1,106.",
      "**Cada integrante prepara su muestra** para obtener duplicado de la medida.",
      "**Aclarar con el docente:** el juego de pH (2–10 vs. 2–12; tablas distintas) y que «BT» es BR.",
    ],
    procedure: [
      "#### Actividad A — Soluciones de trabajo y λmáx",
      "1. Preparar la solución madre del ácido gálico (agua destilada o EtOH 96 %).",
      "2. Preparar soluciones de trabajo en **HCl 0,1 N** y en **NaOH 0,1 N** y hacer el barrido 200–400 nm de cada una (metodología de la Práctica 3) para hallar los λmáx de HA y de A⁻.",
      "",
      "#### Actividad B — Buffer BR",
      "1. Calcular y medir los volúmenes/masas de H₃PO₄, CH₃COOH y H₃BO₃ para 500 mL a 0,04 M cada uno.",
      "2. Disolver, aforar y medir el pH con el potenciómetro (≈ 2). Completar la tabla (valor y concentración).",
      "",
      "#### Actividad C — Buffers a pH 2–12",
      "1. Rotular 10 vasos con los pH de la tabla; medir 50 mL de BR en cada uno.",
      "2. Adicionar NaOH 0,1 N hasta un pH muy cercano al rotulado; registrar el volumen de NaOH y el pH real.",
      "",
      "#### Actividad D — Muestras y medición",
      "1. Preparar en un balón de 20 mL la **solución C (160 µg/mL)** a partir de la madre.",
      "2. En 10 balones de 20 mL: 1,0 mL de solución C + aforo con cada buffer → 8 µg/mL.",
      "3. Medir absorbancia a λmáx de HA y de A⁻ de cada solución y su pH real (réplica 1 y réplica 2).",
      "4. Graficar A vs. pH; calcular el pKa por el método gráfico y por el de las pendientes; discutir.",
    ].join("\n"),
    equations: [
      {
        name: "Moles de cada ácido del buffer BR",
        expression: "n = M × V = 0,04 mol/L × 0,500 L = 0,0200 mol",
        variables: "Luego: masa = n × PM; volumen de reactivo comercial = masa ÷ (pureza × densidad)",
      },
      {
        name: "Volumen de reactivo líquido comercial",
        expression: "V = #{n × PM|pureza × d}",
        variables: "n (mol) · PM (g/mol) · pureza (fracción: 85 % = 0,85) · d (g/mL) · V en mL (× 1000 = µL)",
      },
      {
        name: "Dilución (solución C y soluciones de trabajo)",
        expression: "C_{1}V_{1} = C_{2}V_{2}",
        variables: "Solución C: 160 µg/mL · 8 µg/mL = 160 µg/mL × 1,0 mL ÷ 20 mL",
      },
      {
        name: "Henderson-Hasselbalch espectrofotométrica",
        expression: "pH = pK_{a} + log #{A − A_{HA}|A_{A} − A}",
        variables: "A_{HA} = meseta ácida · A_{A} = meseta básica · A = absorbancia del tubo",
        description: "Graficando pH vs. el logaritmo: pendiente ≈ 1 y intercepto = pKa.",
      },
      {
        name: "Fracción ionizada",
        expression: "α_{A} = #{1|1 + 10^{pK_{a} − pH}}",
        variables: "α_{A} = fracción como A⁻ · α_{HA} = 1 − α_{A}",
      },
      {
        name: "Masa de ácido gálico monohidrato",
        expression: "m_{monohidrato} = m_{anhidro} × #{188,13|170,12}",
        variables: "Factor ≈ 1,106 · úsalo si pesas el monohidrato y te piden la concentración como ácido gálico anhidro",
      },
    ],
    dataRequested: [
      "Nombre y PM del principio activo (ácido gálico; indica si es monohidrato o anhidro).",
      "Tabla del buffer BR: H₃PO₄ (µL), CH₃COOH (µL), H₃BO₃ (mg) con su concentración (M) y el **pH de la solución BR**.",
      "Tabla de ajuste: pH aproximado → volumen de NaOH 0,1 N (mL) y **pH real**.",
      "Cálculos de la solución C (160 µg/mL, 20 mL) y de las soluciones de 8 µg/mL.",
      "Tabla de lecturas: pH aproximado × réplica 1 y 2 → **Abs [HA]**, **Abs [A⁻]**, **pH real**.",
      "Gráficas A vs. pH, pKa por el método gráfico y por el de las pendientes, y discusión.",
    ],
    studyTopics: [
      "Equilibrio ácido-base, pKa y Henderson-Hasselbalch; diagramas de distribución de especies.",
      "Buffer de Britton-Robinson: composición y rango útil.",
      "Cambio del espectro UV con la ionización (desplazamientos batocrómico/hipsocrómico).",
      "pKa y propiedades farmacéuticas: solubilidad, absorción y formas iónica/neutra.",
    ],
    quizQuestions: [
      {
        question:
          "Para el buffer BR necesitas **0,0200 mol de CH₃COOH** (PM 60,05 g/mol; d 1,049 g/mL; pureza ≈ 100 %). ¿Cuántos µL mides? Muestra los factores de conversión.",
        solution: [
          "**Interpretación.** Pasar de moles → gramos (con el PM) → mL (con la densidad) → µL.",
          "",
          "**Paso 1 — gramos.** 0,0200 mol × (60,05 g ÷ 1 mol) = **1,201 g** (el «mol» se cancela).",
          "",
          "**Paso 2 — mL.** 1,201 g ÷ (1,049 g/mL) = **1,145 mL** (el «g» se cancela).",
          "",
          "**Paso 3 — µL.** 1,145 mL × (1000 µL ÷ 1 mL) = **1145 µL** (el «mL» se cancela).",
          "",
          "**Conclusión:** mide ≈ 1145 µL de ácido acético glacial (≈ 1147 µL si tu frasco es 99,8 %). Se afora a 500 mL → 0,04 M.",
        ].join("\n"),
      },
      {
        question:
          "A pH 4,40 un ácido tiene **pKa = 4,40**. ¿Qué fracción está ionizada? ¿Y a pH 6,40?",
        solution: [
          "**Interpretación.** Fracción ionizada α_A = 1 ÷ (1 + 10^(pKa − pH)).",
          "",
          "**pH 4,40:** 10^(4,40 − 4,40) = 10⁰ = 1 → α_A = 1 ÷ 2 = **0,50 (50 %)**.",
          "",
          "**pH 6,40:** 10^(4,40 − 6,40) = 10⁻² = 0,01 → α_A = 1 ÷ 1,01 = **0,990 (99 %)**.",
          "",
          "**Conclusión:** a pH = pKa hay 50 % de cada forma; a pH = pKa + 2 ya predomina ≈ 99 % la forma ionizada. Por eso el espectro cambia casi completo en ± 2 unidades de pH alrededor del pKa.",
        ].join("\n"),
      },
    ],
  },

  // ───────────────────────────── PRÁCTICA 6 ─────────────────────────────
  {
    number: 6,
    labModule: "Módulo II",
    title: "Cuantificación de dos analitos por aditividad de absorbancias (AC + CAF)",
    moduleSlug: "espectrofotometria-fundamentos",
    fundamento:
      "Si dos analitos **absorben en la misma región** y no interactúan, la absorbancia de la mezcla a cada longitud de onda es la **suma** de las absorbancias de sus componentes (**aditividad**, ley de Lambert-Beer). Midiendo la mezcla a **dos longitudes de onda** y conociendo la **absortividad de cada analito a ambas** (pendientes de 4 curvas de calibración) se obtiene un **sistema de 2 ecuaciones con 2 incógnitas** que da la concentración de cada analito **sin separarlos**.",
    desarrollo: [
      "#### En una frase",
      "",
      "Tienes una mezcla de **dos sustancias** (según el cronograma del grupo: **AC + CAF**, cafeína = CAF) que no puedes separar. Midiendo la luz que absorbe la mezcla en **dos longitudes de onda** y sabiendo cuánto absorbe cada sustancia sola en ambas, **resuelves un sistema de 2 ecuaciones** y obtienes cuánto hay de cada una.",
      "",
      "> **Aviso sobre «AC».** En la tabla del grupo solo dice «AC + CAF». Lo más habitual en un producto comercial con cafeína es **acetaminofén (paracetamol)**, pero también existe **ácido acetilsalicílico**. Aquí se usa «AC» de forma genérica y se dan datos de ambos; **confirma con el docente cuál es** (cambia λ, pKa y estabilidad).",
      "",
      "> **Analogía — dos tintas en un vaso.** Echas tinta azul y tinta roja en el mismo vaso. Con un solo filtro de color no sabes cuánto hay de cada una (los dos colores bloquean luz en cualquier filtro). Pero con **dos filtros distintos**, y sabiendo cuánto bloquea cada tinta sola en cada filtro, tienes dos mediciones para dos incógnitas: las puedes resolver.",
      "",
      "#### La base teórica (ecuaciones de la guía, explicadas)",
      "",
      "**Ecuación (1) — Lambert-Beer:** **A_λ = ε_λ · b · C**. Para **un** analito: la absorbancia a una λ es proporcional a su concentración.",
      "",
      "**Ecuaciones (2) y (3) — aditividad.** Si los componentes **no reaccionan entre sí ni alteran la absorción del otro**, a una λ dada:",
      "",
      "```formula",
      "A_{λ} = A_{1,λ} + A_{2,λ} = ε_{1,λ}·b·C_{1} + ε_{2,λ}·b·C_{2}",
      "```",
      "",
      "(La guía escribe «ε₁λ·b·C₁ + ε₁λ·b·C₁…» con los mismos subíndices por una errata de copiado; lo correcto es 1 y 2, uno por analito.)",
      "",
      "**Ecuaciones (4) y (5) — simplificar.** Como la celda es la misma (b = 1 cm), se agrupa **k_{i,λ} = ε_{i,λ}·b** (la *pendiente* de la curva de calibración del analito *i* a esa λ, en UA por µg/mL). Queda: **A_λ = k₁λ·C₁ + k₂λ·C₂**.",
      "",
      "**El sistema de 2 ecuaciones, con 2 longitudes de onda (λ₁ y λ₂):**",
      "",
      "```formula",
      "A_{λ1} = k_{11}·C_{1} + k_{21}·C_{2}",
      "A_{λ2} = k_{12}·C_{1} + k_{22}·C_{2}",
      "```",
      "",
      "(k_{ij}: analito *i*, longitud de onda *j*.) Las **dos incógnitas** son C₁ y C₂; las **medidas** son A_{λ1} y A_{λ2} de la mezcla; las **k** salen de **cuatro curvas de calibración** (cada analito por separado, a cada λ).",
      "",
      "**Solución por determinantes (Cramer):**",
      "",
      "```formula",
      "D = k_{11}·k_{22} − k_{21}·k_{12}",
      "C_{1} = #{A_{λ1}·k_{22} − k_{21}·A_{λ2}|D}",
      "C_{2} = #{k_{11}·A_{λ2} − k_{12}·A_{λ1}|D}",
      "```",
      "",
      "#### Elegir las dos longitudes de onda (lo más importante)",
      "",
      "- **Ideal:** una λ donde **solo un analito absorbe** y otra donde solo absorbe el otro; entonces las dos ecuaciones casi se desacoplan.",
      "- **Realista:** dos λ donde **cada analito absorbe sobre todo en una** y poco en la otra (p. ej. cada uno en su propio λmáx).",
      "- **Por qué importa el determinante D:** si los espectros son muy parecidos en las dos λ, D se acerca a 0 y **cualquier error pequeño de absorbancia se amplifica enormemente** en C₁ y C₂. Elige λ donde los espectros **se diferencien** lo más posible.",
      "",
      "**Referencias (literatura, aproximadas; tus barridos mandan):**",
      "",
      "| Analito | PM | λmáx aprox. | pKa relevante | Nota |",
      "| --- | --- | --- | --- | --- |",
      "| Cafeína (CAF) | 194,19 (anhidra) | ≈ 273 nm | ≈ 0,6 (ácido conjugado) → neutra en casi todo el rango de pH | Existe el **monohidrato** (PM ≈ 212,2): ver chequeo de hidratación. |",
      "| Acetaminofén (si AC = paracetamol) | 151,16 | ≈ 243 nm (agua/ácido) | ≈ 9,5 (fenol) | A pH muy básico se ioniza y su λmáx se desplaza. |",
      "| Ácido acetilsalicílico (si AC = AAS) | 180,16 | ≈ 229 y ≈ 276 nm | ≈ 3,5 | **Se hidroliza** a ácido salicílico en agua/medio básico: medir fresco y sin calentar. |",
      "",
      "**Chequeo de hidratación:** la cafeína comercial puede ser anhidra (194,19) o **monohidrato (≈ 212,2)**. Para X mg de cafeína anhidra: m_monohidrato = X × (212,2 ÷ 194,19) = X × **1,093**. Anota la forma de tu patrón.",
      "",
      "#### Cuál solvente usar (diagramas de distribución de especies)",
      "",
      "El objetivo pide elegir el disolvente según el **pH** y la **especie dominante** de cada analito: lo mejor es un medio donde **cada analito esté en una sola forma estable**, para que su espectro no cambie con pequeñas variaciones de pH.",
      "",
      "**Ejemplo (AC = acetaminofén, pKa ≈ 9,5) en agua (pH ≈ 7).**",
      "",
      "- **Fracción neutra** α_HA = 1 ÷ (1 + 10^(pH − pKa)) = 1 ÷ (1 + 10^(7 − 9,5)) = 1 ÷ (1 + 0,0032) = **0,997 (99,7 %)**.",
      "- **Conclusión:** a pH 7 el acetaminofén está prácticamente 100 % neutro; la cafeína (pKa ≈ 0,6) también. **Ambos neutros → espectros estables → el agua (o un medio ligeramente ácido, no muy fuerte) es buena opción.** Un HCl 0,1 N (pH ≈ 1) deja a la cafeína ≈ 29 % protonada (10^(0,6 − 1) = 0,40 → 0,40 ÷ 1,40), lo que movería su espectro: no es lo ideal.",
      "",
      "#### Curvas de calibración: 4 curvas, 5 niveles, duplicado independiente",
      "",
      "Para **cada analito**: espectro individual → λmáx, **dos λ de trabajo** y, **a cada λ**, una curva de **5 niveles × 2 réplicas** (rango 0,17–0,85 UA, C₁V₁ = C₂V₂, regresión, ANOVA, incertidumbres, residuos, %RSD por nivel; igual que en las Prácticas 3 y 4). De cada curva sale la **pendiente k** (UA por µg/mL). Total: **4 pendientes** (k₁₁, k₂₁, k₁₂, k₂₂).",
      "",
      "**Ejemplo de dilución (factores):** madre de 200 µg/mL; nivel de 8 µg/mL en balón de 25,0 mL → V₁ = (8 µg/mL × 25,0 mL) ÷ (200 µg/mL) = **1,0 mL** (el «µg/mL» se cancela).",
      "",
      "#### El «reto»: resolver una mezcla (ejemplo numérico completo, ilustrativo)",
      "",
      "Pendientes (UA por µg/mL), obtenidas de las 4 curvas:",
      "",
      "| | λ₁ | λ₂ |",
      "| --- | --- | --- |",
      "| Analito 1 | k₁₁ = 0,050 | k₁₂ = 0,010 |",
      "| Analito 2 | k₂₁ = 0,004 | k₂₂ = 0,040 |",
      "",
      "La mezcla problema dio **A_λ1 = 0,448** y **A_λ2 = 0,560**.",
      "",
      "**Paso 1 — plantear el sistema.** *Interpretación:* a cada λ, la absorbancia total es la suma de lo que aporta cada analito.",
      "",
      "- 0,050·C₁ + 0,004·C₂ = 0,448",
      "- 0,010·C₁ + 0,040·C₂ = 0,560",
      "",
      "**Paso 2 — determinante.** D = k₁₁·k₂₂ − k₂₁·k₁₂ = 0,050 × 0,040 − 0,004 × 0,010 = 0,002 − 0,00004 = **0,00196**. *(D no es casi cero: las λ discriminan bien.)*",
      "",
      "**Paso 3 — C₁.** C₁ = (A_λ1·k₂₂ − k₂₁·A_λ2) ÷ D = (0,448 × 0,040 − 0,004 × 0,560) ÷ 0,00196 = (0,01792 − 0,00224) ÷ 0,00196 = 0,01568 ÷ 0,00196 = **8,0 µg/mL**.",
      "",
      "- **Factor de conversión:** el numerador está en UA·(UA por µg/mL) y el denominador en (UA por µg/mL)²; al dividir, queda UA ÷ (UA por µg/mL) = **µg/mL**.",
      "",
      "**Paso 4 — C₂.** C₂ = (k₁₁·A_λ2 − k₁₂·A_λ1) ÷ D = (0,050 × 0,560 − 0,010 × 0,448) ÷ 0,00196 = (0,02800 − 0,00448) ÷ 0,00196 = **12,0 µg/mL**.",
      "",
      "**Paso 5 — comprobar** (sustituir en las dos ecuaciones): 0,050 × 8,0 + 0,004 × 12,0 = 0,400 + 0,048 = 0,448 ✔ · 0,010 × 8,0 + 0,040 × 12,0 = 0,080 + 0,480 = 0,560 ✔.",
      "",
      "**Conclusión:** la mezcla contiene 8,0 µg/mL del analito 1 y 12,0 µg/mL del analito 2. Si la muestra se diluyó (p. ej. 1 : 50 desde una tableta), multiplica por el factor de dilución y pasa µg → mg (÷ 1000) para llegar al contenido por tableta, como en la Práctica 3.",
      "",
      "#### Resultado esperado",
      "",
      "- Cuatro rectas con R² ≈ 1; k mayores en el λmáx propio de cada analito.",
      "- Recuperación cercana al 100 % de cada componente en mezclas de composición conocida; %RSD bajo.",
      "- Si usas un producto comercial, contenido por tableta cercano al declarado para ambos activos.",
      "- En la discusión: límites del método (λ mal elegidas, espectros muy solapados, interacciones entre analitos, desviaciones de Lambert-Beer a A > 1) y su utilidad frente a una separación cromatográfica.",
    ].join("\n"),
    keyPoints: [
      "**Condición:** los componentes **no reaccionan ni se afectan** entre sí; a cada λ, A_mezcla = Σ k_i·C_i (aditividad).",
      "**Calibración:** **4 curvas** (2 analitos × 2 λ), cada una de **5 niveles con duplicado independiente**, rango 0,17–0,85 UA; las **pendientes k** son la absortividad (UA por µg/mL).",
      "**Elegir λ:** una donde domina un analito y otra donde domina el otro; verifica que el **determinante D** no sea ≈ 0.",
      "**Solución del sistema:** C₁ = (A₁·k₂₂ − k₂₁·A₂) ÷ D · C₂ = (k₁₁·A₂ − k₁₂·A₁) ÷ D, con D = k₁₁k₂₂ − k₂₁k₁₂.",
      "**Elegir solvente:** con base en el pH medido y la **especie dominante** de cada analito (diagramas de distribución de especies, según su pKa).",
      "**Reto:** mezclas de composición conocida o producto comercial; reporta recuperación, error relativo y %RSD.",
      "**«AC» sin definir:** confirmar con el docente si es acetaminofén o ácido acetilsalicílico (λ, pKa y estabilidad distintos; el AAS se hidroliza).",
      "**Chequeo de hidratación:** cafeína anhidra (194,19) vs. monohidrato (≈ 212,2): factor ≈ 1,093 al pesar el monohidrato.",
    ],
    procedure: [
      "#### Actividad A — Propiedades y elección del solvente",
      "1. Consultar pKa, solubilidad y estructura de los dos analitos y construir sus diagramas de distribución de especies.",
      "2. Escoger el solvente según el pH medido y la especie dominante de cada analito.",
      "",
      "#### Actividad B — Espectros y longitudes de onda de trabajo",
      "1. Preparar madre y soluciones de trabajo de cada analito (metodología de las Prácticas 3 a 5).",
      "2. Obtener el barrido individual de cada uno; registrar λmáx y absorbancia (tabla de la guía).",
      "3. Elegir las **dos longitudes de onda de trabajo** (ver criterios del desarrollo).",
      "",
      "#### Actividad C — Curvas de calibración",
      "1. Para cada analito y a **cada λ**, construir una curva de 5 niveles × 2 réplicas (rango 0,17–0,85 UA; C₁V₁ = C₂V₂).",
      "2. Evaluar cada curva: pendiente, intercepto, R², ANOVA, incertidumbres, residuos y %RSD por nivel.",
      "3. Anotar las 4 pendientes (k₁₁, k₂₁, k₁₂, k₂₂) o las absortividades molares.",
      "",
      "#### Actividad D — El reto",
      "1. Preparar mezclas de los dos analitos (o usar un producto comercial que los contenga).",
      "2. Medir la absorbancia de cada mezcla a las dos λ.",
      "3. Resolver el sistema de 2 ecuaciones con 2 incógnitas; calcular concentración de cada analito, % recuperación, error relativo y %RSD.",
    ].join("\n"),
    equations: [
      {
        name: "Ley de Lambert-Beer",
        expression: "A_{λ} = ε_{λ} · b · C",
        variables: "A = −log T · ε = absortividad molar (L·mol^{−1}·cm^{−1}) · b = paso óptico (cm) · C = concentración",
      },
      {
        name: "Aditividad de absorbancias",
        expression: "A_{λ} = A_{1,λ} + A_{2,λ} = ε_{1,λ}·b·C_{1} + ε_{2,λ}·b·C_{2}",
        variables: "Válida si los componentes no reaccionan ni alteran la absorción del otro.",
      },
      {
        name: "Constante de proporcionalidad k",
        expression: "k_{i,λ} = ε_{i,λ} · b",
        variables: "k = pendiente de la curva de calibración del analito i a la longitud de onda λ (UA por µg/mL)",
      },
      {
        name: "Sistema de 2 ecuaciones",
        expression: "A_{λ1} = k_{11}·C_{1} + k_{21}·C_{2}\nA_{λ2} = k_{12}·C_{1} + k_{22}·C_{2}",
        variables: "k_{ij}: analito i, longitud de onda j · incógnitas C_{1} y C_{2}",
      },
      {
        name: "Solución por determinantes (Cramer)",
        expression: "D = k_{11}k_{22} − k_{21}k_{12}\nC_{1} = #{A_{λ1}k_{22} − k_{21}A_{λ2}|D}\nC_{2} = #{k_{11}A_{λ2} − k_{12}A_{λ1}|D}",
        variables: "Si D ≈ 0, las λ no discriminan: cambia de longitud de onda.",
      },
      {
        name: "Verificación de la mezcla",
        expression: "%Rec = #{C_{exp}|C_{teo}} × 100        ER (%) = #{C_{exp} − C_{teo}|C_{teo}} × 100",
        variables: "Para cada analito de la mezcla de composición conocida",
      },
    ],
    dataRequested: [
      "Propiedades fisicoquímicas de cada analito (pKa, solubilidad, estructura) y sus diagramas de distribución de especies; solvente escogido y su pH.",
      "Tabla de λmáx y absorbancia de cada analito (barridos individuales) y las dos λ de trabajo.",
      "Para cada analito: λmáx seleccionado, rango (0,17–0,85 UA), concentración de la madre y C₁…C₅ (µg/mL).",
      "Absorbancias 5 × 2 a cada λ; recta, k (pendiente), R², ANOVA, incertidumbres, residuos y %RSD por nivel.",
      "Absorbancias de las mezclas a las dos λ; C₁ y C₂ calculadas, % recuperación, error relativo y %RSD.",
      "Discusión y conclusión.",
    ],
    studyTopics: [
      "Aditividad de absorbancias y sistemas de ecuaciones para mezclas binarias.",
      "Desviaciones de la ley de Lambert-Beer y error espectrofotométrico.",
      "Diagramas de distribución de especies y pKa de cafeína, acetaminofén y ácido acetilsalicílico.",
      "Selección de longitudes de onda para minimizar el error en mezclas con espectros solapados.",
    ],
    quizQuestions: [
      {
        question:
          "k₁₁ = 0,050 · k₁₂ = 0,010 · k₂₁ = 0,004 · k₂₂ = 0,040 (UA por µg/mL). La mezcla da A_λ1 = 0,300 y A_λ2 = 0,400. Calcula C₁ y C₂.",
        solution: [
          "**Interpretación.** Sistema: 0,050·C₁ + 0,004·C₂ = 0,300 y 0,010·C₁ + 0,040·C₂ = 0,400.",
          "",
          "**Paso 1 — determinante.** D = 0,050 × 0,040 − 0,004 × 0,010 = 0,00200 − 0,00004 = **0,00196**.",
          "",
          "**Paso 2 — C₁.** (0,300 × 0,040 − 0,004 × 0,400) ÷ 0,00196 = (0,01200 − 0,00160) ÷ 0,00196 = 0,01040 ÷ 0,00196 = **5,31 µg/mL**.",
          "",
          "**Paso 3 — C₂.** (0,050 × 0,400 − 0,010 × 0,300) ÷ 0,00196 = (0,02000 − 0,00300) ÷ 0,00196 = 0,01700 ÷ 0,00196 = **8,67 µg/mL**.",
          "",
          "**Comprobación:** 0,050 × 5,31 + 0,004 × 8,67 = 0,2655 + 0,0347 = 0,300 ✔ · 0,010 × 5,31 + 0,040 × 8,67 = 0,0531 + 0,3468 = 0,400 ✔.",
          "",
          "**Conclusión:** C₁ ≈ 5,31 µg/mL y C₂ ≈ 8,67 µg/mL. Las unidades salen de UA ÷ (UA por µg/mL) = µg/mL.",
        ].join("\n"),
      },
      {
        question:
          "¿Por qué es mala idea elegir dos longitudes de onda donde los espectros de los dos analitos son casi idénticos? Relaciónalo con el determinante D.",
        solution: [
          "**Razón.** Si los espectros son casi iguales en λ₁ y λ₂, las dos ecuaciones son casi la misma ecuación: k₁₁ ≈ k₁₂·c y k₂₁ ≈ k₂₂·c con la misma proporción c, y entonces **D = k₁₁k₂₂ − k₂₁k₁₂ ≈ 0**.",
          "",
          "**Consecuencia.** C₁ y C₂ se calculan dividiendo por D: un D casi cero **amplifica** cualquier error pequeño de absorbancia (ruido, burbujas, pipeteo) y los resultados salen muy dispersos o sin sentido.",
          "",
          "**Conclusión.** Escoge λ donde **cada analito domine en una de ellas**; así D es grande y el sistema es estable.",
        ].join("\n"),
      },
    ],
  },
];
