import type { SubjectContent } from "./_schema";

/**
 * Farmacología General (UNAL) — desde el programa oficial (Prof. Luis Fernando
 * Ospina Giraldo). Código 2015683. Sin componente de laboratorio.
 * Las fechas de parciales van en la app.
 */
export const fg: SubjectContent = {
  code: "FG",
  slug: "fg",
  name: "Farmacología General",
  credits: "3",
  professors: ["Luis Fernando Ospina Giraldo"],
  scheduleTheory: "Lunes 7:00–9:00, Miércoles 14:00–16:00",
  scheduleLab: "",
  totalClasses: 32,
  hasLab: false,
  descriptionSummary:
    "Conceptos **farmacológicos básicos** —farmacodinamia, farmacocinética y farmacología clínica— para el manejo y **uso racional** de las sustancias con actividad biológica, con aplicación a la farmacoterapia de los trastornos del **sistema nervioso central**.",
  objectiveGeneral:
    "Que el estudiante desarrolle habilidades para **aplicar de manera crítica y analítica** los conceptos farmacológicos básicos indispensables en el manejo y uso racional de las sustancias con actividad biológica, e integrarlos con las demás disciplinas del campo profesional.",
  objectivesSpecific: [
    "Comprender e integrar los aspectos farmacológicos básicos para **inferir y corregir interacciones** farmacológicas de importancia clínica.",
    "Caracterizar las sustancias según su **estructura química, sitio y mecanismo de acción y actividad farmacológica**, para participar en el diseño, la valoración biológica y la aplicación de nuevas moléculas activas.",
  ],

  // Curso teórico (clases magistrales, talleres, seminarios). Sin laboratorio.
  sections: ["modulos", "proyectos", "fechas", "glosario", "formulas", "bibliografia", "insumos", "prompt-ia"],

  modules: [
    {
      slug: "generalidades",
      title: "Módulo 1: Generalidades",
      description:
        "Contexto de la Farmacología en las Ciencias Biomédicas. **Definiciones y conceptos básicos** (fármaco, medicamento, principio activo, dosis). **Fuentes de información** sobre medicamentos. **Denominación** de los fármacos (DCI/INN, nombre químico, comercial).",
      exercises: [
        {
          question: [
            "**Verdadero o falso, con justificación.** En farmacología clínica, droga y estupefaciente son términos equivalentes.",
          ].join("\n"),
          solution: [
            "**Falso.**",
            "",
            "**Droga** es el término amplio: cualquier sustancia capaz de modificar la función de un organismo vivo (incluye venenos, tóxicos, sustancias recreativas y fármacos). **Estupefaciente** es una categoría legal/regulatoria: sustancias controladas por su potencial de abuso y dependencia (opioides, algunos psicoestimulantes). Un fármaco de uso terapéutico corriente (p. ej. paracetamol) es una droga pero no un estupefaciente; la morfina sí es ambas cosas.",
          ].join("\n"),
        },
        {
          question: [
            "**Definición — diferenciación.** Diferencie **fármaco**, **medicamento** y **principio activo**, y ordénelos de \"ingrediente\" a \"producto terminado\".",
          ].join("\n"),
          solution: [
            "**Principio activo**: la sustancia química pura responsable del efecto biológico (el \"ingrediente\").",
            "",
            "**Fármaco**: esa sustancia ya caracterizada por su actividad farmacológica — qué le hace al organismo y por qué mecanismo.",
            "",
            "**Medicamento**: el producto terminado listo para el paciente — principio activo + excipientes + forma farmacéutica (tableta, jarabe, inyectable) + información de uso + empaque.",
            "",
            "Orden: principio activo → fármaco → medicamento.",
          ].join("\n"),
        },
        {
          question: [
            "**Aplicación.** El paracetamol se puede nombrar de formas distintas según el contexto: *N-(4-hidroxifenil)acetamida*, *paracetamol/acetaminofén* y *Dolex®/Panadol®/Tylenol®*. Identifique cuál es el nombre químico, cuál la DCI (Denominación Común Internacional) y cuál el/los nombre(s) comercial(es), y explique para qué sirve cada uno.",
          ].join("\n"),
          solution: [
            "**Nombre químico** (*N-(4-hidroxifenil)acetamida*): describe la estructura según reglas IUPAC — preciso pero poco práctico para prescribir.",
            "",
            "**DCI/INN** (*paracetamol* / *acetaminofén*): nombre genérico único asignado por la OMS, igual en cualquier país y cualquier fabricante — es el que identifica sin ambigüedad al principio activo.",
            "",
            "**Nombres comerciales** (*Dolex®, Panadol®, Tylenol®*): marcas registradas por cada laboratorio para el mismo principio activo; pueden variar de un país a otro y cambian con el fabricante, aunque el fármaco sea idéntico.",
          ].join("\n"),
        },
        {
          question: [
            "**Opción múltiple.** Un ensayo clínico fase III publicado en una revista indexada, un vademécum farmacéutico y una revisión sistemática que resume 40 estudios sobre un mismo fármaco son, respectivamente, ejemplos de fuentes de información:",
            "",
            "A) Terciaria, primaria, secundaria",
            "B) Primaria, terciaria, secundaria",
            "C) Secundaria, primaria, terciaria",
            "D) Primaria, secundaria, terciaria",
          ].join("\n"),
          solution: [
            "**Respuesta: B.**",
            "",
            "**Fuente primaria**: el artículo original que reporta datos de primera mano (el ensayo clínico). **Fuente terciaria**: compendios de referencia rápida que ya sintetizan el conocimiento establecido (vademécum, formularios, libros de texto). **Fuente secundaria**: analiza y sintetiza varias fuentes primarias (revisión sistemática, metaanálisis) — está a medio camino entre el dato crudo y el resumen de referencia.",
          ].join("\n"),
        },
      ],
      chapter: [
        "#### Por qué empezar por las palabras",
        "",
        "La farmacología es una ciencia de cruce: se apoya en química, fisiología, bioquímica, patología, genética y estadística a la vez. Antes de estudiar cómo actúa cualquier sustancia sobre el organismo, hace falta fijar el vocabulario que vas a usar el resto de la carrera — porque en el lenguaje cotidiano \"droga\", \"medicamento\" y \"fármaco\" se usan como sinónimos, y en farmacología clínica **no lo son**. Esa es, de hecho, la primera trampa clásica de examen en este curso.",
        "",
        "#### Principio activo, fármaco y medicamento: del ingrediente al producto terminado",
        "",
        "> Analogía: piensa en la diferencia entre \"ingrediente\", \"receta caracterizada\" y \"plato servido\". El **principio activo** es el ingrediente puro (paracetamol en polvo, sin nada más). El **fármaco** es ese ingrediente ya estudiado y caracterizado por su actividad biológica: qué le hace al organismo, por qué mecanismo, a qué dosis. El **medicamento** es el \"plato servido\": el principio activo combinado con excipientes, presentado en una forma farmacéutica concreta (tableta, jarabe, inyectable), con su información de uso y su empaque — listo para que lo reciba un paciente.",
        "",
        "La **dosis** es la cantidad de fármaco administrada de una vez (o por unidad de tiempo) para producir un efecto. Todavía no hablamos aquí de *cuánto* efecto produce cada dosis — eso, la curva dosis-respuesta, es el corazón del Módulo 2 — pero conviene tener clara la definición desde ahora: dosis es una cantidad, no un efecto.",
        "",
        "#### Droga, fármaco y estupefaciente: tres palabras que no son sinónimas",
        "",
        "**Droga**, en el sentido farmacológico amplio, es cualquier sustancia capaz de modificar la función de un organismo vivo — un concepto tan amplio que incluye tanto a los fármacos terapéuticos como a los venenos, los tóxicos ambientales y las sustancias de uso recreativo. **Fármaco** es más específico: una droga que se usa con intención terapéutica, diagnóstica o preventiva, y de la que se conoce su mecanismo de acción. **Estupefaciente**, en cambio, no es una categoría farmacológica sino **legal y regulatoria**: sustancias sometidas a control especial por su potencial de abuso y dependencia (la mayoría de los opioides, por ejemplo).",
        "",
        "> Analogía: \"droga\" es como \"vehículo\" — una categoría enorme que incluye bicicletas, camiones y aviones. \"Fármaco\" es como \"vehículo con conductor autorizado y ruta declarada\" — un uso específico y caracterizado de esa categoría amplia. \"Estupefaciente\" es como \"vehículo de carga peligrosa\": una etiqueta legal que exige controles especiales, independientemente de si el vehículo (la droga) se usa bien o mal. Por eso la morfina es, a la vez, una droga, un fármaco (analgésico opioide bien caracterizado) y un estupefaciente (sometido a control legal estricto) — pero el paracetamol es droga y fármaco, sin ser estupefaciente.",
        "",
        "#### La denominación de los fármacos: tres nombres para la misma molécula",
        "",
        "Cualquier fármaco puede nombrarse de al menos tres formas distintas, y confundirlas genera errores de prescripción y de comunicación:",
        "",
        "* **Nombre químico** — describe la estructura molecular según las reglas de nomenclatura de la IUPAC. Es exacto pero impráctico para el uso clínico diario.",
        "* **DCI / INN** (Denominación Común Internacional / *International Nonproprietary Name*) — el nombre genérico único que asigna la Organización Mundial de la Salud a cada principio activo. Es el mismo en cualquier país, para cualquier fabricante.",
        "* **Nombre comercial (marca)** — el nombre registrado por cada laboratorio para su producto. Puede variar de un país a otro, cambia con el fabricante y suele estar protegido por patente durante un tiempo.",
        "",
        "> Analogía: piensa en el documento de identidad de una persona. La **DCI** es como el número de cédula: único, universal, no cambia sin importar quién te llame. El **nombre comercial** es como los distintos apodos que te pueden poner en diferentes círculos — la misma persona (molécula) puede tener varios \"apodos\" (Dolex®, Panadol®, Tylenol®) según quién la fabrique y venda, pero la cédula (DCI: paracetamol) sigue siendo una sola.",
        "",
        "#### Fuentes de información sobre medicamentos",
        "",
        "No toda la información disponible sobre un fármaco tiene el mismo nivel de evidencia ni el mismo propósito. Es útil clasificarla en tres niveles:",
        "",
        "* **Fuentes primarias** — el reporte original de primera mano: el artículo de un ensayo clínico, un estudio experimental publicado en una revista indexada.",
        "* **Fuentes secundarias** — analizan y sintetizan varias fuentes primarias: revisiones sistemáticas, metaanálisis, índices bibliográficos.",
        "* **Fuentes terciarias** — compendios de referencia rápida que ya destilan el conocimiento establecido: vademécums, formularios terapéuticos, libros de texto, la información de prescripción oficial (inserto/prospecto).",
        "",
        "> Analogía periodística: la fuente primaria es el reportero que estuvo en el lugar de los hechos y escribió la nota original. La fuente secundaria es el artículo de análisis que cruza varias notas originales para explicar una tendencia. La fuente terciaria es la entrada de una enciclopedia: rápida de consultar, pero ya varios pasos alejada del hecho crudo.",
        "",
        "Conviene distinguir, además, entre información **independiente** (guías clínicas, formularios oficiales, literatura revisada por pares) e información **promocional** de la industria farmacéutica: esta última no es necesariamente falsa, pero está diseñada para vender, no para informar de manera neutral, y suele resaltar beneficios minimizando riesgos.",
        "",
        "#### El lugar de la farmacología entre las ciencias biomédicas",
        "",
        "La farmacología no es una disciplina aislada: es el puente entre las ciencias básicas (química, bioquímica, fisiología) y la aplicación clínica. De ahí se derivan sus grandes ramas, que vas a recorrer una por una en los módulos siguientes de este curso:",
        "",
        "* **Farmacodinamia** — qué le hace el fármaco al organismo (mecanismo de acción, receptores, dosis-respuesta). Módulo 2.",
        "* **Farmacocinética** — qué le hace el organismo al fármaco (absorción, distribución, metabolismo, excreción). Módulo 3.",
        "* **Farmacología clínica** — variabilidad de la respuesta en personas reales, reacciones adversas, farmacovigilancia. Módulo 4.",
        "* **Investigación farmacológica** — cómo se descubre y valida un fármaco antes y durante su uso en humanos, desde el laboratorio hasta el ensayo clínico. Módulo 5.",
        "* **Farmacología del sistema nervioso central** — la aplicación concreta de todo lo anterior a un sistema particular, con su propia farmacoterapia. Módulos 6 y 7.",
        "",
        "#### En resumen",
        "",
        "* **Principio activo → fármaco → medicamento**: del ingrediente puro al producto terminado.",
        "* **Droga** (amplio) ≠ **fármaco** (uso terapéutico caracterizado) ≠ **estupefaciente** (categoría legal por potencial de abuso).",
        "* Todo fármaco tiene tres nombres posibles: **químico** (estructura), **DCI/INN** (genérico universal) y **comercial** (marca del fabricante).",
        "* Las fuentes de información se ordenan por distancia al dato original: **primaria → secundaria → terciaria**, y conviene distinguir la información independiente de la promocional.",
        "* La farmacología se organiza en ramas que se recorren en orden en este curso: farmacodinamia, farmacocinética, farmacología clínica, investigación farmacológica, y su aplicación al sistema nervioso central.",
      ].join("\n"),
    },
    {
      slug: "farmacodinamia",
      title: "Módulo 2: Farmacodinamia",
      description:
        "Tipos de acción farmacológica. **Curvas dosis-respuesta** (concentración–efecto), potencia y eficacia. Dianas y mecanismos: **familias de receptores**, transducción de señales y **segundos mensajeros**, regulación de receptores. Mecanismos inespecíficos. **Interacciones** farmacológicas: incompatibilidades, interacciones farmacocinéticas y farmacodinámicas (sinergismo y antagonismo).",
      exercises: [
        {
          question: [
            "**Relación de términos.** Relacione cada mecanismo con el fármaco/agente que mejor lo ejemplifica:",
            "",
            "**Términos:** 1. Acción \"scavenger\" (barredora de radicales) · 2. Anestésico general · 3. Anestésico local · 4. Antiácido neutralizante · 5. Antídoto quelante · 6. Enzima antioxidante · 7. Inhibidor de fosfodiesterasa 5 · 8. Laxante osmótico · 9. Terapia de sustitución",
            "",
            "**Agentes:** a. Vitamina E (alfa-tocoferol) · b. Perturbación de la membrana lipídica · c. Bloqueo de canales de sodio dependientes de voltaje · d. NaHCO₃ · e. EDTA · f. Catalasa · g. Sildenafilo · h. Lactulosa · i. Insulina recombinante",
          ].join("\n"),
          solution: [
            "1-a (vitamina E), 2-b (perturbación lipídica — teoría de Meyer-Overton para anestésicos inhalados), 3-c (bloqueo de canales de sodio — **no** el complejo GABA/Cl⁻, que es el blanco de los anestésicos *generales* IV, benzodiazepinas y barbitúricos), 4-d (NaHCO₃ neutraliza directamente el ácido gástrico), 5-e (EDTA quela cationes divalentes como plomo), 6-f (catalasa descompone peróxido de hidrógeno), 7-g (sildenafilo inhibe la degradación de GMPc), 8-h (lactulosa retiene agua en el colon por ósmosis), 9-i (insulina recombinante reemplaza la hormona endógena faltante).",
            "",
            "**Nota importante:** en bancos de términos de este estilo es fácil que \"anestésico local\" quede emparejado por descarte con \"complejo GABA/Cl⁻\" — es un error frecuente. Los anestésicos **locales** (lidocaína y similares) bloquean canales de sodio; el complejo GABA/Cl⁻ es el blanco de los anestésicos **generales** intravenosos, no de los locales.",
          ].join("\n"),
        },
        {
          question: [
            "**Comente.** Mencione cuatro clases de fármacos cuyo efecto NO se debe a una interacción fármaco-receptor específica: explique brevemente el mecanismo de cada una y en qué situación clínica es aprovechable.",
          ].join("\n"),
          solution: [
            "**1. Neutralización ácido-base** — antiácidos como el NaHCO₃: neutralizan químicamente el ácido gástrico, útiles en dispepsia/reflujo.",
            "",
            "**2. Quelación** — EDTA y agentes similares: forman complejos estables con cationes metálicos divalentes; útiles como antídoto en intoxicación por metales pesados (plomo).",
            "",
            "**3. Efecto osmótico** — manitol (reduce presión intracraneal en edema cerebral, extrayendo agua del tejido por gradiente osmótico) y lactulosa (laxante, retiene agua en el colon).",
            "",
            "**4. Perturbación de membranas lipídicas** — anestésicos generales inhalados: se disuelven en la bicapa lipídica de las neuronas y alteran su función eléctrica sin necesitar un receptor específico (teoría de Meyer-Overton).",
            "",
            "*(Nota: furosemida no pertenece a este grupo aunque a veces se le clasifica erróneamente como osmótica — es un diurético que inhibe específicamente el cotransportador Na⁺-K⁺-2Cl⁻, un mecanismo fármaco-transportador, no un mecanismo inespecífico.)*",
          ].join("\n"),
        },
        {
          question: [
            "**Comente el significado de:** actividad intrínseca, eficacia, potencia, agonismo parcial / antagonismo parcial, segundo mensajero.",
          ].join("\n"),
          solution: [
            "**Actividad intrínseca**: capacidad de un fármaco, ya unido al receptor, de activarlo y producir respuesta. Va de 0 (antagonista puro) a 1 (agonista total).",
            "",
            "**Eficacia**: el efecto máximo que puede producir un fármaco — el \"techo\" de su curva dosis-respuesta.",
            "",
            "**Potencia**: cuánta dosis hace falta para lograr un efecto dado; se compara por la DE₅₀ (a menor DE₅₀, mayor potencia). Es independiente de la eficacia: un fármaco puede ser muy potente (poca dosis) y poco eficaz (techo bajo), o al revés.",
            "",
            "**Agonismo parcial / antagonismo parcial**: un agonista parcial tiene actividad intrínseca entre 0 y 1 — incluso ocupando el 100 % de los receptores no alcanza el efecto máximo de un agonista total. Frente a un agonista total presente en el mismo sistema, compite por el receptor y **reduce** el efecto máximo posible: por eso, en ese contexto, también se comporta como un antagonista (parcial).",
            "",
            "**Segundo mensajero**: molécula intracelular (AMPc, GMPc, IP₃, DAG, Ca²⁺) que amplifica y propaga la señal iniciada por un receptor de membrana, traduciéndola en una respuesta celular concreta.",
          ].join("\n"),
        },
        {
          question: [
            "**Las siguientes frases sobre curvas dosis-respuesta son ciertas, EXCEPTO:**",
            "",
            "a) La representación gráfica \"sigmoide\" se logra cuando las dosis se expresan en escala logarítmica.",
            "b) El parámetro DE₅₀ es un indicativo de la potencia de un fármaco.",
            "c) El índice terapéutico relaciona las dosis tóxicas con las dosis efectivas para un efecto farmacológico dado.",
            "d) Con una dosis puntual, los individuos tratados dan respuestas de diferente intensidad.",
            "e) En una curva dosis-respuesta, al doblar la dosis siempre se dobla el efecto.",
          ].join("\n"),
          solution: [
            "**Falsa: e.**",
            "",
            "La relación dosis-respuesta es **sigmoidea**, no lineal: cerca del techo (eficacia máxima) el sistema se satura y doblar la dosis apenas cambia el efecto. Las demás afirmaciones son correctas: (a) la escala logarítmica linealiza la parte central de la sigmoide; (b) la DE₅₀ indica potencia (menor DE₅₀ = mayor potencia); (c) el índice terapéutico compara dosis tóxica con dosis eficaz; (d) la variabilidad interindividual hace que una misma dosis produzca distintas intensidades de respuesta entre personas.",
          ].join("\n"),
        },
        {
          question: [
            "**Elija la respuesta correcta.** Los agonistas adrenérgicos beta2 se unen a receptores que son:",
            "",
            "A) Ácidos nucleicos",
            "B) Siete proteínas de transmembrana",
            "C) Canales iónicos activados por ligando",
            "D) Lípidos como el DAG",
          ].join("\n"),
          solution: [
            "**Respuesta: B.**",
            "",
            "Los receptores beta-adrenérgicos son receptores acoplados a proteína G (GPCR), con estructura de siete dominios transmembrana (7TM). No son canales iónicos, ni ácidos nucleicos, ni lípidos — el DAG es, de hecho, un segundo mensajero producido río abajo de otro tipo de GPCR (los acoplados a Gq), no un receptor.",
          ].join("\n"),
        },
      ],
      chapter: [
        "#### El problema que resuelve la farmacodinamia",
        "",
        "El Módulo 1 fijó el vocabulario; este módulo empieza a responder la primera pregunta realmente farmacológica: **¿qué le hace el fármaco al organismo, y por qué mecanismo?** Esa es, precisamente, la definición de farmacodinamia — en contraste con la farmacocinética (Módulo 3), que pregunta lo inverso: **qué le hace el organismo al fármaco**. Piensa en esta distinción como la diferencia entre estudiar el efecto de un actor sobre el escenario (farmacodinamia) y estudiar cómo el escenario transporta, transforma y finalmente expulsa a ese actor (farmacocinética). Ambas preguntas son necesarias para entender por qué un medicamento funciona, cuánto tarda y cuánto dura.",
        "",
        "#### Dos grandes caminos: mecanismos inespecíficos vs. interacción fármaco-receptor",
        "",
        "No todos los fármacos actúan de la misma manera. Algunos producen su efecto sin necesitar un receptor biológico específico — basta su presencia física o su reactividad química. Otros dependen enteramente de reconocer y unirse a una molécula diana concreta del organismo: el receptor.",
        "",
        "> Analogía: imagina dos formas de abrir una puerta. La primera es empujarla con suficiente fuerza física — no importa qué puerta sea, cualquier empujón suficientemente fuerte la abre (mecanismo **inespecífico**). La segunda es usar una llave hecha a la medida de esa cerradura exacta — solo esa llave, con esa forma precisa, encaja y gira el mecanismo (interacción **fármaco-receptor**, específica).",
        "",
        "#### Mecanismos inespecíficos: cuando no hace falta una llave",
        "",
        "Estos mecanismos dependen de propiedades fisicoquímicas simples — no de un reconocimiento molecular fino — y por eso suelen ser rápidos, predecibles y poco sensibles a mutaciones puntuales del organismo:",
        "",
        "* **Neutralización ácido-base** — un antiácido como el NaHCO₃ simplemente reacciona químicamente con el ácido gástrico y sube el pH. Es un antiácido *neutralizante*; no actúa por \"citoprotección\" (ese es un mecanismo distinto, mediado por prostaglandinas, típico de otros fármacos como el misoprostol).",
        "* **Quelación** — agentes como el EDTA forman complejos estables con cationes metálicos (plomo, entre otros divalentes), \"secuestrándolos\" para facilitar su excreción. Es la base del antidotismo en intoxicaciones por metales pesados.",
        "* **Efecto osmótico** — el manitol, al ser una molécula osmóticamente activa que no se reabsorbe fácilmente, arrastra agua consigo: se usa para reducir la presión intracraneal en edema cerebral. La lactulosa, por el mismo principio en el colon, retiene agua y actúa como laxante.",
        "* **Perturbación de membranas lipídicas** — los anestésicos generales inhalados son moléculas muy liposolubles que se disuelven en la bicapa lipídica de las neuronas y alteran su función eléctrica de forma inespecífica (teoría de Meyer-Overton: la potencia anestésica correlaciona con la liposolubilidad, no con la afinidad por un receptor concreto).",
        "* **Acción \"scavenger\" (barredora de radicales libres)** — antioxidantes como la vitamina E \"atrapan\" especies reactivas de oxígeno antes de que dañen membranas y macromoléculas; es un mecanismo de reactividad química directa, reforzado por enzimas antioxidantes endógenas como la catalasa.",
        "* **Terapia de sustitución** — cuando el organismo no produce una molécula endógena (insulina en diabetes tipo 1), administrar esa misma molécula (insulina recombinante) no es, estrictamente, activar un mecanismo *nuevo*: es reemplazar lo que falta.",
        "",
        "Un error frecuente aquí es clasificar cualquier diurético como \"osmótico\": la **furosemida**, por ejemplo, no lo es — inhibe de forma específica el cotransportador Na⁺-K⁺-2Cl⁻ (NKCC2) en el asa ascendente de Henle, un mecanismo fármaco-transportador tan específico como cualquier interacción fármaco-receptor. El verdadero diurético osmótico de referencia es el manitol.",
        "",
        "#### Mecanismos específicos: la interacción fármaco-receptor",
        "",
        "La mayoría de los fármacos modernos, sin embargo, sí dependen de una \"llave\" molecular precisa: el **receptor**, una proteína (o, más raramente, otra macromolécula) capaz de reconocer selectivamente a un ligando —endógeno o farmacológico— e iniciar una respuesta biológica. Los receptores farmacológicos se agrupan en cuatro grandes familias, que difieren sobre todo en **qué tan rápido** transmiten la señal:",
        "",
        "* **Canales iónicos (receptores ionotrópicos)** — el propio receptor ES el canal; al unirse el ligando, se abre y deja pasar iones (Na⁺, Cl⁻, Ca²⁺). Respuesta en milisegundos. Ejemplo: el complejo GABA/Cl⁻.",
        "* **Receptores acoplados a proteína G (GPCR, \"7TM\")** — siete dominios transmembrana; al activarse, acoplan y activan una proteína G intracelular (Gs, Gi, Gq), que a su vez modula enzimas o canales. Respuesta en segundos. Ejemplo: receptores adrenérgicos beta2.",
        "* **Receptores con actividad enzimática intrínseca** — típicamente tirosina cinasas; la unión del ligando dispara directamente una cascada enzimática (fosforilación de proteínas). Respuesta en minutos-horas. Ejemplo: receptor de insulina.",
        "* **Receptores intracelulares/nucleares** — el receptor está en el citosol o el núcleo; el ligando (típicamente lipofílico, como una hormona esteroidea) lo atraviesa la membrana y se une, y el complejo regula directamente la transcripción de genes. Respuesta en horas-días. Ejemplo: receptor de glucocorticoides, que es citosólico y se transloca al núcleo tras unirse a su ligando.",
        "",
        "> Analogía: piensa en estas cuatro familias como cuatro formas distintas de \"tocar el timbre\" de una casa. El canal iónico es una puerta que se abre de inmediato al girar la llave — instantáneo. El GPCR es un timbre que activa una campana interna (la proteína G) que, a su vez, pone en marcha otros mecanismos dentro de la casa — hay un paso intermedio, pero sigue siendo rápido. El receptor enzimático es como activar una fábrica interna que empieza a producir cosas — toma más tiempo. El receptor nuclear es como dejar un mensaje directamente con el dueño de la casa, que decide reorganizar los planos del edificio (la expresión génica) — el más lento, pero el de efecto más duradero.",
        "",
        "**Importante:** la proteína G (p. ej. Gs) **no es** el receptor 7TM — es su transductor intracelular. El receptor 7TM es quien reconoce al ligando en la membrana; la proteína G es la pieza que ese receptor activa por dentro.",
        "",
        "#### Los segundos mensajeros: amplificando la señal hacia adentro de la célula",
        "",
        "Una vez activada la proteína G, la señal se propaga mediante **segundos mensajeros** — moléculas intracelulares que amplifican la señal original (una sola molécula de ligando puede terminar generando miles de moléculas de segundo mensajero) y la traducen en respuestas celulares concretas:",
        "",
        "* **AMPc** — generado por la adenilato ciclasa (activada por Gs, inhibida por Gi).",
        "* **GMPc** — generado por la guanilato ciclasa; el sildenafilo actúa inhibiendo la enzima que lo degrada (fosfodiesterasa 5), prolongando su efecto vasodilatador.",
        "* **IP₃ y DAG** — generados por la fosfolipasa C (activada por Gq); el IP₃ libera Ca²⁺ desde depósitos intracelulares, el DAG activa la proteína cinasa C.",
        "* **Ca²⁺ intracelular** — funciona como segundo mensajero por sí mismo, liberado tanto por IP₃ como por canales de voltaje.",
        "",
        "#### Agonismo, antagonismo y el techo de la respuesta",
        "",
        "Que un fármaco se una a un receptor no garantiza que lo active. La **actividad intrínseca** describe justamente eso: la capacidad de activar el receptor una vez unido, en una escala de 0 (no lo activa en absoluto) a 1 (lo activa al máximo posible). Un **agonista total** tiene actividad intrínseca = 1. Un **antagonista puro** se une pero no activa nada (actividad intrínseca = 0) — su único efecto es bloquear el sitio para que el agonista endógeno o farmacológico no pueda actuar. Un **agonista parcial** queda en medio: activa el receptor, pero incluso ocupando el 100 % de los receptores disponibles nunca alcanza el efecto máximo de un agonista total. Por eso, si se administra junto con un agonista total, el agonista parcial compite por el mismo sitio y termina *reduciendo* el efecto máximo alcanzable — comportándose, en ese contexto específico, como un antagonista parcial.",
        "",
        "De aquí surgen dos parámetros que conviene no confundir: la **eficacia** es el efecto máximo que un fármaco puede producir — el \"techo\" de su curva dosis-respuesta. La **potencia** es cuánta dosis hace falta para llegar a un efecto dado — se compara con la DE₅₀ (dosis efectiva 50): a menor DE₅₀, mayor potencia. Un fármaco puede ser muy potente pero poco eficaz, o viceversa: son ejes independientes.",
        "",
        "No todo antagonismo implica competir por el mismo receptor. El **antagonismo fisiológico** (o funcional) ocurre cuando dos sustancias actúan sobre receptores *distintos*, produciendo efectos *opuestos* que se cancelan mutuamente a nivel del sistema, no de la molécula. El ejemplo clásico es la adrenalina en el shock anafiláctico: no bloquea los receptores de histamina, sino que activa receptores adrenérgicos que producen el efecto fisiológico contrario (vasoconstricción, broncodilatación). Por el mismo principio, cuando la cafeína (antagonista de receptores de adenosina, con efecto estimulante) contrarresta la depresión del sistema nervioso central causada por el etanol (que potencia el GABA-A e inhibe al NMDA), **no** están compitiendo por el mismo receptor — es, de nuevo, antagonismo fisiológico entre dos sistemas de neurotransmisión distintos con efectos opuestos.",
        "",
        "#### La curva dosis-respuesta: potencia, eficacia y el límite de la sigmoide",
        "",
        "Si administras dosis crecientes de un fármaco y mides el efecto, obtienes una **curva dosis-respuesta**. Cuando la dosis se expresa en escala logarítmica, esa curva adopta una forma característica en \"S\" (sigmoide): al principio el efecto crece poco (dosis subumbral), luego crece casi linealmente en la zona media, y finalmente se **aplana** cerca del techo — el sistema se satura porque ya no quedan receptores libres para ocupar. Esta es la razón por la que, cerca del techo, **doblar la dosis no dobla el efecto**: es una de las trampas de examen más repetidas en este tema.",
        "",
        "> Analogía: piensa en llenar una sala con sillas numeradas y personas entrando una por una. Al principio, cada persona nueva que entra (\"dosis\") aumenta claramente la ocupación (\"efecto\"). Pero cuando la sala está casi llena, meter el doble de personas nuevas no duplica la ocupación — simplemente no hay más sillas libres. El \"techo\" de la sala es la eficacia máxima del sistema.",
        "",
        "Existen además dos formas de medir la respuesta: la **respuesta graduada**, continua y medible en un mismo individuo (p. ej. milímetros de mercurio de presión arterial, que sube o baja de forma gradual), y la **respuesta cuantal**, todo-o-nada, evaluada típicamente en una población a una dosis dada (el efecto está presente o ausente — por ejemplo, si una benzodiazepina logra o no el efecto ansiolítico esperado en cada persona de un grupo, a una dosis fija).",
        "",
        "El **índice terapéutico** (que ya viste como fórmula en el glosario: IT = DL₅₀/DE₅₀) resume en un solo número qué tan separadas están la dosis que cura y la dosis que daña — cuanto mayor, más margen de seguridad tiene el fármaco.",
        "",
        "#### Regulación de receptores: el sistema se adapta",
        "",
        "Los receptores no son estructuras fijas e inmutables: su número y su sensibilidad cambian con la exposición repetida a un ligando. La exposición prolongada a un agonista puede producir **desensibilización** o **regulación a la baja** (*down-regulation*) — menos receptores disponibles o receptores menos sensibles, la base de la tolerancia farmacológica. Al contrario, el bloqueo prolongado con un antagonista puede producir **regulación al alza** (*up-regulation*) — el organismo \"compensa\" fabricando más receptores, lo que explica por qué suspender abruptamente ciertos fármacos (betabloqueadores, por ejemplo) puede producir un efecto de rebote exagerado: hay más receptores disponibles de los que había antes de empezar el tratamiento.",
        "",
        "#### Interacciones farmacológicas",
        "",
        "Cuando dos o más fármacos coinciden en un mismo organismo (o incluso en la misma jeringa), pueden interactuar en distintos niveles:",
        "",
        "* **Incompatibilidades** — interacciones puramente fisicoquímicas, fuera del organismo (p. ej. dos fármacos que precipitan al mezclarse en la misma solución IV). No son farmacodinamia ni farmacocinética propiamente dichas: ocurren antes de que el fármaco entre al cuerpo.",
        "* **Interacciones farmacocinéticas** — un fármaco altera la absorción, distribución, metabolismo o excreción de otro (verás esto en profundidad en el Módulo 3 — inducción/inhibición enzimática, competencia por unión a proteínas, etc.).",
        "* **Interacciones farmacodinámicas** — ocurren en el sitio de acción: **sinergismo** (el efecto combinado supera la simple suma de los efectos individuales — potenciación) o **antagonismo** (un fármaco reduce o anula el efecto de otro, ya sea compitiendo por el mismo receptor o por antagonismo fisiológico en receptores distintos, como en los ejemplos de la adrenalina y la cafeína vistos arriba).",
        "",
        "#### En resumen",
        "",
        "* La farmacodinamia estudia **qué le hace el fármaco al organismo**; la farmacocinética (Módulo 3) estudia lo inverso.",
        "* Hay dos grandes caminos de acción: **mecanismos inespecíficos** (fisicoquímicos: neutralización, quelación, ósmosis, perturbación lipídica, scavengers, sustitución) e **interacción fármaco-receptor** (específica, mediada por una de cuatro familias de receptores: canales iónicos, GPCR/7TM, enzimáticos, nucleares).",
        "* Los GPCR transducen su señal a través de **proteínas G** y **segundos mensajeros** (AMPc, GMPc, IP₃/DAG, Ca²⁺) — la proteína G no es el receptor, es su transductor.",
        "* **Actividad intrínseca, eficacia y potencia** son tres ejes distintos que describen a un fármaco frente a su receptor; el **agonismo parcial** y el **antagonismo fisiológico** (receptores distintos, efectos opuestos) son las trampas conceptuales más frecuentes.",
        "* La curva dosis-respuesta es **sigmoide** en escala logarítmica: cerca del techo, doblar la dosis no dobla el efecto.",
        "* Los receptores se regulan con el uso: la exposición prolongada puede producir tolerancia (*down-regulation*) o, al suspender un antagonista, un rebote por *up-regulation*.",
        "* Las interacciones farmacológicas pueden ser incompatibilidades, farmacocinéticas o farmacodinámicas (sinergismo/antagonismo) — el Módulo 3 retoma justo el segundo tipo en profundidad.",
      ].join("\n"),
    },
    {
      slug: "farmacocinetica-adme",
      title: "Módulo 3: Farmacocinética — procesos ADME (absorción, distribución, metabolismo y excreción)",
      description:
        "Formas farmacéuticas y **vías de administración**. Procesos de **absorción y distribución** (barreras, unión a proteínas, volumen de distribución). Procesos de **biotransformación** (fases I y II, citocromo P450) y **eliminación** (renal, biliar). Factores que afectan los procesos de absorción, distribución, metabolismo y excreción (ADME).",
      exercises: [
        {
          question: [
            "**Verdadero o falso, con justificación.** Los fármacos en su forma disociada (ionizada) son más polares y por eso se absorben más fácilmente, ya que el plasma es un fluido esencialmente acuoso.",
          ].join("\n"),
          solution: [
            "**Falso.**",
            "",
            "La forma disociada (ionizada) es efectivamente más polar/hidrosoluble, pero justo por eso se absorbe **peor**: solo la forma no ionizada (liposoluble) atraviesa con facilidad la bicapa lipídica de las membranas por difusión pasiva. Esta es la base de la hipótesis de partición de pH: un ácido débil se absorbe mejor en un medio ácido (donde predomina su forma no ionizada) y una base débil se absorbe mejor en un medio básico.",
          ].join("\n"),
        },
        {
          question: [
            "**Verdadero o falso, con justificación.** La aspirina es una base débil cuya absorción se ve favorecida por el pH gástrico.",
          ].join("\n"),
          solution: [
            "**Falso.**",
            "",
            "La aspirina es un **ácido débil** (constante de disociación ácida, pKa, de aproximadamente 3.5), no una base débil. Precisamente por ser un ácido débil, en el ambiente ácido del estómago predomina su forma no ionizada (liposoluble), lo que sí favorece su absorción gástrica — pero la premisa de \"base débil\" del enunciado es incorrecta.",
          ].join("\n"),
        },
        {
          question: [
            "**Cálculo — volumen de distribución.** Se administran 500 mg de un fármaco por vía intravenosa y, extrapolando a tiempo cero, la concentración plasmática es de 10 mg/L. Calcule el volumen de distribución (Vd) y explique qué indica un valor tan alto frente a uno típico del volumen plasmático (~5 L).",
          ].join("\n"),
          solution: [
            "#### Cálculo",
            "Vd = Dosis / C₀ = 500 mg / 10 mg/L = **50 L**",
            "",
            "#### Interpretación",
            "El volumen de distribución es un volumen **aparente**, no un compartimento fisiológico real. 50 L es varias veces el volumen plasmático (~5 L) y también supera el agua corporal total (~40 L): indica que el fármaco no se queda en el plasma, sino que se distribuye ampliamente hacia los tejidos (alta liposolubilidad o baja unión a proteínas plasmáticas). Un Vd cercano al volumen plasmático, en cambio, indicaría un fármaco muy unido a proteínas o poco capaz de salir del compartimento vascular (como la warfarina).",
          ].join("\n"),
        },
        {
          question: [
            "**Verdadero o falso, con justificación.** Los complejos fármaco-proteínas plasmáticas son útiles para la eliminación de los fármacos.",
          ].join("\n"),
          solution: [
            "**Falso.**",
            "",
            "Solo el fármaco **libre** (no unido a proteínas) se filtra en el glomérulo renal o queda disponible para ser biotransformado. La unión a proteínas plasmáticas actúa como un reservorio que **retrasa** la eliminación, no que la facilita — por eso los fármacos muy unidos a proteínas (como la warfarina) suelen tener una vida media más prolongada y un volumen de distribución bajo.",
          ].join("\n"),
        },
        {
          question: [
            "**Definición — diferenciación.** Diferencie la fase I y la fase II de la biotransformación, y explique por qué no toda biotransformación produce metabolitos inactivos.",
          ].join("\n"),
          solution: [
            "**Fase I** (funcionalización): reacciones de oxidación (principalmente por el sistema enzimático del citocromo P450, un conjunto de enzimas oxidativas hepáticas), reducción o hidrólisis, que suelen exponer o crear un grupo funcional reactivo en la molécula.",
            "",
            "**Fase II** (conjugación): une el fármaco (o su metabolito de fase I) con un sustrato endógeno — ácido glucurónico, sulfato, glutatión — aumentando su hidrosolubilidad para facilitar la excreción renal o biliar.",
            "",
            "No siempre el resultado es un metabolito inactivo: puede tratarse de un **profármaco** que se activa al biotransformarse (codeína → morfina), o generarse un **metabolito tóxico** (paracetamol → N-acetil-p-benzoquinona imina, abreviada NAPQI, hepatotóxica si se agota el glutatión disponible).",
          ].join("\n"),
        },
        {
          question: [
            "**Aplicación.** Explique por qué el etanol se usa como antídoto en la intoxicación por metanol, y por qué el fenobarbital puede alterar la eficacia de otros fármacos administrados junto con él.",
          ].join("\n"),
          solution: [
            "**Etanol y metanol**: ambos son sustratos de la misma enzima, la alcohol-deshidrogenasa, pero el etanol tiene mayor afinidad por ella. Al administrar etanol se satura competitivamente la enzima, bloqueando la conversión del metanol en sus metabolitos tóxicos (formaldehído, ácido fórmico) mientras el organismo elimina el metanol sin transformar.",
            "",
            "**Fenobarbital**: es un inductor enzimático amplio — aumenta la cantidad y actividad de las enzimas del citocromo P450 (y de algunas enzimas de conjugación de fase II). Al coadministrarse con otro fármaco metabolizado por esas mismas enzimas, acelera su biotransformación, reduce su concentración plasmática y, en consecuencia, puede disminuir su efecto terapéutico.",
          ].join("\n"),
        },
        {
          question: [
            "**Opción múltiple — atrapamiento iónico.** En una intoxicación por barbitúricos (ácidos débiles), ¿qué estrategia favorece su eliminación renal?",
            "",
            "A) Acidificar la orina, para que el fármaco se ionice y se reabsorba",
            "B) Alcalinizar la orina, para que el fármaco se ionice y quede atrapado en la orina",
            "C) Alcalinizar la orina, para que el fármaco se desionice y se reabsorba",
            "D) El pH urinario no afecta la eliminación de ácidos ni bases débiles",
          ].join("\n"),
          solution: [
            "**Respuesta: B.**",
            "",
            "Al alcalinizar la orina (p. ej. con bicarbonato), un ácido débil como el barbitúrico se ioniza más — la forma ionizada no puede difundir de vuelta a través del epitelio tubular hacia la sangre, así que queda \"atrapada\" en la orina y se elimina. El mismo principio de atrapamiento iónico se usa con la alcalinización urinaria en la intoxicación por salicilatos (ácidos débiles). Para una **base** débil, el principio se invierte: se favorece su eliminación **acidificando** la orina.",
          ].join("\n"),
        },
      ],
      chapter: [
        "#### El problema que resuelve la farmacocinética",
        "",
        "El Módulo 2 respondió qué le hace el fármaco al organismo. Este módulo responde la pregunta inversa: **¿qué le hace el organismo al fármaco?** A ese recorrido completo — desde que el fármaco entra al cuerpo hasta que sale de él — se le conoce por la sigla ADME: **A**bsorción, **D**istribución, **M**etabolismo (biotransformación) y **E**xcreción. Cada una de esas cuatro etapas determina cuánto fármaco llega a su sitio de acción, qué tan rápido y cuánto tiempo permanece ahí — es decir, determina la intensidad y la duración del efecto que estudiaste en el módulo anterior.",
        "",
        "> Analogía general del módulo: piensa en un fármaco como un viajero que entra a un país extranjero (el organismo). Primero debe cruzar la frontera (**absorción**), luego repartirse por las distintas ciudades del país (**distribución**), después pasa por una oficina de aduanas que puede modificar su \"forma\" o incluso confiscar parte de su carga (**biotransformación**), y finalmente debe salir del país por algún puesto fronterizo (**excreción**). En cada etapa hay reglas, barreras y \"funcionarios\" (proteínas, enzimas, transportadores) que deciden qué tan fácil o difícil es el paso.",
        "",
        "#### Formas farmacéuticas y vías de administración",
        "",
        "Antes de que un fármaco pueda absorberse, tiene que dársele al paciente en alguna **forma farmacéutica** concreta (tableta, jarabe, inyectable, parche, entre otras) por alguna **vía de administración**. La vía elegida determina, de entrada, cuánta absorción hace falta y qué tan rápido se espera el efecto:",
        "",
        "* **Vías enterales** (usan el tracto digestivo) — oral, sublingual, rectal. La oral es la más común, pero obliga al fármaco a atravesar el estómago, el intestino y, antes de llegar a la circulación general, el hígado.",
        "* **Vías parenterales** (evitan el tracto digestivo) — intravenosa, intramuscular, subcutánea. La intravenosa deposita el fármaco directamente en la sangre: no hay, en sentido estricto, una etapa de \"absorción\" que atravesar.",
        "* **Otras vías** — tópica, transdérmica, inhalatoria, entre otras, cada una con su propia velocidad y patrón de absorción.",
        "",
        "Un detalle práctico y con relevancia clínica: los vasoconstrictores como la epinefrina, añadidos a un anestésico local inyectado por vía subcutánea, disminuyen la absorción sistémica del anestésico al reducir el flujo sanguíneo local — el fármaco queda \"atrapado\" más tiempo cerca del sitio de acción deseado, con menos paso a la circulación general.",
        "",
        "#### Absorción: cruzar la primera frontera",
        "",
        "La absorción depende, sobre todo, de si el fármaco puede atravesar membranas biológicas — bicapas lipídicas — por **difusión pasiva**. Aquí aplica la **hipótesis de partición de pH**: la mayoría de los fármacos son ácidos o bases débiles que existen en equilibrio entre una forma ionizada (polar, hidrosoluble) y una no ionizada (liposoluble). Solo la forma **no ionizada** cruza con facilidad la membrana — la forma ionizada, aunque más soluble en el plasma, queda relativamente atrapada por su propia carga.",
        "",
        "> Analogía: piensa en una membrana celular como una valla de madera con espacios muy estrechos entre las tablas. Una persona sin bolsas (la forma no ionizada, \"liposoluble\") se cuela fácilmente entre las tablas. Una persona cargando muchas bolsas de mandado visibles (la forma ionizada, \"cargada\" eléctricamente) queda atorada en la valla, sin importar que técnicamente sea buena caminando por la acera (soluble en el medio acuoso). Por eso, contra la intuición, ser \"más polar\" no es sinónimo de \"absorberse mejor\" — todo lo contrario, para atravesar una membrana.",
        "",
        "La aspirina (ácido acetilsalicílico) es un buen ejemplo aplicado: es un **ácido débil**, así que en el pH ácido del estómago predomina su forma no ionizada, y eso favorece su absorción gástrica.",
        "",
        "No todo fármaco depende únicamente de la difusión pasiva: algunas moléculas usan **transporte activo o facilitado**, mediado por transportadores específicos (necesario para nutrientes y algunos fármacos similares a ellos), y ciertas barreras biológicas tienen, además, bombas de expulsión como la glicoproteína P, que devuelve activamente algunas moléculas fuera de la célula. Esto es clave para entender la **barrera hematoencefálica** (BHE): NO se atraviesa únicamente por difusión pasiva, como suele creerse — también hay transportadores específicos (de glucosa, de aminoácidos) y sistemas de expulsión activa que restringen selectivamente el paso de muchas sustancias hacia el sistema nervioso central.",
        "",
        "El **efecto de primer paso** es otro concepto central de esta etapa: un fármaco administrado por vía oral, tras absorberse en el intestino, pasa primero por la vena porta hacia el hígado *antes* de llegar a la circulación general — y el hígado puede biotransformar una fracción importante de la dosis antes de que alcance su sitio de acción. Por eso, que un fármaco **evite** el efecto de primer paso (p. ej. por vía sublingual o intravenosa) es necesario pero **no suficiente** para que sea completamente biodisponible: todavía puede perderse por absorción incompleta, degradación en el tracto digestivo o metabolismo en la propia pared intestinal.",
        "",
        "#### Distribución: repartiéndose entre los tejidos",
        "",
        "Una vez en la sangre, el fármaco se reparte hacia los distintos tejidos del organismo. Dos factores dominan esta etapa:",
        "",
        "* **Unión a proteínas plasmáticas** — muchos fármacos circulan parcialmente unidos a proteínas como la albúmina. Solo la fracción **libre** (no unida) puede atravesar membranas, actuar sobre receptores o ser eliminada; la fracción unida queda \"guardada\" en el plasma como un reservorio, lo que retrasa tanto su acción como su eliminación. Un fármaco muy unido a proteínas (como la warfarina, unida en un porcentaje muy alto) tiende a tener un **volumen de distribución bajo** — se queda más confinado al plasma en vez de distribuirse ampliamente a los tejidos.",
        "* **Volumen de distribución (Vd)** — ya viste su fórmula (Vd = Dosis/C₀) en el glosario y las fórmulas de esta asignatura. Es un volumen **aparente**, no un compartimento fisiológico real: relaciona la dosis administrada con la concentración plasmática medida. Un Vd bajo (cercano al volumen plasmático, ~5 L) sugiere que el fármaco queda confinado al plasma; un Vd muy alto (decenas o cientos de litros) sugiere una distribución amplia hacia los tejidos.",
        "",
        "#### Biotransformación: la aduana que modifica la carga",
        "",
        "Ya viste en el Módulo 2 el papel de la biotransformación como fuente de interacciones farmacocinéticas. Aquí se profundiza en sus dos fases:",
        "",
        "* **Fase I (funcionalización)** — reacciones de oxidación (el sistema enzimático del citocromo P450, un conjunto de enzimas oxidativas hepáticas, es el protagonista), reducción o hidrólisis. Suelen exponer o introducir un grupo funcional reactivo en la molécula original.",
        "* **Fase II (conjugación)** — se une el fármaco (o su metabolito de fase I) a un sustrato endógeno hidrofílico: ácido glucurónico, sulfato o glutatión. El resultado es, casi siempre, una molécula más hidrosoluble y más fácil de excretar.",
        "",
        "No toda biotransformación desactiva al fármaco. Hay **profármacos**, diseñados deliberadamente para activarse solo tras metabolizarse (la codeína se convierte en morfina, su forma activa), y hay **metabolitos tóxicos**: el ejemplo clásico es el paracetamol, cuya sobredosis satura las vías normales de conjugación y desvía una fracción mayor hacia un metabolito reactivo (NAPQI, abreviatura de N-acetil-p-benzoquinona imina) que, si se agota el glutatión hepático disponible para neutralizarlo, causa daño hepático agudo. Por eso el antídoto de la sobredosis de paracetamol es la N-acetilcisteína: repone el \"estatus de glutatión\" del hígado.",
        "",
        "La actividad de estas enzimas no es fija: puede **inducirse** (el fenobarbital es el ejemplo clásico de inductor amplio, que acelera el metabolismo de sí mismo y de otros fármacos coadministrados) o **inhibirse** (un segundo fármaco compite por la misma enzima o la bloquea directamente, haciendo que el primero se acumule). Ambos fenómenos son una fuente central de interacciones farmacocinéticas: cambian cuánto fármaco activo llega, en última instancia, a producir su efecto farmacodinámico.",
        "",
        "> Analogía: piensa en el hígado como una aduana con un número limitado de funcionarios (enzimas) revisando cada maleta (molécula de fármaco). Inducir enzimas es como contratar más funcionarios — la aduana procesa más rápido, así que el fármaco pasa (se metaboliza) más deprisa de lo normal. Inhibir enzimas es como bloquear a los funcionarios existentes — se forma una fila, el fármaco se acumula esperando su turno.",
        "",
        "#### Eliminación: la salida del país",
        "",
        "La eliminación final del fármaco (o de sus metabolitos) ocurre principalmente por dos rutas:",
        "",
        "* **Eliminación renal** — filtración glomerular (solo del fármaco libre, no unido a proteínas), secreción tubular activa y reabsorción tubular pasiva. Aquí aplica el **atrapamiento iónico**: si se altera el pH de la orina, se altera cuánto fármaco se ioniza en el túbulo renal y, por tanto, cuánto se reabsorbe de vuelta a la sangre o queda atrapado para eliminarse. **Alcalinizar** la orina favorece la eliminación de **ácidos débiles** (barbitúricos, salicilatos: se ionizan más, quedan atrapados); **acidificar** la orina favorece la eliminación de **bases débiles**, por el principio inverso.",
        "* **Eliminación biliar** — el hígado excreta el fármaco (o su metabolito conjugado) hacia la bilis, que lo lleva al intestino. Desde ahí puede eliminarse con las heces, o parte de él puede **reabsorberse** de vuelta a la circulación general — la llamada **circulación enterohepática**, que actúa como un ciclo de reciclaje y **prolonga** la vida media efectiva del fármaco.",
        "",
        "El **aclaramiento** (*clearance*, abreviado CL) resume la capacidad del organismo entero para eliminar un fármaco: es el volumen de plasma que queda completamente \"limpio\" de fármaco por unidad de tiempo. Junto con el volumen de distribución, determina la **vida media de eliminación** (t½ = 0,693 · Vd / CL, fórmula que ya viste en esta asignatura): el tiempo que tarda la concentración plasmática en caer a la mitad, y que orienta directamente la frecuencia de dosificación de un fármaco.",
        "",
        "#### Factores que afectan los procesos ADME",
        "",
        "Ningún proceso de absorción, distribución, metabolismo o excreción ocurre igual en todas las personas ni en todas las condiciones. Edad (los recién nacidos tienen enzimas de conjugación inmaduras — por eso el fenobarbital se ha usado para inducirlas en hiperbilirrubinemia neonatal), función renal y hepática, embarazo, genética (polimorfismos enzimáticos que aceleran o enlentecen el metabolismo de ciertos fármacos) y las propias interacciones farmacocinéticas con otros fármacos son variables que modifican, en la práctica, cuánto fármaco llega y cuánto tiempo permanece activo en el organismo. Este es, precisamente, el puente hacia el Módulo 4: la farmacología clínica estudia justo esa variabilidad interindividual en la respuesta.",
        "",
        "#### En resumen",
        "",
        "* La farmacocinética recorre cuatro etapas — absorción, distribución, metabolismo (biotransformación) y excreción (ADME) — que determinan cuánto fármaco llega a su sitio de acción y por cuánto tiempo.",
        "* La **absorción** depende sobre todo de la forma no ionizada de ácidos y bases débiles (hipótesis de partición de pH); la barrera hematoencefálica no se cruza solo por difusión pasiva, también hay transporte activo/facilitado y bombas de expulsión.",
        "* El **efecto de primer paso** reduce la biodisponibilidad oral; evitarlo es necesario pero no suficiente para una biodisponibilidad completa.",
        "* La **unión a proteínas plasmáticas** retrasa —no facilita— la eliminación, y se relaciona con un volumen de distribución bajo.",
        "* La **biotransformación** (fase I: funcionalización; fase II: conjugación) no siempre inactiva al fármaco — hay profármacos y metabolitos tóxicos — y su velocidad puede inducirse o inhibirse enzimáticamente.",
        "* La **eliminación renal** obedece al atrapamiento iónico según el pH urinario; la **eliminación biliar** puede reciclarse por circulación enterohepática, prolongando la vida media.",
        "* Los factores individuales (edad, función renal/hepática, genética) modulan todos estos procesos — el puente directo hacia la variabilidad de la respuesta que estudia el Módulo 4.",
      ].join("\n"),
    },
    {
      slug: "farmacologia-clinica",
      title: "Módulo 4: Principios de farmacología clínica",
      description:
        "**Variabilidad en la respuesta** farmacológica: distribución poblacional, factores genéticos, edad, idiosincrasias, estados fisiológicos y patológicos. **Reacciones adversas a los medicamentos (RAM)**: clasificación y concepto de **farmacovigilancia**. **Monitorización terapéutica** de fármacos y nociones de farmacoepidemiología.",
    },
    {
      slug: "investigacion-farmacologia",
      title: "Módulo 5: Introducción a la investigación en farmacología",
      description:
        "Proceso de **investigación de los medicamentos**: investigación preclínica (principios y métodos), el animal de experimentación como reactivo biológico, ética y **alternativas** en experimentación animal, ensayos de **screening**. **Ensayos clínicos**: fases de la evaluación clínica y principios éticos (**Declaración de Helsinki**).",
    },
    {
      slug: "snc-introduccion",
      title: "Módulo 6: Introducción a la farmacología del SNC",
      description:
        "La **neurotransmisión como diana farmacológica**. Mediadores químicos en el SNC (glutamato, GABA, dopamina, serotonina, noradrenalina, acetilcolina). **Clasificación** de los fármacos con acción central.",
    },
    {
      slug: "snc-farmacoterapia",
      title: "Módulo 7: Farmacología del SNC — farmacoterapia",
      description:
        "**Anestesia balanceada**. Tratamiento farmacológico del **dolor y la inflamación**. **Sedantes, hipnóticos y ansiolíticos**. **Antidepresivos** y **neurolépticos**. **Antiparkinsonianos**, **antiepilépticos** y tratamiento del **Alzheimer**. **Farmacodependencias** y abuso de fármacos.",
    },
    {
      slug: "aspectos-legales",
      title: "Módulo 8: Aspectos legales y comerciales del uso de medicamentos",
      description:
        "Evaluación farmacológica en el proceso de **registro sanitario**. **Productos fitoterapéuticos**: marco regulatorio y evidencia.",
    },
  ],

  glossary: [
    // --- Módulo 1: Generalidades ---
    { term: "Fármaco", moduleSlug: "generalidades", definition: "Sustancia caracterizada por su actividad biológica: qué le hace al organismo y por qué mecanismo. Intermedio entre el principio activo puro y el medicamento terminado. *(en inglés: **drug**, o *pharmacon*.)*" },
    { term: "Medicamento", moduleSlug: "generalidades", definition: "El producto terminado listo para el paciente: fármaco + excipientes + forma farmacéutica (tableta, jarabe, inyectable) + información de uso + empaque. *(en inglés: **medicine** / **medication**.)*" },
    { term: "Principio activo", moduleSlug: "generalidades", definition: "La sustancia química pura responsable del efecto biológico — el \"ingrediente\" sin excipientes ni forma farmacéutica. *(en inglés: **active pharmaceutical ingredient**, abreviado **API**.)*" },
    { term: "Droga", moduleSlug: "generalidades", definition: "En sentido farmacológico amplio, cualquier sustancia capaz de modificar la función de un organismo vivo (incluye fármacos, venenos y sustancias de uso recreativo) — no es sinónimo de \"fármaco\" ni de \"estupefaciente\". *(en inglés: **drug**, en su acepción más general.)*" },
    { term: "Estupefaciente", moduleSlug: "generalidades", definition: "Categoría legal y regulatoria (no farmacológica): sustancias controladas por su potencial de abuso y dependencia, como la mayoría de los opioides. *(en inglés: **narcotic** / **controlled substance**.)*" },
    { term: "Denominación Común Internacional (DCI)", moduleSlug: "generalidades", definition: "Nombre genérico único que asigna la Organización Mundial de la Salud a cada principio activo, igual en cualquier país y para cualquier fabricante — distinto del nombre químico (estructura IUPAC) y del nombre comercial (marca del laboratorio). *(en inglés: **International Nonproprietary Name**, abreviado **INN**.)*" },
    { term: "Dosis", moduleSlug: "generalidades", definition: "Cantidad de fármaco administrada de una vez o por unidad de tiempo — una cantidad, no un efecto (el efecto de cada dosis se estudia en la curva dosis-respuesta, Módulo 2). *(en inglés: **dose**.)*" },
    { term: "Fuentes de información (primaria / secundaria / terciaria)", moduleSlug: "generalidades", definition: "**Primaria**: el reporte original de un estudio. **Secundaria**: analiza y sintetiza varias fuentes primarias (revisiones sistemáticas, metaanálisis). **Terciaria**: compendios de referencia rápida (vademécum, libros de texto). *(en inglés: **primary / secondary / tertiary sources**.)*" },

    // --- Módulo 2: Farmacodinamia ---
    { term: "Farmacodinamia", moduleSlug: "farmacodinamia", definition: "Estudio de **qué le hace el fármaco al organismo**: sus efectos bioquímicos y fisiológicos y su mecanismo de acción. *(en inglés: **pharmacodynamics**.)*" },
    { term: "Mecanismo inespecífico", moduleSlug: "farmacodinamia", definition: "Mecanismo de acción que depende de propiedades fisicoquímicas simples (neutralización, quelación, ósmosis, perturbación de membranas lipídicas) y no de reconocer una molécula diana concreta — no necesita un receptor. *(en inglés: **nonspecific mechanism**.)*" },
    { term: "Receptor acoplado a proteína G", moduleSlug: "farmacodinamia", definition: "Familia de receptores con siete dominios transmembrana que, al activarse, acoplan y activan una proteína G intracelular (transductora, no el receptor mismo), la cual modula enzimas o canales mediante segundos mensajeros. *(en inglés: **G protein-coupled receptor**, abreviado **GPCR**; también llamados receptores \"7TM\" por sus siete pasos transmembrana.)*" },
    { term: "Segundos mensajeros", moduleSlug: "farmacodinamia", definition: "Moléculas intracelulares que amplifican y transmiten la señal iniciada por un receptor de membrana: el adenosín monofosfato cíclico (**AMPc**), el guanosín monofosfato cíclico (**GMPc**), el inositol trifosfato (**IP₃**), el diacilglicerol (**DAG**) y el calcio intracelular (**Ca²⁺**). *(en inglés: **second messengers**.)*" },
    { term: "Curva dosis-respuesta", moduleSlug: "farmacodinamia", definition: "Relación entre la dosis (o concentración) y la magnitud del efecto; sigmoide en escala logarítmica. Define la **potencia** (posición de la curva, dosis efectiva 50 o **DE₅₀**) y la **eficacia** (efecto máximo, el \"techo\" de la curva). *(en inglés: **dose-response curve**.)*" },
    { term: "Potencia", moduleSlug: "farmacodinamia", definition: "Cuánta dosis hace falta para lograr un efecto dado; se compara con la dosis efectiva 50 (**DE₅₀**) — a menor DE₅₀, mayor potencia. Independiente de la eficacia. *(en inglés: **potency**.)*" },
    { term: "Eficacia", moduleSlug: "farmacodinamia", definition: "Efecto máximo que puede producir un fármaco — el \"techo\" de su curva dosis-respuesta, alcanzado cuando el sistema se satura de receptores ocupados. *(en inglés: **efficacy**.)*" },
    { term: "Actividad intrínseca", moduleSlug: "farmacodinamia", definition: "Capacidad de un fármaco, ya unido al receptor, de activarlo y producir respuesta: de 0 (antagonista puro) a 1 (agonista total). *(en inglés: **intrinsic activity**.)*" },
    { term: "Agonista / antagonista", moduleSlug: "farmacodinamia", definition: "**Agonista**: se une al receptor y produce respuesta. **Antagonista**: se une pero no activa; bloquea la acción del agonista (competitivo, por el mismo sitio, o no competitivo, por un sitio distinto o de forma irreversible)." },
    { term: "Agonista parcial", moduleSlug: "farmacodinamia", definition: "Fármaco con actividad intrínseca entre 0 y 1: aun ocupando el 100 % de los receptores, no alcanza el efecto máximo de un agonista total; frente a este último, reduce el efecto máximo y se comporta como antagonista parcial. *(en inglés: **partial agonist**.)*" },
    { term: "Antagonismo fisiológico", moduleSlug: "farmacodinamia", definition: "Dos sustancias actúan sobre receptores **distintos**, produciendo efectos **opuestos** que se cancelan a nivel del sistema — no compiten por el mismo receptor (ejemplo: adrenalina frente a histamina en el shock anafiláctico). *(en inglés: **physiological antagonism**, también llamado **functional antagonism**.)*" },
    { term: "Regulación de receptores (up/down-regulation)", moduleSlug: "farmacodinamia", definition: "La exposición prolongada a un agonista puede reducir el número o la sensibilidad de los receptores (regulación a la baja, base de la tolerancia); el bloqueo prolongado con un antagonista puede aumentar el número de receptores (regulación al alza), explicando el efecto de rebote al suspender el fármaco de golpe. *(en inglés: **up-regulation** / **down-regulation**.)*" },
    { term: "Sinergismo / antagonismo (interacción farmacodinámica)", moduleSlug: "farmacodinamia", definition: "**Sinergismo**: el efecto combinado de dos fármacos supera la simple suma de los efectos individuales (potenciación). **Antagonismo**: un fármaco reduce o anula el efecto de otro. *(en inglés: **synergism** / **antagonism**.)*" },

    // --- Módulo 3: Farmacocinética — procesos ADME ---
    { term: "Farmacocinética", moduleSlug: "farmacocinetica-adme", definition: "Estudio de **qué le hace el organismo al fármaco**: absorción, distribución, metabolismo y excreción, en función del tiempo. *(en inglés: **pharmacokinetics**.)*" },
    { term: "Absorción, distribución, metabolismo y excreción (ADME)", moduleSlug: "farmacocinetica-adme", definition: "Las cuatro etapas del recorrido de un fármaco por el organismo, desde que entra hasta que sale, que determinan cuánto llega a su sitio de acción y por cuánto tiempo. *(en inglés: **Absorption, Distribution, Metabolism, Excretion**, sigla **ADME**.)*" },
    { term: "Vías de administración", moduleSlug: "farmacocinetica-adme", definition: "Ruta por la que se da un medicamento al paciente: enterales (oral, sublingual, rectal — usan el tracto digestivo) o parenterales (intravenosa, intramuscular, subcutánea — lo evitan), entre otras (tópica, transdérmica, inhalatoria). *(en inglés: **routes of administration**.)*" },
    { term: "Biodisponibilidad", moduleSlug: "farmacocinetica-adme", definition: "Fracción de la dosis administrada que llega intacta a la circulación general. Evitar el efecto de primer paso es necesario pero no suficiente para una biodisponibilidad completa (también influyen la absorción incompleta y la degradación en el tracto digestivo). *(en inglés: **bioavailability**.)*" },
    { term: "Efecto de primer paso", moduleSlug: "farmacocinetica-adme", definition: "Biotransformación de una fracción del fármaco administrado por vía oral, en el hígado (tras absorberse en el intestino, pasa por la vena porta) o en la pared intestinal, antes de llegar a la circulación general. *(en inglés: **first-pass effect** / **first-pass metabolism**.)*" },
    { term: "Barrera hematoencefálica", moduleSlug: "farmacocinetica-adme", definition: "Barrera que restringe selectivamente el paso de sustancias hacia el sistema nervioso central; no se cruza únicamente por difusión pasiva — también hay transporte activo/facilitado (glucosa, aminoácidos) y bombas de expulsión como la glicoproteína P. *(en inglés: **blood-brain barrier**, abreviado **BBB**.)*" },
    { term: "Unión a proteínas plasmáticas", moduleSlug: "farmacocinetica-adme", definition: "Fracción de un fármaco que circula unida a proteínas (como la albúmina); solo la fracción libre atraviesa membranas, actúa sobre receptores o se elimina — la unión actúa como reservorio que retrasa la eliminación, no la facilita. *(en inglés: **plasma protein binding**.)*" },
    { term: "Atrapamiento iónico", moduleSlug: "farmacocinetica-adme", definition: "Principio de eliminación renal: alcalinizar la orina favorece la eliminación de ácidos débiles (se ionizan más, quedan atrapados en la orina); acidificar la orina favorece la eliminación de bases débiles, por el principio inverso. *(en inglés: **ion trapping**.)*" },
    { term: "Biotransformación (fases I y II)", moduleSlug: "farmacocinetica-adme", definition: "**Fase I**: reacciones de funcionalización (oxidación por el citocromo P450, reducción, hidrólisis). **Fase II**: conjugación (con ácido glucurónico, sulfato o glutatión) que aumenta la hidrosolubilidad para facilitar la excreción. No siempre da metabolitos inactivos: hay profármacos que se activan y metabolitos tóxicos. *(en inglés: **biotransformation**, o **Phase I / Phase II metabolism**.)*" },
    { term: "Citocromo P450", moduleSlug: "farmacocinetica-adme", definition: "Superfamilia de enzimas oxidativas hepáticas responsables de la mayoría de las reacciones de fase I de la biotransformación. Su actividad puede inducirse o inhibirse por otros fármacos. *(en inglés: **cytochrome P450**, abreviado **CYP450**.)*" },
    { term: "Inducción / inhibición enzimática", moduleSlug: "farmacocinetica-adme", definition: "**Inducción**: un fármaco (p. ej. fenobarbital) aumenta la cantidad o actividad de las enzimas metabolizadoras, acelerando el metabolismo de sí mismo u otros fármacos. **Inhibición**: un fármaco bloquea o compite por esas enzimas, haciendo que el otro se acumule. Ambas alteran la intensidad y duración del efecto. *(en inglés: **enzyme induction / inhibition**.)*" },
    { term: "Volumen de distribución (Vd)", moduleSlug: "farmacocinetica-adme", definition: "Volumen aparente (no un compartimento fisiológico real) en el que se distribuiría el fármaco para alcanzar la concentración plasmática medida: Vd = dosis / C₀. *(en inglés: **volume of distribution**.)*" },
    { term: "Eliminación renal y biliar", moduleSlug: "farmacocinetica-adme", definition: "**Renal**: filtración glomerular (solo del fármaco libre), secreción tubular activa y reabsorción tubular pasiva (sujeta a atrapamiento iónico). **Biliar**: el hígado excreta el fármaco hacia la bilis y de ahí al intestino, desde donde puede eliminarse o reabsorberse (circulación enterohepática). *(en inglés: **renal and biliary elimination**.)*" },
    { term: "Circulación enterohepática", moduleSlug: "farmacocinetica-adme", definition: "Reciclaje de un fármaco excretado por bilis al intestino, que se reabsorbe de vuelta a la circulación general en lugar de eliminarse con las heces — prolonga la vida media efectiva del fármaco. *(en inglés: **enterohepatic circulation** / **enterohepatic recirculation**.)*" },
    { term: "Aclaramiento (clearance)", moduleSlug: "farmacocinetica-adme", definition: "Volumen de plasma que queda completamente libre de fármaco por unidad de tiempo; resume la capacidad del organismo entero para eliminarlo. Junto con el volumen de distribución, determina la vida media de eliminación. *(en inglés: **clearance**, abreviado **CL**.)*" },
    { term: "Vida media de eliminación (t½)", moduleSlug: "farmacocinetica-adme", definition: "Tiempo que tarda la concentración plasmática de un fármaco en reducirse a la mitad; determina la frecuencia de dosificación y el tiempo hasta el estado estacionario (~4-5 vidas medias). *(en inglés: **elimination half-life**.)*" },

    // --- Módulo 4: Principios de farmacología clínica ---
    { term: "Reacción adversa a medicamentos (RAM)", moduleSlug: "farmacologia-clinica", definition: "Respuesta nociva y no intencionada a un medicamento, en dosis usadas para profilaxis, diagnóstico o tratamiento. Se clasifica en tipo A (aumentada, dosis-dependiente), B (bizarra/idiosincrásica), C (crónica), D (diferida), E (por fin de tratamiento) y F (foreign/fallo terapéutico, por excipientes o mal uso). *(en inglés: **adverse drug reaction**, abreviado **ADR**.)*" },
    { term: "Farmacovigilancia", moduleSlug: "farmacologia-clinica", definition: "Actividades de detección, evaluación, comprensión y prevención de las reacciones adversas a medicamentos y otros problemas relacionados, principalmente en la etapa de poscomercialización. *(en inglés: **pharmacovigilance**.)*" },
    { term: "Índice terapéutico", moduleSlug: "farmacologia-clinica", definition: "Relación entre la dosis que produce toxicidad y la dosis eficaz (dosis letal 50 sobre dosis efectiva 50, o DL₅₀/DE₅₀). Cuanto mayor, más seguro el margen del fármaco. *(en inglés: **therapeutic index**.)*" },

    // --- Módulo 5: Introducción a la investigación en farmacología ---
    { term: "Ensayo clínico — fases", moduleSlug: "investigacion-farmacologia", definition: "**Fase I** (seguridad, voluntarios sanos), **Fase II** (eficacia y dosis, pacientes), **Fase III** (confirmación frente al estándar de tratamiento), **Fase IV** (farmacovigilancia poscomercialización). *(en inglés: **clinical trial phases**.)*" },
  ],

  formulas: [
    {
      name: "Índice terapéutico",
      expression: "IT = #{DL_{50}|DE_{50}}",
      variables: "DL_{50} = dosis letal 50 · DE_{50} = dosis efectiva 50",
      description: "Estima el **margen de seguridad** de un fármaco: cuánto separa la dosis eficaz de la dosis tóxica.",
      moduleSlug: "farmacologia-clinica",
      derivation:
        "Se obtiene de dos curvas dosis-respuesta cuantales: una para el efecto terapéutico y otra para la toxicidad (o letalidad). El cociente de sus valores medianos indica cuántas veces hay que aumentar la dosis eficaz para llegar a la tóxica. Un IT alto (> 10) da un margen amplio; fármacos como digoxina o litio tienen IT bajo y requieren monitorización.\nIT = índice terapéutico — adimensional.\nDL_{50} = dosis que produce el efecto tóxico/letal en el 50 % de la población — mg/kg.\nDE_{50} = dosis que produce el efecto terapéutico en el 50 % — mg/kg.",
    },
    {
      name: "Volumen de distribución",
      expression: "V_{d} = #{Dosis|C_{0}}",
      variables: "C_{0} = concentración plasmática extrapolada a tiempo cero",
      description: "Parámetro que relaciona la cantidad de fármaco en el cuerpo con su concentración plasmática; orienta sobre su **distribución tisular**.",
      moduleSlug: "farmacocinetica-adme",
      derivation:
        "Es un volumen **aparente**, no fisiológico: el que haría falta para que toda la dosis administrada estuviera a la concentración plasmática medida. Valores bajos (~5 L) indican fármaco confinado al plasma; valores muy altos (cientos de L) indican gran fijación a tejidos.\nV_{d} = volumen aparente de distribución — L o L/kg.\nDosis = cantidad de fármaco en el organismo (dosis IV) — mg.\nC_{0} = concentración plasmática a tiempo cero — mg/L.",
    },
    {
      name: "Vida media de eliminación",
      expression: "t_{1/2} = #{0,693 · V_{d}|CL}",
      variables: "CL = aclaramiento (clearance) · V_{d} = volumen de distribución",
      description: "Tiempo que tarda la concentración plasmática en reducirse a la mitad; determina la **frecuencia de dosificación** y el tiempo hasta el estado estacionario (~4–5 t½).",
      moduleSlug: "farmacocinetica-adme",
      derivation:
        "Para una cinética de primer orden, la constante de eliminación es k = CL/V_{d}, y el tiempo para que C caiga a la mitad es ln(2)/k = 0,693·V_{d}/CL. Depende por igual del aclaramiento y del volumen de distribución.\nt_{1/2} = vida media de eliminación — h.\nV_{d} = volumen de distribución — L.\nCL = aclaramiento plasmático — L/h.",
    },
  ],

  evaluation: [
    { name: "1er Parcial (semana 4)", weight: 20 },
    { name: "2do Parcial (semana 8)", weight: 20 },
    { name: "3er Parcial (semana 12)", weight: 20 },
    { name: "Evaluación final (semana 16)", weight: 20 },
    { name: "Participación, talleres, quices y tareas", weight: 20 },
  ],

  keyDates: [
    { name: "1er Parcial", weight: "20%" },
    { name: "2do Parcial", weight: "20%" },
    { name: "3er Parcial", weight: "20%" },
    { name: "Evaluación final", weight: "20%" },
  ],

  projects: [
    { title: "Talleres de discusión", category: "Taller" },
    { title: "Seminario / exposición", category: "Seminario" },
  ],

  bibliography: [
    { kind: "libro", reference: "Brunton L., Chabner B.A., Knollmann B.C. (Ed.). Goodman & Gilman. Las Bases Farmacológicas de la Terapéutica. Vol. I y II. McGraw-Hill Interamericana. México. 2012." },
    { kind: "libro", reference: "Hilal-Dandan R., Brunton L. (Ed.). Goodman & Gilman Manual de Farmacología y Terapéutica. 2ª ed. McGraw-Hill Education. México. 2015." },
    { kind: "libro", reference: "Katzung B.G. (Ed.). Farmacología Básica y Clínica. 12ª ed. McGraw-Hill Interamericana. México. 2013. (y Katzung's Basic & Clinical Pharmacology, T.W. Vanderah, 2024)." },
    { kind: "libro", reference: "Flórez J., Armijo J.A., Mediavilla A. Farmacología Humana. 6ª ed. Elsevier Masson. Barcelona. 2014." },
    { kind: "libro", reference: "Rang & Dale. Farmacología. M. Dale. 9ª ed. Elsevier. 2020." },
    { kind: "libro", reference: "Isaza C.A., Machado J.E., Machado M.E. y col. Fundamentos de Farmacología en Terapéutica. 7ª ed. Celsus. Colombia. 2020." },
    { kind: "libro", reference: "Golan D.E. (Ed.). Principios de Farmacología: Bases Fisiopatológicas del Tratamiento Farmacológico. Lippincott Williams & Wilkins. España. 2012." },
    { kind: "libro", reference: "Declaración de Helsinki de la AMM. Res. 008430 de 1993 (Min. Salud, Colombia). Ley 84 de 1989 (protección animal)." },
    { kind: "revista", reference: "British Journal of Pharmacology" },
    { kind: "revista", reference: "European Journal of Pharmacology" },
    { kind: "revista", reference: "Trends in Pharmacological Sciences" },
    { kind: "revista", reference: "Annual Review of Pharmacology and Toxicology" },
  ],
};
