import type { SubjectContent } from "./_schema";

/**
 * Farmacología General (UNAL) — desde el programa oficial (Prof. Luis Fernando
 * Ospina Giraldo). Código 2015683. Sin componente de laboratorio.
 * Las fechas de parciales van en la app.
 */
export const fg: SubjectContent = {
  code: "FG",
  slug: "fg",
  name: "Farmacología General",
  credits: "3",
  professors: ["Luis Fernando Ospina Giraldo"],
  scheduleTheory: "Lunes 7:00–9:00, Miércoles 14:00–16:00",
  scheduleLab: "",
  totalClasses: 32,
  hasLab: false,
  descriptionSummary:
    "Conceptos **farmacológicos básicos** —farmacodinamia, farmacocinética y farmacología clínica— para el manejo y **uso racional** de las sustancias con actividad biológica, con aplicación a la farmacoterapia de los trastornos del **sistema nervioso central**.",
  objectiveGeneral:
    "Que el estudiante desarrolle habilidades para **aplicar de manera crítica y analítica** los conceptos farmacológicos básicos indispensables en el manejo y uso racional de las sustancias con actividad biológica, e integrarlos con las demás disciplinas del campo profesional.",
  objectivesSpecific: [
    "Comprender e integrar los aspectos farmacológicos básicos para **inferir y corregir interacciones** farmacológicas de importancia clínica.",
    "Caracterizar las sustancias según su **estructura química, sitio y mecanismo de acción y actividad farmacológica**, para participar en el diseño, la valoración biológica y la aplicación de nuevas moléculas activas.",
  ],

  // Curso teórico (clases magistrales, talleres, seminarios). Sin laboratorio.
  sections: ["modulos", "proyectos", "fechas", "glosario", "formulas", "bibliografia", "insumos", "prompt-ia"],

  modules: [
    {
      slug: "generalidades",
      title: "Módulo 1: Generalidades",
      description:
        "Contexto de la Farmacología en las Ciencias Biomédicas. **Definiciones y conceptos básicos** (fármaco, medicamento, principio activo, dosis). **Fuentes de información** sobre medicamentos. **Denominación** de los fármacos (DCI/INN, nombre químico, comercial).",
      exercises: [
        {
          question: [
            "**Verdadero o falso, con justificación.** En farmacología clínica, droga y estupefaciente son términos equivalentes.",
          ].join("\n"),
          solution: [
            "**Falso.**",
            "",
            "**Droga** es el término amplio: cualquier sustancia capaz de modificar la función de un organismo vivo (incluye venenos, tóxicos, sustancias recreativas y fármacos). **Estupefaciente** es una categoría legal/regulatoria: sustancias controladas por su potencial de abuso y dependencia (opioides, algunos psicoestimulantes). Un fármaco de uso terapéutico corriente (p. ej. paracetamol) es una droga pero no un estupefaciente; la morfina sí es ambas cosas.",
          ].join("\n"),
        },
        {
          question: [
            "**Definición — diferenciación.** Diferencie **fármaco**, **medicamento** y **principio activo**, y ordénelos de \"ingrediente\" a \"producto terminado\".",
          ].join("\n"),
          solution: [
            "**Principio activo**: la sustancia química pura responsable del efecto biológico (el \"ingrediente\").",
            "",
            "**Fármaco**: esa sustancia ya caracterizada por su actividad farmacológica — qué le hace al organismo y por qué mecanismo.",
            "",
            "**Medicamento**: el producto terminado listo para el paciente — principio activo + excipientes + forma farmacéutica (tableta, jarabe, inyectable) + información de uso + empaque.",
            "",
            "Orden: principio activo → fármaco → medicamento.",
          ].join("\n"),
        },
        {
          question: [
            "**Aplicación.** El paracetamol se puede nombrar de formas distintas según el contexto: *N-(4-hidroxifenil)acetamida*, *paracetamol/acetaminofén* y *Dolex®/Panadol®/Tylenol®*. Identifique cuál es el nombre químico, cuál la DCI (Denominación Común Internacional) y cuál el/los nombre(s) comercial(es), y explique para qué sirve cada uno.",
          ].join("\n"),
          solution: [
            "**Nombre químico** (*N-(4-hidroxifenil)acetamida*): describe la estructura según reglas IUPAC — preciso pero poco práctico para prescribir.",
            "",
            "**DCI/INN** (*paracetamol* / *acetaminofén*): nombre genérico único asignado por la OMS, igual en cualquier país y cualquier fabricante — es el que identifica sin ambigüedad al principio activo.",
            "",
            "**Nombres comerciales** (*Dolex®, Panadol®, Tylenol®*): marcas registradas por cada laboratorio para el mismo principio activo; pueden variar de un país a otro y cambian con el fabricante, aunque el fármaco sea idéntico.",
          ].join("\n"),
        },
        {
          question: [
            "**Opción múltiple.** Un ensayo clínico fase III publicado en una revista indexada, un vademécum farmacéutico y una revisión sistemática que resume 40 estudios sobre un mismo fármaco son, respectivamente, ejemplos de fuentes de información:",
            "",
            "A) Terciaria, primaria, secundaria",
            "B) Primaria, terciaria, secundaria",
            "C) Secundaria, primaria, terciaria",
            "D) Primaria, secundaria, terciaria",
          ].join("\n"),
          solution: [
            "**Respuesta: B.**",
            "",
            "**Fuente primaria**: el artículo original que reporta datos de primera mano (el ensayo clínico). **Fuente terciaria**: compendios de referencia rápida que ya sintetizan el conocimiento establecido (vademécum, formularios, libros de texto). **Fuente secundaria**: analiza y sintetiza varias fuentes primarias (revisión sistemática, metaanálisis) — está a medio camino entre el dato crudo y el resumen de referencia.",
          ].join("\n"),
        },
      ],
      chapter: [
        "#### Por qué empezar por las palabras",
        "",
        "La farmacología es una ciencia de cruce: se apoya en química, fisiología, bioquímica, patología, genética y estadística a la vez. Antes de estudiar cómo actúa cualquier sustancia sobre el organismo, hace falta fijar el vocabulario que vas a usar el resto de la carrera — porque en el lenguaje cotidiano \"droga\", \"medicamento\" y \"fármaco\" se usan como sinónimos, y en farmacología clínica **no lo son**. Esa es, de hecho, la primera trampa clásica de examen en este curso.",
        "",
        "#### Principio activo, fármaco y medicamento: del ingrediente al producto terminado",
        "",
        "> Analogía: piensa en la diferencia entre \"ingrediente\", \"receta caracterizada\" y \"plato servido\". El **principio activo** es el ingrediente puro (paracetamol en polvo, sin nada más). El **fármaco** es ese ingrediente ya estudiado y caracterizado por su actividad biológica: qué le hace al organismo, por qué mecanismo, a qué dosis. El **medicamento** es el \"plato servido\": el principio activo combinado con excipientes, presentado en una forma farmacéutica concreta (tableta, jarabe, inyectable), con su información de uso y su empaque — listo para que lo reciba un paciente.",
        "",
        "La **dosis** es la cantidad de fármaco administrada de una vez (o por unidad de tiempo) para producir un efecto. Todavía no hablamos aquí de *cuánto* efecto produce cada dosis — eso, la curva dosis-respuesta, es el corazón del Módulo 2 — pero conviene tener clara la definición desde ahora: dosis es una cantidad, no un efecto.",
        "",
        "#### Droga, fármaco y estupefaciente: tres palabras que no son sinónimas",
        "",
        "**Droga**, en el sentido farmacológico amplio, es cualquier sustancia capaz de modificar la función de un organismo vivo — un concepto tan amplio que incluye tanto a los fármacos terapéuticos como a los venenos, los tóxicos ambientales y las sustancias de uso recreativo. **Fármaco** es más específico: una droga que se usa con intención terapéutica, diagnóstica o preventiva, y de la que se conoce su mecanismo de acción. **Estupefaciente**, en cambio, no es una categoría farmacológica sino **legal y regulatoria**: sustancias sometidas a control especial por su potencial de abuso y dependencia (la mayoría de los opioides, por ejemplo).",
        "",
        "> Analogía: \"droga\" es como \"vehículo\" — una categoría enorme que incluye bicicletas, camiones y aviones. \"Fármaco\" es como \"vehículo con conductor autorizado y ruta declarada\" — un uso específico y caracterizado de esa categoría amplia. \"Estupefaciente\" es como \"vehículo de carga peligrosa\": una etiqueta legal que exige controles especiales, independientemente de si el vehículo (la droga) se usa bien o mal. Por eso la morfina es, a la vez, una droga, un fármaco (analgésico opioide bien caracterizado) y un estupefaciente (sometido a control legal estricto) — pero el paracetamol es droga y fármaco, sin ser estupefaciente.",
        "",
        "#### La denominación de los fármacos: tres nombres para la misma molécula",
        "",
        "Cualquier fármaco puede nombrarse de al menos tres formas distintas, y confundirlas genera errores de prescripción y de comunicación:",
        "",
        "* **Nombre químico** — describe la estructura molecular según las reglas de nomenclatura de la IUPAC. Es exacto pero impráctico para el uso clínico diario.",
        "* **DCI / INN** (Denominación Común Internacional / *International Nonproprietary Name*) — el nombre genérico único que asigna la Organización Mundial de la Salud a cada principio activo. Es el mismo en cualquier país, para cualquier fabricante.",
        "* **Nombre comercial (marca)** — el nombre registrado por cada laboratorio para su producto. Puede variar de un país a otro, cambia con el fabricante y suele estar protegido por patente durante un tiempo.",
        "",
        "> Analogía: piensa en el documento de identidad de una persona. La **DCI** es como el número de cédula: único, universal, no cambia sin importar quién te llame. El **nombre comercial** es como los distintos apodos que te pueden poner en diferentes círculos — la misma persona (molécula) puede tener varios \"apodos\" (Dolex®, Panadol®, Tylenol®) según quién la fabrique y venda, pero la cédula (DCI: paracetamol) sigue siendo una sola.",
        "",
        "#### Fuentes de información sobre medicamentos",
        "",
        "No toda la información disponible sobre un fármaco tiene el mismo nivel de evidencia ni el mismo propósito. Es útil clasificarla en tres niveles:",
        "",
        "* **Fuentes primarias** — el reporte original de primera mano: el artículo de un ensayo clínico, un estudio experimental publicado en una revista indexada.",
        "* **Fuentes secundarias** — analizan y sintetizan varias fuentes primarias: revisiones sistemáticas, metaanálisis, índices bibliográficos.",
        "* **Fuentes terciarias** — compendios de referencia rápida que ya destilan el conocimiento establecido: vademécums, formularios terapéuticos, libros de texto, la información de prescripción oficial (inserto/prospecto).",
        "",
        "> Analogía periodística: la fuente primaria es el reportero que estuvo en el lugar de los hechos y escribió la nota original. La fuente secundaria es el artículo de análisis que cruza varias notas originales para explicar una tendencia. La fuente terciaria es la entrada de una enciclopedia: rápida de consultar, pero ya varios pasos alejada del hecho crudo.",
        "",
        "Conviene distinguir, además, entre información **independiente** (guías clínicas, formularios oficiales, literatura revisada por pares) e información **promocional** de la industria farmacéutica: esta última no es necesariamente falsa, pero está diseñada para vender, no para informar de manera neutral, y suele resaltar beneficios minimizando riesgos.",
        "",
        "#### El lugar de la farmacología entre las ciencias biomédicas",
        "",
        "La farmacología no es una disciplina aislada: es el puente entre las ciencias básicas (química, bioquímica, fisiología) y la aplicación clínica. De ahí se derivan sus grandes ramas, que vas a recorrer una por una en los módulos siguientes de este curso:",
        "",
        "* **Farmacodinamia** — qué le hace el fármaco al organismo (mecanismo de acción, receptores, dosis-respuesta). Módulo 2.",
        "* **Farmacocinética** — qué le hace el organismo al fármaco (absorción, distribución, metabolismo, excreción). Módulo 3.",
        "* **Farmacología clínica** — variabilidad de la respuesta en personas reales, reacciones adversas, farmacovigilancia. Módulo 4.",
        "* **Investigación farmacológica** — cómo se descubre y valida un fármaco antes y durante su uso en humanos, desde el laboratorio hasta el ensayo clínico. Módulo 5.",
        "* **Farmacología del sistema nervioso central** — la aplicación concreta de todo lo anterior a un sistema particular, con su propia farmacoterapia. Módulos 6 y 7.",
        "",
        "#### En resumen",
        "",
        "* **Principio activo → fármaco → medicamento**: del ingrediente puro al producto terminado.",
        "* **Droga** (amplio) ≠ **fármaco** (uso terapéutico caracterizado) ≠ **estupefaciente** (categoría legal por potencial de abuso).",
        "* Todo fármaco tiene tres nombres posibles: **químico** (estructura), **DCI/INN** (genérico universal) y **comercial** (marca del fabricante).",
        "* Las fuentes de información se ordenan por distancia al dato original: **primaria → secundaria → terciaria**, y conviene distinguir la información independiente de la promocional.",
        "* La farmacología se organiza en ramas que se recorren en orden en este curso: farmacodinamia, farmacocinética, farmacología clínica, investigación farmacológica, y su aplicación al sistema nervioso central.",
      ].join("\n"),
    },
    {
      slug: "farmacodinamia",
      title: "Módulo 2: Farmacodinamia",
      description:
        "Tipos de acción farmacológica. **Curvas dosis-respuesta** (concentración–efecto), potencia y eficacia. Dianas y mecanismos: **familias de receptores**, transducción de señales y **segundos mensajeros**, regulación de receptores. Mecanismos inespecíficos. **Interacciones** farmacológicas: incompatibilidades, interacciones farmacocinéticas y farmacodinámicas (sinergismo y antagonismo).",
      exercises: [
        {
          question: [
            "**Relación de términos.** Relacione cada mecanismo con el fármaco/agente que mejor lo ejemplifica:",
            "",
            "**Términos:** 1. Acción \"scavenger\" (barredora de radicales) · 2. Anestésico general · 3. Anestésico local · 4. Antiácido neutralizante · 5. Antídoto quelante · 6. Enzima antioxidante · 7. Inhibidor de fosfodiesterasa 5 · 8. Laxante osmótico · 9. Terapia de sustitución",
            "",
            "**Agentes:** a. Vitamina E (alfa-tocoferol) · b. Perturbación de la membrana lipídica · c. Bloqueo de canales de sodio dependientes de voltaje · d. NaHCO₃ · e. EDTA · f. Catalasa · g. Sildenafilo · h. Lactulosa · i. Insulina recombinante",
          ].join("\n"),
          solution: [
            "1-a (vitamina E), 2-b (perturbación lipídica — teoría de Meyer-Overton para anestésicos inhalados), 3-c (bloqueo de canales de sodio — **no** el complejo GABA/Cl⁻, que es el blanco de los anestésicos *generales* IV, benzodiazepinas y barbitúricos), 4-d (NaHCO₃ neutraliza directamente el ácido gástrico), 5-e (EDTA quela cationes divalentes como plomo), 6-f (catalasa descompone peróxido de hidrógeno), 7-g (sildenafilo inhibe la degradación de GMPc), 8-h (lactulosa retiene agua en el colon por ósmosis), 9-i (insulina recombinante reemplaza la hormona endógena faltante).",
            "",
            "**Nota importante:** en bancos de términos de este estilo es fácil que \"anestésico local\" quede emparejado por descarte con \"complejo GABA/Cl⁻\" — es un error frecuente. Los anestésicos **locales** (lidocaína y similares) bloquean canales de sodio; el complejo GABA/Cl⁻ es el blanco de los anestésicos **generales** intravenosos, no de los locales.",
          ].join("\n"),
        },
        {
          question: [
            "**Comente.** Mencione cuatro clases de fármacos cuyo efecto NO se debe a una interacción fármaco-receptor específica: explique brevemente el mecanismo de cada una y en qué situación clínica es aprovechable.",
          ].join("\n"),
          solution: [
            "**1. Neutralización ácido-base** — antiácidos como el NaHCO₃: neutralizan químicamente el ácido gástrico, útiles en dispepsia/reflujo.",
            "",
            "**2. Quelación** — EDTA y agentes similares: forman complejos estables con cationes metálicos divalentes; útiles como antídoto en intoxicación por metales pesados (plomo).",
            "",
            "**3. Efecto osmótico** — manitol (reduce presión intracraneal en edema cerebral, extrayendo agua del tejido por gradiente osmótico) y lactulosa (laxante, retiene agua en el colon).",
            "",
            "**4. Perturbación de membranas lipídicas** — anestésicos generales inhalados: se disuelven en la bicapa lipídica de las neuronas y alteran su función eléctrica sin necesitar un receptor específico (teoría de Meyer-Overton).",
            "",
            "*(Nota: furosemida no pertenece a este grupo aunque a veces se le clasifica erróneamente como osmótica — es un diurético que inhibe específicamente el cotransportador Na⁺-K⁺-2Cl⁻, un mecanismo fármaco-transportador, no un mecanismo inespecífico.)*",
          ].join("\n"),
        },
        {
          question: [
            "**Comente el significado de:** actividad intrínseca, eficacia, potencia, agonismo parcial / antagonismo parcial, segundo mensajero.",
          ].join("\n"),
          solution: [
            "**Actividad intrínseca**: capacidad de un fármaco, ya unido al receptor, de activarlo y producir respuesta. Va de 0 (antagonista puro) a 1 (agonista total).",
            "",
            "**Eficacia**: el efecto máximo que puede producir un fármaco — el \"techo\" de su curva dosis-respuesta.",
            "",
            "**Potencia**: cuánta dosis hace falta para lograr un efecto dado; se compara por la DE₅₀ (a menor DE₅₀, mayor potencia). Es independiente de la eficacia: un fármaco puede ser muy potente (poca dosis) y poco eficaz (techo bajo), o al revés.",
            "",
            "**Agonismo parcial / antagonismo parcial**: un agonista parcial tiene actividad intrínseca entre 0 y 1 — incluso ocupando el 100 % de los receptores no alcanza el efecto máximo de un agonista total. Frente a un agonista total presente en el mismo sistema, compite por el receptor y **reduce** el efecto máximo posible: por eso, en ese contexto, también se comporta como un antagonista (parcial).",
            "",
            "**Segundo mensajero**: molécula intracelular (AMPc, GMPc, IP₃, DAG, Ca²⁺) que amplifica y propaga la señal iniciada por un receptor de membrana, traduciéndola en una respuesta celular concreta.",
          ].join("\n"),
        },
        {
          question: [
            "**Las siguientes frases sobre curvas dosis-respuesta son ciertas, EXCEPTO:**",
            "",
            "a) La representación gráfica \"sigmoide\" se logra cuando las dosis se expresan en escala logarítmica.",
            "b) El parámetro DE₅₀ es un indicativo de la potencia de un fármaco.",
            "c) El índice terapéutico relaciona las dosis tóxicas con las dosis efectivas para un efecto farmacológico dado.",
            "d) Con una dosis puntual, los individuos tratados dan respuestas de diferente intensidad.",
            "e) En una curva dosis-respuesta, al doblar la dosis siempre se dobla el efecto.",
          ].join("\n"),
          solution: [
            "**Falsa: e.**",
            "",
            "La relación dosis-respuesta es **sigmoidea**, no lineal: cerca del techo (eficacia máxima) el sistema se satura y doblar la dosis apenas cambia el efecto. Las demás afirmaciones son correctas: (a) la escala logarítmica linealiza la parte central de la sigmoide; (b) la DE₅₀ indica potencia (menor DE₅₀ = mayor potencia); (c) el índice terapéutico compara dosis tóxica con dosis eficaz; (d) la variabilidad interindividual hace que una misma dosis produzca distintas intensidades de respuesta entre personas.",
          ].join("\n"),
        },
        {
          question: [
            "**Elija la respuesta correcta.** Los agonistas adrenérgicos beta2 se unen a receptores que son:",
            "",
            "A) Ácidos nucleicos",
            "B) Siete proteínas de transmembrana",
            "C) Canales iónicos activados por ligando",
            "D) Lípidos como el DAG",
          ].join("\n"),
          solution: [
            "**Respuesta: B.**",
            "",
            "Los receptores beta-adrenérgicos son receptores acoplados a proteína G (GPCR), con estructura de siete dominios transmembrana (7TM). No son canales iónicos, ni ácidos nucleicos, ni lípidos — el DAG es, de hecho, un segundo mensajero producido río abajo de otro tipo de GPCR (los acoplados a Gq), no un receptor.",
          ].join("\n"),
        },
      ],
      chapter: [
        "#### El problema que resuelve la farmacodinamia",
        "",
        "El Módulo 1 fijó el vocabulario; este módulo empieza a responder la primera pregunta realmente farmacológica: **¿qué le hace el fármaco al organismo, y por qué mecanismo?** Esa es, precisamente, la definición de farmacodinamia — en contraste con la farmacocinética (Módulo 3), que pregunta lo inverso: **qué le hace el organismo al fármaco**. Piensa en esta distinción como la diferencia entre estudiar el efecto de un actor sobre el escenario (farmacodinamia) y estudiar cómo el escenario transporta, transforma y finalmente expulsa a ese actor (farmacocinética). Ambas preguntas son necesarias para entender por qué un medicamento funciona, cuánto tarda y cuánto dura.",
        "",
        "#### Dos grandes caminos: mecanismos inespecíficos vs. interacción fármaco-receptor",
        "",
        "No todos los fármacos actúan de la misma manera. Algunos producen su efecto sin necesitar un receptor biológico específico — basta su presencia física o su reactividad química. Otros dependen enteramente de reconocer y unirse a una molécula diana concreta del organismo: el receptor.",
        "",
        "> Analogía: imagina dos formas de abrir una puerta. La primera es empujarla con suficiente fuerza física — no importa qué puerta sea, cualquier empujón suficientemente fuerte la abre (mecanismo **inespecífico**). La segunda es usar una llave hecha a la medida de esa cerradura exacta — solo esa llave, con esa forma precisa, encaja y gira el mecanismo (interacción **fármaco-receptor**, específica).",
        "",
        "#### Mecanismos inespecíficos: cuando no hace falta una llave",
        "",
        "Estos mecanismos dependen de propiedades fisicoquímicas simples — no de un reconocimiento molecular fino — y por eso suelen ser rápidos, predecibles y poco sensibles a mutaciones puntuales del organismo:",
        "",
        "* **Neutralización ácido-base** — un antiácido como el NaHCO₃ simplemente reacciona químicamente con el ácido gástrico y sube el pH. Es un antiácido *neutralizante*; no actúa por \"citoprotección\" (ese es un mecanismo distinto, mediado por prostaglandinas, típico de otros fármacos como el misoprostol).",
        "* **Quelación** — agentes como el EDTA forman complejos estables con cationes metálicos (plomo, entre otros divalentes), \"secuestrándolos\" para facilitar su excreción. Es la base del antidotismo en intoxicaciones por metales pesados.",
        "* **Efecto osmótico** — el manitol, al ser una molécula osmóticamente activa que no se reabsorbe fácilmente, arrastra agua consigo: se usa para reducir la presión intracraneal en edema cerebral. La lactulosa, por el mismo principio en el colon, retiene agua y actúa como laxante.",
        "* **Perturbación de membranas lipídicas** — los anestésicos generales inhalados son moléculas muy liposolubles que se disuelven en la bicapa lipídica de las neuronas y alteran su función eléctrica de forma inespecífica (teoría de Meyer-Overton: la potencia anestésica correlaciona con la liposolubilidad, no con la afinidad por un receptor concreto).",
        "* **Acción \"scavenger\" (barredora de radicales libres)** — antioxidantes como la vitamina E \"atrapan\" especies reactivas de oxígeno antes de que dañen membranas y macromoléculas; es un mecanismo de reactividad química directa, reforzado por enzimas antioxidantes endógenas como la catalasa.",
        "* **Terapia de sustitución** — cuando el organismo no produce una molécula endógena (insulina en diabetes tipo 1), administrar esa misma molécula (insulina recombinante) no es, estrictamente, activar un mecanismo *nuevo*: es reemplazar lo que falta.",
        "",
        "Un error frecuente aquí es clasificar cualquier diurético como \"osmótico\": la **furosemida**, por ejemplo, no lo es — inhibe de forma específica el cotransportador Na⁺-K⁺-2Cl⁻ (NKCC2) en el asa ascendente de Henle, un mecanismo fármaco-transportador tan específico como cualquier interacción fármaco-receptor. El verdadero diurético osmótico de referencia es el manitol.",
        "",
        "#### Mecanismos específicos: la interacción fármaco-receptor",
        "",
        "La mayoría de los fármacos modernos, sin embargo, sí dependen de una \"llave\" molecular precisa: el **receptor**, una proteína (o, más raramente, otra macromolécula) capaz de reconocer selectivamente a un ligando —endógeno o farmacológico— e iniciar una respuesta biológica. Los receptores farmacológicos se agrupan en cuatro grandes familias, que difieren sobre todo en **qué tan rápido** transmiten la señal:",
        "",
        "* **Canales iónicos (receptores ionotrópicos)** — el propio receptor ES el canal; al unirse el ligando, se abre y deja pasar iones (Na⁺, Cl⁻, Ca²⁺). Respuesta en milisegundos. Ejemplo: el complejo GABA/Cl⁻.",
        "* **Receptores acoplados a proteína G (GPCR, \"7TM\")** — siete dominios transmembrana; al activarse, acoplan y activan una proteína G intracelular (Gs, Gi, Gq), que a su vez modula enzimas o canales. Respuesta en segundos. Ejemplo: receptores adrenérgicos beta2.",
        "* **Receptores con actividad enzimática intrínseca** — típicamente tirosina cinasas; la unión del ligando dispara directamente una cascada enzimática (fosforilación de proteínas). Respuesta en minutos-horas. Ejemplo: receptor de insulina.",
        "* **Receptores intracelulares/nucleares** — el receptor está en el citosol o el núcleo; el ligando (típicamente lipofílico, como una hormona esteroidea) lo atraviesa la membrana y se une, y el complejo regula directamente la transcripción de genes. Respuesta en horas-días. Ejemplo: receptor de glucocorticoides, que es citosólico y se transloca al núcleo tras unirse a su ligando.",
        "",
        "> Analogía: piensa en estas cuatro familias como cuatro formas distintas de \"tocar el timbre\" de una casa. El canal iónico es una puerta que se abre de inmediato al girar la llave — instantáneo. El GPCR es un timbre que activa una campana interna (la proteína G) que, a su vez, pone en marcha otros mecanismos dentro de la casa — hay un paso intermedio, pero sigue siendo rápido. El receptor enzimático es como activar una fábrica interna que empieza a producir cosas — toma más tiempo. El receptor nuclear es como dejar un mensaje directamente con el dueño de la casa, que decide reorganizar los planos del edificio (la expresión génica) — el más lento, pero el de efecto más duradero.",
        "",
        "**Importante:** la proteína G (p. ej. Gs) **no es** el receptor 7TM — es su transductor intracelular. El receptor 7TM es quien reconoce al ligando en la membrana; la proteína G es la pieza que ese receptor activa por dentro.",
        "",
        "#### Los segundos mensajeros: amplificando la señal hacia adentro de la célula",
        "",
        "Una vez activada la proteína G, la señal se propaga mediante **segundos mensajeros** — moléculas intracelulares que amplifican la señal original (una sola molécula de ligando puede terminar generando miles de moléculas de segundo mensajero) y la traducen en respuestas celulares concretas:",
        "",
        "* **AMPc** — generado por la adenilato ciclasa (activada por Gs, inhibida por Gi).",
        "* **GMPc** — generado por la guanilato ciclasa; el sildenafilo actúa inhibiendo la enzima que lo degrada (fosfodiesterasa 5), prolongando su efecto vasodilatador.",
        "* **IP₃ y DAG** — generados por la fosfolipasa C (activada por Gq); el IP₃ libera Ca²⁺ desde depósitos intracelulares, el DAG activa la proteína cinasa C.",
        "* **Ca²⁺ intracelular** — funciona como segundo mensajero por sí mismo, liberado tanto por IP₃ como por canales de voltaje.",
        "",
        "#### Agonismo, antagonismo y el techo de la respuesta",
        "",
        "Que un fármaco se una a un receptor no garantiza que lo active. La **actividad intrínseca** describe justamente eso: la capacidad de activar el receptor una vez unido, en una escala de 0 (no lo activa en absoluto) a 1 (lo activa al máximo posible). Un **agonista total** tiene actividad intrínseca = 1. Un **antagonista puro** se une pero no activa nada (actividad intrínseca = 0) — su único efecto es bloquear el sitio para que el agonista endógeno o farmacológico no pueda actuar. Un **agonista parcial** queda en medio: activa el receptor, pero incluso ocupando el 100 % de los receptores disponibles nunca alcanza el efecto máximo de un agonista total. Por eso, si se administra junto con un agonista total, el agonista parcial compite por el mismo sitio y termina *reduciendo* el efecto máximo alcanzable — comportándose, en ese contexto específico, como un antagonista parcial.",
        "",
        "De aquí surgen dos parámetros que conviene no confundir: la **eficacia** es el efecto máximo que un fármaco puede producir — el \"techo\" de su curva dosis-respuesta. La **potencia** es cuánta dosis hace falta para llegar a un efecto dado — se compara con la DE₅₀ (dosis efectiva 50): a menor DE₅₀, mayor potencia. Un fármaco puede ser muy potente pero poco eficaz, o viceversa: son ejes independientes.",
        "",
        "No todo antagonismo implica competir por el mismo receptor. El **antagonismo fisiológico** (o funcional) ocurre cuando dos sustancias actúan sobre receptores *distintos*, produciendo efectos *opuestos* que se cancelan mutuamente a nivel del sistema, no de la molécula. El ejemplo clásico es la adrenalina en el shock anafiláctico: no bloquea los receptores de histamina, sino que activa receptores adrenérgicos que producen el efecto fisiológico contrario (vasoconstricción, broncodilatación). Por el mismo principio, cuando la cafeína (antagonista de receptores de adenosina, con efecto estimulante) contrarresta la depresión del sistema nervioso central causada por el etanol (que potencia el GABA-A e inhibe al NMDA), **no** están compitiendo por el mismo receptor — es, de nuevo, antagonismo fisiológico entre dos sistemas de neurotransmisión distintos con efectos opuestos.",
        "",
        "#### La curva dosis-respuesta: potencia, eficacia y el límite de la sigmoide",
        "",
        "Si administras dosis crecientes de un fármaco y mides el efecto, obtienes una **curva dosis-respuesta**. Cuando la dosis se expresa en escala logarítmica, esa curva adopta una forma característica en \"S\" (sigmoide): al principio el efecto crece poco (dosis subumbral), luego crece casi linealmente en la zona media, y finalmente se **aplana** cerca del techo — el sistema se satura porque ya no quedan receptores libres para ocupar. Esta es la razón por la que, cerca del techo, **doblar la dosis no dobla el efecto**: es una de las trampas de examen más repetidas en este tema.",
        "",
        "> Analogía: piensa en llenar una sala con sillas numeradas y personas entrando una por una. Al principio, cada persona nueva que entra (\"dosis\") aumenta claramente la ocupación (\"efecto\"). Pero cuando la sala está casi llena, meter el doble de personas nuevas no duplica la ocupación — simplemente no hay más sillas libres. El \"techo\" de la sala es la eficacia máxima del sistema.",
        "",
        "Existen además dos formas de medir la respuesta: la **respuesta graduada**, continua y medible en un mismo individuo (p. ej. milímetros de mercurio de presión arterial, que sube o baja de forma gradual), y la **respuesta cuantal**, todo-o-nada, evaluada típicamente en una población a una dosis dada (el efecto está presente o ausente — por ejemplo, si una benzodiazepina logra o no el efecto ansiolítico esperado en cada persona de un grupo, a una dosis fija).",
        "",
        "El **índice terapéutico** (que ya viste como fórmula en el glosario: IT = DL₅₀/DE₅₀) resume en un solo número qué tan separadas están la dosis que cura y la dosis que daña — cuanto mayor, más margen de seguridad tiene el fármaco.",
        "",
        "#### Regulación de receptores: el sistema se adapta",
        "",
        "Los receptores no son estructuras fijas e inmutables: su número y su sensibilidad cambian con la exposición repetida a un ligando. La exposición prolongada a un agonista puede producir **desensibilización** o **regulación a la baja** (*down-regulation*) — menos receptores disponibles o receptores menos sensibles, la base de la tolerancia farmacológica. Al contrario, el bloqueo prolongado con un antagonista puede producir **regulación al alza** (*up-regulation*) — el organismo \"compensa\" fabricando más receptores, lo que explica por qué suspender abruptamente ciertos fármacos (betabloqueadores, por ejemplo) puede producir un efecto de rebote exagerado: hay más receptores disponibles de los que había antes de empezar el tratamiento.",
        "",
        "#### Interacciones farmacológicas",
        "",
        "Cuando dos o más fármacos coinciden en un mismo organismo (o incluso en la misma jeringa), pueden interactuar en distintos niveles:",
        "",
        "* **Incompatibilidades** — interacciones puramente fisicoquímicas, fuera del organismo (p. ej. dos fármacos que precipitan al mezclarse en la misma solución IV). No son farmacodinamia ni farmacocinética propiamente dichas: ocurren antes de que el fármaco entre al cuerpo.",
        "* **Interacciones farmacocinéticas** — un fármaco altera la absorción, distribución, metabolismo o excreción de otro (verás esto en profundidad en el Módulo 3 — inducción/inhibición enzimática, competencia por unión a proteínas, etc.).",
        "* **Interacciones farmacodinámicas** — ocurren en el sitio de acción: **sinergismo** (el efecto combinado supera la simple suma de los efectos individuales — potenciación) o **antagonismo** (un fármaco reduce o anula el efecto de otro, ya sea compitiendo por el mismo receptor o por antagonismo fisiológico en receptores distintos, como en los ejemplos de la adrenalina y la cafeína vistos arriba).",
        "",
        "#### En resumen",
        "",
        "* La farmacodinamia estudia **qué le hace el fármaco al organismo**; la farmacocinética (Módulo 3) estudia lo inverso.",
        "* Hay dos grandes caminos de acción: **mecanismos inespecíficos** (fisicoquímicos: neutralización, quelación, ósmosis, perturbación lipídica, scavengers, sustitución) e **interacción fármaco-receptor** (específica, mediada por una de cuatro familias de receptores: canales iónicos, GPCR/7TM, enzimáticos, nucleares).",
        "* Los GPCR transducen su señal a través de **proteínas G** y **segundos mensajeros** (AMPc, GMPc, IP₃/DAG, Ca²⁺) — la proteína G no es el receptor, es su transductor.",
        "* **Actividad intrínseca, eficacia y potencia** son tres ejes distintos que describen a un fármaco frente a su receptor; el **agonismo parcial** y el **antagonismo fisiológico** (receptores distintos, efectos opuestos) son las trampas conceptuales más frecuentes.",
        "* La curva dosis-respuesta es **sigmoide** en escala logarítmica: cerca del techo, doblar la dosis no dobla el efecto.",
        "* Los receptores se regulan con el uso: la exposición prolongada puede producir tolerancia (*down-regulation*) o, al suspender un antagonista, un rebote por *up-regulation*.",
        "* Las interacciones farmacológicas pueden ser incompatibilidades, farmacocinéticas o farmacodinámicas (sinergismo/antagonismo) — el Módulo 3 retoma justo el segundo tipo en profundidad.",
      ].join("\n"),
    },
    {
      slug: "farmacocinetica-adme",
      title: "Módulo 3: Farmacocinética — procesos ADME",
      description:
        "Formas farmacéuticas y **vías de administración**. Procesos de **absorción y distribución** (barreras, unión a proteínas, volumen de distribución). Procesos de **biotransformación** (fases I y II, citocromo P450) y **eliminación** (renal, biliar). Factores que afectan los procesos ADME.",
    },
    {
      slug: "farmacologia-clinica",
      title: "Módulo 4: Principios de farmacología clínica",
      description:
        "**Variabilidad en la respuesta** farmacológica: distribución poblacional, factores genéticos, edad, idiosincrasias, estados fisiológicos y patológicos. **Reacciones adversas a los medicamentos (RAM)**: clasificación y concepto de **farmacovigilancia**. **Monitorización terapéutica** de fármacos y nociones de farmacoepidemiología.",
    },
    {
      slug: "investigacion-farmacologia",
      title: "Módulo 5: Introducción a la investigación en farmacología",
      description:
        "Proceso de **investigación de los medicamentos**: investigación preclínica (principios y métodos), el animal de experimentación como reactivo biológico, ética y **alternativas** en experimentación animal, ensayos de **screening**. **Ensayos clínicos**: fases de la evaluación clínica y principios éticos (**Declaración de Helsinki**).",
    },
    {
      slug: "snc-introduccion",
      title: "Módulo 6: Introducción a la farmacología del SNC",
      description:
        "La **neurotransmisión como diana farmacológica**. Mediadores químicos en el SNC (glutamato, GABA, dopamina, serotonina, noradrenalina, acetilcolina). **Clasificación** de los fármacos con acción central.",
    },
    {
      slug: "snc-farmacoterapia",
      title: "Módulo 7: Farmacología del SNC — farmacoterapia",
      description:
        "**Anestesia balanceada**. Tratamiento farmacológico del **dolor y la inflamación**. **Sedantes, hipnóticos y ansiolíticos**. **Antidepresivos** y **neurolépticos**. **Antiparkinsonianos**, **antiepilépticos** y tratamiento del **Alzheimer**. **Farmacodependencias** y abuso de fármacos.",
    },
    {
      slug: "aspectos-legales",
      title: "Módulo 8: Aspectos legales y comerciales del uso de medicamentos",
      description:
        "Evaluación farmacológica en el proceso de **registro sanitario**. **Productos fitoterapéuticos**: marco regulatorio y evidencia.",
    },
  ],

  glossary: [
    { term: "Farmacodinamia", moduleSlug: "farmacodinamia", definition: "Estudio de **qué le hace el fármaco al organismo**: sus efectos bioquímicos y fisiológicos y su mecanismo de acción." },
    { term: "Farmacocinética", moduleSlug: "farmacocinetica-adme", definition: "Estudio de **qué le hace el organismo al fármaco**: absorción, distribución, metabolismo y excreción (ADME) en función del tiempo." },
    { term: "Curva dosis-respuesta", moduleSlug: "farmacodinamia", definition: "Relación entre la dosis (o concentración) y la magnitud del efecto. Define la **potencia** (posición, DE₅₀) y la **eficacia** (efecto máximo)." },
    { term: "Agonista / antagonista", moduleSlug: "farmacodinamia", definition: "**Agonista**: se une al receptor y produce respuesta. **Antagonista**: se une pero no activa; bloquea la acción del agonista (competitivo o no competitivo)." },
    { term: "Segundos mensajeros", moduleSlug: "farmacodinamia", definition: "Moléculas intracelulares (AMPc, GMPc, IP₃, Ca²⁺, DAG) que amplifican y transmiten la señal iniciada por un receptor de membrana." },
    { term: "Sinergismo / antagonismo", moduleSlug: "farmacodinamia", definition: "**Sinergismo**: el efecto combinado supera la suma (potenciación). **Antagonismo**: un fármaco reduce o anula el efecto de otro." },
    { term: "Biotransformación (fases I y II)", moduleSlug: "farmacocinetica-adme", definition: "**Fase I**: reacciones de funcionalización (oxidación por citocromo P450, reducción, hidrólisis). **Fase II**: conjugación (glucuronidación, sulfatación) que aumenta la hidrosolubilidad para la excreción." },
    { term: "Volumen de distribución (Vd)", moduleSlug: "farmacocinetica-adme", definition: "Volumen aparente en el que se distribuiría el fármaco para alcanzar la concentración plasmática medida: Vd = dosis / C₀." },
    { term: "Reacción adversa (RAM)", moduleSlug: "farmacologia-clinica", definition: "Respuesta nociva y no intencionada a un medicamento en dosis usadas para profilaxis, diagnóstico o tratamiento. Se clasifican en tipo A (dosis-dependientes) y tipo B (idiosincrásicas), entre otras." },
    { term: "Farmacovigilancia", moduleSlug: "farmacologia-clinica", definition: "Actividades de detección, evaluación, comprensión y prevención de las RAM y otros problemas relacionados con medicamentos." },
    { term: "Índice terapéutico", moduleSlug: "farmacologia-clinica", definition: "Relación entre la dosis que produce toxicidad y la dosis eficaz (p. ej. DL₅₀/DE₅₀). Cuanto mayor, más seguro el margen del fármaco." },
    { term: "Ensayo clínico — fases", moduleSlug: "investigacion-farmacologia", definition: "**Fase I** (seguridad, voluntarios sanos), **Fase II** (eficacia y dosis, pacientes), **Fase III** (confirmación frente a estándar), **Fase IV** (farmacovigilancia poscomercialización)." },
  ],

  formulas: [
    {
      name: "Índice terapéutico",
      expression: "IT = #{DL_{50}|DE_{50}}",
      variables: "DL_{50} = dosis letal 50 · DE_{50} = dosis efectiva 50",
      description: "Estima el **margen de seguridad** de un fármaco: cuánto separa la dosis eficaz de la dosis tóxica.",
      moduleSlug: "farmacologia-clinica",
      derivation:
        "Se obtiene de dos curvas dosis-respuesta cuantales: una para el efecto terapéutico y otra para la toxicidad (o letalidad). El cociente de sus valores medianos indica cuántas veces hay que aumentar la dosis eficaz para llegar a la tóxica. Un IT alto (> 10) da un margen amplio; fármacos como digoxina o litio tienen IT bajo y requieren monitorización.\nIT = índice terapéutico — adimensional.\nDL_{50} = dosis que produce el efecto tóxico/letal en el 50 % de la población — mg/kg.\nDE_{50} = dosis que produce el efecto terapéutico en el 50 % — mg/kg.",
    },
    {
      name: "Volumen de distribución",
      expression: "V_{d} = #{Dosis|C_{0}}",
      variables: "C_{0} = concentración plasmática extrapolada a tiempo cero",
      description: "Parámetro que relaciona la cantidad de fármaco en el cuerpo con su concentración plasmática; orienta sobre su **distribución tisular**.",
      moduleSlug: "farmacocinetica-adme",
      derivation:
        "Es un volumen **aparente**, no fisiológico: el que haría falta para que toda la dosis administrada estuviera a la concentración plasmática medida. Valores bajos (~5 L) indican fármaco confinado al plasma; valores muy altos (cientos de L) indican gran fijación a tejidos.\nV_{d} = volumen aparente de distribución — L o L/kg.\nDosis = cantidad de fármaco en el organismo (dosis IV) — mg.\nC_{0} = concentración plasmática a tiempo cero — mg/L.",
    },
    {
      name: "Vida media de eliminación",
      expression: "t_{1/2} = #{0,693 · V_{d}|CL}",
      variables: "CL = aclaramiento (clearance) · V_{d} = volumen de distribución",
      description: "Tiempo que tarda la concentración plasmática en reducirse a la mitad; determina la **frecuencia de dosificación** y el tiempo hasta el estado estacionario (~4–5 t½).",
      moduleSlug: "farmacocinetica-adme",
      derivation:
        "Para una cinética de primer orden, la constante de eliminación es k = CL/V_{d}, y el tiempo para que C caiga a la mitad es ln(2)/k = 0,693·V_{d}/CL. Depende por igual del aclaramiento y del volumen de distribución.\nt_{1/2} = vida media de eliminación — h.\nV_{d} = volumen de distribución — L.\nCL = aclaramiento plasmático — L/h.",
    },
  ],

  evaluation: [
    { name: "1er Parcial (semana 4)", weight: 20 },
    { name: "2do Parcial (semana 8)", weight: 20 },
    { name: "3er Parcial (semana 12)", weight: 20 },
    { name: "Evaluación final (semana 16)", weight: 20 },
    { name: "Participación, talleres, quices y tareas", weight: 20 },
  ],

  keyDates: [
    { name: "1er Parcial", weight: "20%" },
    { name: "2do Parcial", weight: "20%" },
    { name: "3er Parcial", weight: "20%" },
    { name: "Evaluación final", weight: "20%" },
  ],

  projects: [
    { title: "Talleres de discusión", category: "Taller" },
    { title: "Seminario / exposición", category: "Seminario" },
  ],

  bibliography: [
    { kind: "libro", reference: "Brunton L., Chabner B.A., Knollmann B.C. (Ed.). Goodman & Gilman. Las Bases Farmacológicas de la Terapéutica. Vol. I y II. McGraw-Hill Interamericana. México. 2012." },
    { kind: "libro", reference: "Hilal-Dandan R., Brunton L. (Ed.). Goodman & Gilman Manual de Farmacología y Terapéutica. 2ª ed. McGraw-Hill Education. México. 2015." },
    { kind: "libro", reference: "Katzung B.G. (Ed.). Farmacología Básica y Clínica. 12ª ed. McGraw-Hill Interamericana. México. 2013. (y Katzung's Basic & Clinical Pharmacology, T.W. Vanderah, 2024)." },
    { kind: "libro", reference: "Flórez J., Armijo J.A., Mediavilla A. Farmacología Humana. 6ª ed. Elsevier Masson. Barcelona. 2014." },
    { kind: "libro", reference: "Rang & Dale. Farmacología. M. Dale. 9ª ed. Elsevier. 2020." },
    { kind: "libro", reference: "Isaza C.A., Machado J.E., Machado M.E. y col. Fundamentos de Farmacología en Terapéutica. 7ª ed. Celsus. Colombia. 2020." },
    { kind: "libro", reference: "Golan D.E. (Ed.). Principios de Farmacología: Bases Fisiopatológicas del Tratamiento Farmacológico. Lippincott Williams & Wilkins. España. 2012." },
    { kind: "libro", reference: "Declaración de Helsinki de la AMM. Res. 008430 de 1993 (Min. Salud, Colombia). Ley 84 de 1989 (protección animal)." },
    { kind: "revista", reference: "British Journal of Pharmacology" },
    { kind: "revista", reference: "European Journal of Pharmacology" },
    { kind: "revista", reference: "Trends in Pharmacological Sciences" },
    { kind: "revista", reference: "Annual Review of Pharmacology and Toxicology" },
  ],
};
